<p>Melatonina e construită pas cu pas dintr-un aminoacid din mâncare, printr-un lanț biochimic care depinde de vitamina B6, zinc, fier, folat și B12 la fiecare etapă. Dacă oricare dintre acești cofactori lipsește, lanțul încetinește și producția de melatonină scade. Deficitele subclinice ale acestor nutrienți sunt frecvente și rareori asociate cu somnul, dar creierul le simte în fiecare noapte.</p>
<ul>
  <li>Melatonina nu apare din nimic: e produsul final al unui lanț biochimic care începe cu triptofanul și necesită cofactori preciși la fiecare etapă</li>
  <li>Vitamina B6 e cofactorul cel mai critic, fără ea conversia 5-HTP în serotonină se blochează aproape complet</li>
  <li>Zincul reglează activitatea enzimei care transformă serotonina în melatonină și deficitul său e răspândit, mai ales la vegetarieni și vârstnici</li>
  <li>Vitamina B12 influențează indirect producția de melatonină prin efectele sale pe ritmul circadian și pe metilare</li>
  <li>Fierul și folatul participă la etape mai puțin vizibile dar la fel de necesare ale lanțului de sinteză</li>
  <li>Deficitele multiple simultane sunt mai frecvente decât cele izolate și au efect cumulativ pe producția de melatonină</li>
  <li>Un plan alimentar bine construit poate corecta deficite ușoare fără suplimentare</li>
  <li>Suplimentarea țintită, în ordinea corectă, e indicată când aportul alimentar nu acoperă necesarul sau când absorbția e compromisă</li>
</ul>
<p>Ai auzit probabil că melatonina e hormonul somnului. Glanda pineală o secretă seara, ea semnalează creierului că e noapte și corpul se pregătește de somn. Dar de unde vine melatonina? Nu se materializează din întuneric. E construită, pas cu pas, printr-un lanț biochimic care începe cu un aminoacid din mâncare și necesită la fiecare etapă un set specific de vitamine și minerale. Dacă oricare dintre aceste elemente lipsește, lanțul se încetinește sau se oprește. Și rezultatul îl simți noaptea.</p>
<p>Ceea ce face acest subiect relevant nu e teoria biochimiei (deși e fascinantă), ci faptul că deficitele nutriționale care afectează producția de melatonină sunt extrem de frecvente în populația generală. Nu vorbim de carențe severe, de tipul scorbutului. Vorbim de deficite subclinice, moderate, pe care analizele obișnuite le ratează și pe care nimeni nu le asociază cu calitatea somnului. Dar creierul le simte. Și somnul arată în consecință.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Lanțul complet arată așa, și fiecare etapă merită înțeleasă.</p>
<p>Triptofanul e un aminoacid esențial, ceea ce înseamnă că organismul nu îl poate produce și trebuie să îl primească din alimente. Se găsește în carne, pește, ouă, brânză, semințe, nuci și leguminoase. Din intestin, triptofanul ajunge în sânge și trebuie să traverseze bariera hematoencefalică pentru a intra în creier. Această traversare e competitivă: triptofanul concurează cu alte aminoacide mari neutre (leucină, izoleucină, valină, fenilalanină, tirozină) pentru același transportor. Asta înseamnă că o masă foarte bogată în proteine nu crește neapărat triptofanul cerebral. Paradoxal, o masă cu proteine moderate plus carbohidrați îl crește, pentru că insulina eliberată de carbohidrați direcționează aminoacizii competitori spre mușchi, lăsând triptofanul să treacă mai ușor bariera.</p>
<p>În creier, triptofanul e convertit în 5-HTP (5-hidroxitriptofan) de enzima triptofan hidroxilază. Această enzimă necesită fier (sub forma de Fe2+) și tetrahidrobiopterină (BH4) ca cofactori. Un deficit de fier, chiar și subclinic, încetinește această primă etapă. BH4 la rândul său depinde de folat (vitamina B9) și vitamina B12 pentru regenerare. Deja la primul pas al lanțului, trei micronutriente sunt implicate.</p>
<p>Următoarea etapă e conversia 5-HTP în serotonină, realizată de enzima decarboxilază a aminoacizilor aromatici (AADC). Cofactorul absolut necesar aici e vitamina B6, sub forma sa activă, piridoxal-5-fosfat (PLP). Aceasta e probabil cea mai vulnerabilă etapă a întregului lanț. Fără B6 suficient, 5-HTP se acumulează și serotonina nu se formează în cantitate adecvată. Efectele se simt pe două fronturi: dispoziție scăzută ziua (serotonina e neurotransmițător al stării de bine) și melatonină redusă noaptea.</p>
<p>Serotonina e apoi convertită în N-acetilserotonină de enzima AANAT (arilalkilamină N-acetiltransferază), iar aceasta e transformată în melatonină de enzima HIOMT (hidroxiindol-O-metiltransferază). Zincul reglează activitatea AANAT, iar SAMe (S-adenozilmetionină, un donator de grupări metil derivat din ciclul metioninei) e necesar pentru HIOMT. SAMe depinde la rândul său de vitamina B12, folat și vitamina B6 pentru regenerare în ciclul metioninic.</p>
<p>Să recapitulăm cofactorii critici ai întregului lanț: fier, folat, vitamina B12, vitamina B6 și zinc. Fiecare are un rol specific, și deficitul oricăruia poate reduce cantitatea finală de melatonină. Dar în practică, deficitele nu vin singure. O persoană cu alimentație dezechilibrată sau cu absorbție compromisă (probleme gastrice, medicamente, vârstă înaintată) are adesea deficite multiple simultane, iar efectul cumulativ e mai mare decât suma părților.</p>
<p>Vitamina B6 merită atenție suplimentară. Studiile au arătat că nivelurile de PLP (formă activă) scad cu vârsta, sunt mai scăzute la fumători, la consumatorii de alcool și la femeile care folosesc contraceptive orale. Un studiu publicat de Lichstein et al. în Journal of Sleep Research (2007) a găsit că nivelurile scăzute de B6 corelează cu calitate mai slabă a somnului la adulți. Surse alimentare bune: pieptul de pui (0.5 mg per 100 g), bananele (0.4 mg per bucată), cartofii copți cu coajă (0.4 mg per bucată medie), năut (0.5 mg per cană). Necesarul zilnic recomandat e 1.3-1.7 mg, dar mulți nutriționiști de medicină funcțională sugerează că necesarul optim e mai mare, în jur de 2-5 mg.</p>
<p>Zincul e la fel de subestimat. Participă nu doar la conversia serotoninei în melatonină, ci și la funcționarea receptorilor GABA și la modularea inflamației. Un studiu publicat de Rondanelli et al. în Journal of the American Geriatrics Society (2011) a arătat că o combinație de melatonină, magneziu și zinc a îmbunătățit calitatea somnului la vârstnici mai mult decât melatonina singură, sugerând că zincul și magneziul optimizează contextul în care melatonina acționează. Sursele cele mai bogate: stridii (74 mg per 100 g, un adevărat campion), carnea roșie (4.8 mg per 100 g), semințele de dovleac (7.8 mg per 100 g), lintea (2.5 mg per cană gătită). Necesarul zilnic: 8-11 mg. Biodisponibilitatea zincului din surse vegetale e mai mică din cauza fitatului, ceea ce explică de ce vegetarienii au risc mai mare de deficit.</p>
<p>Vitamina B12 acționează mai indirect pe melatonină dar nu mai puțin important. Studiile lui Mayer et al., publicate în Neuropsychopharmacology (1996), au arătat că B12 influențează secreția de melatonină prin efecte pe ritmul circadian, posibil prin reglarea expresiei genelor ceas. Deficitul de B12 e frecvent la vegetarieni și vegani (B12 vine aproape exclusiv din surse animale), la vârstnici (absorbția scade după 50 de ani) și la persoanele cu gastrită atrofică sau pe medicamente antiacide. Surse: ficat de vită (67 mcg per 100 g), scoici (84 mcg per 100 g), sardine (8.9 mcg per 100 g), ouă (1.1 mcg per ou). Necesarul zilnic: 2.4 mcg, dar absorbția variază enorm.</p>
<p>Fierul e cofactor al primei etape (triptofan spre 5-HTP) și deficitul său e cea mai frecventă carență nutrițională la nivel global, afectând circa 25% din populație conform OMS. La femei în perioada fertilă, prevalența e și mai mare. Simptomele clasice (oboseala, paloare, dificultate de concentrare) se suprapun cu cele ale somnului prost, făcând distincția dificilă fără analize. Feritina serică e cel mai bun marker: sub 30 ng/ml indică depozite insuficiente, chiar dacă hemoglobina e normală.</p>
<h2>Ce alimentează problema</h2>
<p>Dieta modernă procesuală e primul vinovat. Făina albă a pierdut zincul, magneziul și vitaminele B din boabele integrale. Alimentele ultraprocesate, care constituie 50-60% din aportul caloric în țările dezvoltate, sunt sărace în micronutriente și bogate doar în calorii goale. Poți mânca suficient caloric și să fii în deficit de cofactori simultan.</p>
<p>Stresul cronic consumă vitamine B și zinc cu o viteză crescută. Cortizolul crescut crește turnoverul de B6, iar zincul e mobilizat din țesuturi în condiții de stres pentru a susține funcția imunitară. O persoană stresată cronic are simultan nevoie mai mare de acești nutrienți și aport mai mic (stresul favorizează alimentația rapidă și procesuală).</p>
<p>Absorbția intestinală compromisă multiplică problema. Gastrita, boala celiacă, boala Crohn, sindromul intestinului iritabil, dar și utilizarea cronică de antiacide (omeprazol, ranitidină) reduc absorbția fierului, B12 și zincului. Poți mânca corect și să absorbi insuficient.</p>
<p>Consumul de alcool reduce absorbția B12 și folatului, crește excreția de zinc și interferează cu metabolismul B6. Efectele sunt proporționale cu consumul și se acumulează în timp.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): planul alimentar</h3>
<p>Construiește mesele în jurul alimentelor care furnizează cofactorii critici simultan. Nu e vorba de a adăuga un aliment magic, ci de a restructura puțin ceea ce deja mănânci.</p>
<p>Micul dejun optim pentru producția de melatonină: ouă (B12, B6, triptofan, zinc, fier), spanac sau rucolă (folat, fier, magneziu), o felie de pâine integrală (B6, zinc, magneziu), semințe de floarea-soarelui sau dovleac (zinc, magneziu, triptofan). Această combinație furnizează toți cofactorii principali într-o singură masă.</p>
<p>Prânzul: proteine animale sau leguminoase (triptofan, B12, fier, zinc) cu legume verzi (folat) și cereale integrale (B6, magneziu). Exemplu concret: piept de pui cu orez brun și broccoli. Sau linte cu quinoa și salată de spanac.</p>
<p>Cina (ușoară, cu 3 ore înainte de culcare): pește (somon, sardine, macrou) pentru B12, omega-3 și triptofan, cu legume gătite. Sau o supă de leguminoase cu legume verzi. Combinația de proteine moderate cu carbohidrați complecși la cină facilitează traversarea triptofanului în creier, așa cum am explicat mai sus.</p>
<p>Gustarea de seară (dacă e necesară): un iaurt cu o banană și câteva nuci oferă triptofan, B6, magneziu și calciu într-o combinație care susține specific producția nocturnă de melatonină.</p>
<p>Alimentele de evitat sau limitat: cafeaua excesivă (reduce absorbția fierului și crește excreția de magneziu), alcoolul (interferează cu B12, B6, zinc, folat), alimentele ultraprocesate (calorii fără cofactori).</p>
<p>O mențiune despre combinații: vitamina C crește absorbția fierului non-hem (din surse vegetale) cu 200-300%. O lămâie stoarsă pe linte sau spanac face o diferență reală în absorbție. Cafeaua și ceaiul, consumate în timpul mesei, reduc absorbția fierului cu 40-60% din cauza taninurilor. Dacă ai suspiciune de deficit de fier, separă cafeaua de mese cu cel puțin o oră.</p>
<h3>Faza 2 (săptămânile 3-6): evaluare și suplimentare țintită</h3>
<p>Dacă după două săptămâni de alimentație optimizată somnul nu s-a îmbunătățit, analizele de laborator pot clarifica unde e deficitul. Ce merită cerut: feritina serică (fierul), vitamina B12 serică sau holotranscobalamina (mai sensibilă), folat seric, piridoxal-5-fosfat (forma activă a B6, rar cerut dar disponibil), zinc seric (imperfect dar orientativ) și hemoglobina cu formula leucocitară (pentru anemie).</p>
<p>Ordinea suplimentării contează. Nu suplimenta totul simultan, pentru că nu vei ști ce funcționează și ce nu.</p>
<p>Prima prioritate: vitamina B6 (piridoxal-5-fosfat, formă activă), 25-50 mg zilnic. E cofactorul cel mai direct al conversiei 5-HTP în serotonină și deficitul său e cel mai frecvent limitator al producției de melatonină. Efectele se pot observa în 1-2 săptămâni. Nu depăși 100 mg zilnic cronic, deoarece dozele mari pe termen lung pot cauza neuropatie periferică (amorțeală în mâini și picioare).</p>
<p>A doua prioritate: zincul (zinc picolinat sau zinc bisglichinat), 15-30 mg zilnic, luat seara, pe stomac gol sau cu o gustare mică. Zincul și cuprul concurează pentru absorbție, deci suplimentarea cu zinc peste 30 mg pe termen lung necesită adăugarea a 1-2 mg de cupru pentru a preveni deficitul indus. Efectele pe somn apar în 2-4 săptămâni.</p>
<p>A treia prioritate: vitamina B12 (metilcobalamină sau hidroxocobalamină, nu cianocobalamină), 500-1000 mcg sublingual zilnic. Relevant mai ales dacă ești vegetarian, vegan, ai peste 50 de ani sau iei antiacide cronic. B12 e hidrosolubilă și excesul se elimină renal, deci riscul de supradozare e minim.</p>
<p>Folatul (metilfolat, nu acid folic sintetic) 400-800 mcg zilnic, relevant mai ales dacă analizele confirmă deficit sau dacă ai mutația MTHFR (frecventă la 30-40% din populație), care reduce conversia acidului folic în formă activă.</p>
<p>Fierul se suplimentează DOAR cu confirmare de laborator a deficitului (feritină sub 30 ng/ml). Fierul în exces e toxic și nu se elimină ușor. Fier bisglicinat, 25-50 mg, pe stomac gol, cu vitamina C, departe de cafea și lactate. Monitorizare feritină la 3 luni.</p>
<h3>Faza 3 (luna a doua și după): integrare</h3>
<p>După corectarea deficitelor individuale, o formulă de menținere poate simplifica lucrurile. Un complex B de calitate (cu forme active: P5P pentru B6, metilcobalamină pentru B12, metilfolat pentru B9) plus zinc și magneziu seara acoperă toți cofactorii principali ai lanțului triptofan-serotonină-melatonină.</p>
<p>Retestarea analizelor la 3 luni confirmă dacă suplimentarea funcționează. Feritina ar trebui să crească, B12 să se normalizeze, iar simptomele să se amelioreze.</p>
<p>Melatonina exogenă (supliment) merită considerată temporar (0.5-1 mg, cu 30 de minute înainte de culcare) în paralel cu corectarea cofactorilor, ca un suport pe termen scurt în timp ce producția endogenă se normalizează. Dar nu ca soluție permanentă. Obiectivul e ca propriul corp să producă suficientă melatonină, nu să depindă de sursa externă.</p>
<p>Un aspect care leagă acest articol de altele din serie: lumina naturală dimineața și întunericul seara rămân esențiale indiferent de statusul nutrițional. Poți avea toți cofactorii în cantitate optimă și să produci puțină melatonină dacă glanda pineală primește lumină albastră la ora 22:00. Nutriția și mediul lucrează împreună, nu alternativ.</p>
<h2>Unde te lasă toate astea</h2>
<p>Producția de melatonină nu e un buton pe care îl apești. E un lanț cu mai multe verigi, și rezistența lanțului e dată de veriga cea mai slabă. Poate că ai dormitor întunecat, program regulat și zero ecrane seara, și tot adormitul e dificil. Dacă e așa, merită să întrebi: are corpul meu materialele necesare pentru a construi melatonină?</p>
<p>Răspunsul nu necesită ghiceli. Necesită o privire atentă la ce mănânci, câteva analize de sânge țintite și disponibilitatea de a corecta ce găsești. Nu e un proces complicat. E un proces precis, cu pași clari și rezultate verificabile.</p>
<p>Începe cu farfuria de mâine. Ouă cu spanac dimineața, un pumn de semințe de dovleac la prânz, pește la cină. Și observă, pe parcursul următoarelor două săptămâni, dacă noaptea începe să arate diferit. Dacă da, ai găsit o parte din răspuns. Dacă nu, ai eliminat o variabilă și te poți uita mai departe cu mai multă claritate.</p>
