<ul>
  <li>Corpul consumă glucoză și în somn, iar creierul singur arde 5-6 grame pe oră, non-stop.</li>
  <li>Când rezervele de glicogen din ficat se epuizează noaptea, organismul eliberează adrenalină și cortizol ca să mobilizeze zahăr de urgență, iar aceste hormone te trezesc.</li>
  <li>Trezirea vine cu transpirații, puls rapid și anxietate, nu cu senzația clasică de foame, motiv pentru care mulți pun totul pe seama stresului.</li>
  <li>Cauza cea mai frecventă e banală: cina prea devreme, prea puține proteine și grăsimi la masa de seară, sau post prelungit involuntar de 12-14 ore.</li>
  <li>Alcoolul blochează producția hepatică de glucoză și amplifică problema, chiar și în cantități moderate.</li>
  <li>O gustare înainte de somn (proteine + grăsimi + carbohidrați complecși) funcționează rapid. Mulți oameni observă o diferență în 3-5 nopți.</li>
  <li>Dacă trezirile persistă după ajustarea alimentației, rezistența la insulină sau alte cauze metabolice merită investigate cu analize concrete.</li>
</ul>
<p>Există un paradox interesant legat de somnul și glucoza. Creierul nu se oprește din consumat energie când adormi. De fapt, în anumite faze ale somnului (REM în special), metabolismul cerebral e aproape la fel de activ ca în starea de veghe. Toată energia asta trebuie să vină de undeva, iar sursa principală rămâne glucoza din sânge.</p>
<p>Ceea ce face situația elegantă din punct de vedere fiziologic, dar complicată din punct de vedere practic, e că sistemul are mai multe niveluri de siguranță. Ficatul stochează glicogen și îl eliberează treptat. Dacă glicogenul scade prea mult, gluconeogeneza preia. Dacă și asta e insuficientă, hormonii de stres intervin ca ultima linie de apărare. Problema e că ultima linie de apărare vine cu efecte secundare pe care le simți: te trezești.</p>
<p>Un studiu din 2013 publicat de Jauch-Chara și colaboratorii la Universitatea din Lubeck a arătat că scăderea experimentală a glicemiei în timpul somnului la voluntari sănătoși a produs treziri spontane în 80% din cazuri, însoțite de creșterea frecvenței cardiace și a transpirațiilor. Participanții nu raportau foame. Raportau anxietate și agitație. Confuzia asta diagnostică e unul din motivele pentru care hipoglicemia nocturnă trece nedetectată ani de zile.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Gândește-te la ficatul tău ca la un generator de rezervă. În timpul zilei, mâncarea furnizează glucoză direct, și generatorul stă în standby. După cină, pe măsură ce glucoza din sânge scade, generatorul pornește și începe să elibereze glicogen stocat (un proces numit glicogenoliză). Un ficat adult sănătos poate stoca în jur de 80-100 de grame de glicogen, suficient pentru 12-16 ore în repaus.</p>
<p>Însă cantitatea reală de glicogen stocată variază enorm. Depinde de ce ai mâncat, cât ai mâncat și când. O cină bogată în proteine, grăsimi și carbohidrați complecși la 20:00 lasă ficatul bine aprovizionat. O cină ușoară la 18:00, dominată de paste sau orez alb, produce un vârf glicemic rapid (insulina se eliberează masiv ca răspuns), urmat de stocare rapidă și apoi consum rapid al rezervelor. Până la 1-2 dimineața, generatorul poate rămâne fără combustibil.</p>
<p>Când glicemia scade sub aproximativ 65-70 mg/dL, corpul trece în modul pe care fiziologii îl numesc răspuns contraregulator. Glandele suprarenale eliberează adrenalină și cortizol aproape simultan. Adrenalina face ce știe: crește pulsul, produce transpirații, activează alerta. Cortizolul trimite semnal către ficat să accelereze gluconeogeneza (fabricarea de glucoză nouă din aminoacizi și alte substraturi). Împreună, ridică glicemia înapoi în zona sigură.</p>
<p>Din perspectivă evolutivă, mecanismul e perfect calibrat. Dacă dormeai într-o peșteră și glicemia scădea periculos, trebuia să te trezești ca să cauți mâncare. Mecanismul nu e defect. E activat într-un context care nu mai corespunde.</p>
<p>Un aspect pe care cercetarea recentă l-a clarificat: hipoglicemia nocturnă nu e doar o problemă a diabeticilor. Persoanele cu rezistență la insulină (estimată să afecteze 30-40% din populația adultă din țările industrializate, conform datelor NHANES publicate în 2020) au un profil glicemic instabil. Insulina lor funcționează, dar corpul produce cantități exagerate ca să compenseze sensibilitatea redusă a celulelor. Rezultatul e o curbă glicemică în formă de roller coaster: vârf mare după masă, urmat de scădere bruscă. Noaptea, această instabilitate se manifestă prin episoade hipoglicemice pe care persoana le atribuie stresului, coșmarurilor sau "așa sunt eu, mă trezesc noaptea."</p>
<p>Și e un cerc vicios. Trezirile fragmentează somnul. Somnul fragmentat crește rezistența la insulină a doua zi (un studiu din 2010 condus de Tasali și colaboratorii la Universitatea din Chicago a demonstrat că fragmentarea selectivă a somnului profund a redus sensibilitatea la insulină cu 25% la voluntari sănătoși, în doar 3 nopți). Rezistența la insulină agravată face glicemia și mai instabilă noaptea următoare. Ciclul se auto-alimentează.</p>
<h2>Ce alimentează problema</h2>
<p>Postul prelungit involuntar e factorul cel mai frecvent și cel mai ușor de corectat. Mulți oameni mănâncă ultima dată la prânz sau iau o cină mică la 18:00 și se culcă la 23:00-00:00. Sunt 6-7 ore de post înainte de somn, plus încă 7-8 ore de somn. Total: 13-15 ore fără aport caloric. Pentru un metabolism flexibil cu rezerve hepatice normale, asta poate funcționa. Pentru cineva cu rezerve scăzute de glicogen, rezistență la insulină sau funcție hepatică suboptimală, e prea mult.</p>
<p>Compoziția cinei contează la fel de mult ca timing-ul. O farfurie de paste sau orez alb fără proteine sau grăsimi produce un vârf glicemic rapid. Insulina răspunde proporțional, coboară glicemia agresiv, iar după 3-4 ore nivelul de zahăr din sânge e mai jos decât era înainte de masă. Se numește hipoglicemie reactivă și e mecanismul cel mai frecvent al trezirilor în prima parte a nopții (între 00:00 și 3:00).</p>
<p>Alcoolul amplifică totul. Ficatul tratează alcoolul ca pe o prioritate (e o toxină și trebuie metabolizat înainte de orice altceva). Cât timp procesează alcoolul, gluconeogeneza e suprimată. În plus, alcoolul stimulează secreția de insulină, ceea ce coboară glicemia și mai rapid. Un studiu din 2007 condus de Richardson și colaboratorii a arătat că consumul de alcool seara a scăzut glicemia nocturnă cu 15-20 mg/dL față de serile fără alcool, la persoane fără diabet. Combinația clasică "vin la cină + cină ușoară + culcare la 3 ore după" e una dintre cele mai fiabile rețete pentru o trezire la 2 dimineața.</p>
<p>Exercițiul fizic intens seara consumă glicogenul muscular și hepatic. Fără o masă de refacere adecvată după antrenament (cu carbohidrați suficienți pentru a reîmplini glicogenul), intrarea în somn se face cu rezerve deja scăzute.</p>
<p>Un factor mai subtil: cafeaua după-amiaza. Cofeina crește cortizolul și stimulează secreția de insulină, iar efectul se resimte ore întregi după consum (timpul de înjumătățire al cofeinei e 5-6 ore). O cafea la 15:00 încă influențează metabolismul glucozei la 23:00.</p>
<h2>Ce se poate face concret</h2>
<h3>Faza 1 (săptămânile 1-2): timing-ul și compoziția mesei de seară</h3>
<p>Cea mai simplă intervenție cu efect imediat e o gustare mică cu 30-60 de minute înainte de culcare. Scopul e să furnizezi ficatului combustibil cu eliberare lentă care să acopere primele 4-6 ore de somn. Combinația care funcționează conține proteine, grăsimi sănătoase și o cantitate mică de carbohidrați complecși. Proteinele și grăsimile încetinesc absorbția, iar carbohidrații complecși oferă glucoză treptat, fără vârf.</p>
<p>Variante concrete care funcționează: o lingură de unt de arahide pe pâine integrală (aproximativ 200 de calorii). Un pumn de nuci cu o banană mică. 30 de grame de brânză cu câțiva biscuiți integrali. Iaurt grecesc cu semințe de dovleac și puțin miere. Fiecare combinație oferă eliberare lentă de glucoză pe parcursul a 4-6 ore.</p>
<p>În paralel, cina merită restructurată. Nu e vorba de a mânca mai mult, ci de a schimba proporțiile. Dacă cina e predominant carbohidrați (paste, orez, pâine), adăugarea de proteine (pește, pui, ouă, leguminoase) și grăsimi (ulei de măsline, avocado, nuci) schimbă radical curba glicemică de după masă. Aceeași cantitate de calorii produce o glicemie mult mai stabilă când vine dintr-o combinație echilibrată de macronutrienți.</p>
<p>Timing-ul cinei contează: dacă te culci la 23:00, o cină la 19:00-20:00 e rezonabilă. O cină la 17:00-18:00 lasă un interval prea lung, în care gustarea de seară devine obligatorie, nu opțională.</p>
<h3>Faza 2 (săptămânile 3-4): mișcare, tipare și testare</h3>
<p>Activitatea fizică regulată crește sensibilitatea la insulină, probabil cea mai eficientă intervenție pe termen lung pentru stabilitatea glicemică. Dar timing-ul contează. Exercițiul intens după ora 20:00 consumă glicogenul și ridică cortizolul exact când ambele ar trebui să fie stabile. O plimbare ușoară de 15-20 de minute după cină are efectul opus: studiul lui Reynolds și colaboratorii, publicat în Diabetologia în 2016, a arătat că o plimbare de 10 minute după masă a redus vârful glicemic postprandial cu 22% comparativ cu o singură sesiune de 30 de minute înainte de masă. Mișcarea ușoară după cină ajută la stabilizarea glicemiei pe care o ai deja, fără să consume rezervele de care ai nevoie noaptea.</p>
<p>E momentul să observi tiparele. Un jurnal simplu poate clarifica mult: notează ora cinei, ce ai mâncat, ora gustării, dacă ai consumat alcool și dacă ai avut treziri nocturne. După două săptămâni, corelațiile devin vizibile. Anumite combinații de alimente produc treziri în mod repetat, altele nu.</p>
<p>Componenta psihologică merită menționată. Anxietatea legată de somn ("iar mă voi trezi la 2 dimineața") crește cortizolul presomn, care la rândul lui destabilizează glicemia. E un al doilea cerc vicios, suprapus pe cel metabolic. Dacă jurnalul arată că trezirile s-au redus cu gustarea de seară dar anxietatea anticipatorie persistă, tehnici simple de respirație diafragmatică (4 secunde inspir, 7-8 secunde expir, 5 minute înainte de culcare) pot ajuta la reducerea cortizolului anticipator.</p>
<p>Testarea directă: un glucometru clasic folosit imediat la trezirea nocturnă oferă datele cele mai utile. O valoare sub 70 mg/dL confirmă hipoglicemia. O valoare normală (80-100 mg/dL) sugerează că altceva produce trezirea (cortizol, apnee, reflux). E o informație simplă care poate economisi luni de căutare în direcția greșită.</p>
<h3>Faza 3 (luna a doua și după): cauze structurale și intervenții nutriționale țintite</h3>
<p>Dacă gustarea de seară și restructurarea cinei nu au rezolvat trezirile după 3-4 săptămâni, cauza e probabil mai profundă decât un simplu deficit de glicogen.</p>
<p>Din perspectivă nutrițională, câțiva nutrienți specifici influențează metabolismul glucozei nocturn. Magneziul (300-400 mg de citrat sau glicanat de magneziu seara) îmbunătățește sensibilitatea la insulină. Un studiu din 2003 publicat în Journal of the American College of Nutrition de Rodriguez-Moran și Guerrero-Romero a arătat că suplimentarea cu magneziu a îmbunătățit sensibilitatea la insulină cu 10% după 4 luni, la persoane cu rezistență la insulină. Cromul (200-400 mcg de picolinat de crom) are și el date privind îmbunătățirea toleranței la glucoză, deși efectul e modest.</p>
<p>Fibrele solubile la cină (leguminoase, ovăz, semințe de in) încetinesc absorbția glucozei și produc o curbă glicemică mai plată. Oțetul de mere diluat (1-2 linguri în apă, înainte de cină) a arătat în mai multe studii mici că reduce vârful glicemic postprandial cu 20-30%, probabil prin încetinirea golirii gastrice.</p>
<p>Din punct de vedere medical, un set de analize poate clarifica situația: glicemie à jeun, insulină à jeun, hemoglobină glicozilată (HbA1c) și indexul HOMA-IR. HOMA-IR e un calcul simplu din glicemie și insulină à jeun care estimează gradul de rezistență la insulină. O valoare peste 2.5 sugerează rezistență semnificativă. Funcția hepatică merită evaluată și ea: steatoza hepatică (infiltrarea grasime a ficatului) afectează estimativ 25-30% din populația adultă și reduce capacitatea ficatului de a stoca și elibera glicogen eficient.</p>
<p>Un monitor continuu de glucoză (CGM) e instrumentul ideal, deși nu ieftin. Senzorul mic aplicat pe braț măsoară glicemia la fiecare 5 minute și arată exact ce se întâmplă în nopțile cu treziri versus cele fără. Corelația devine vizibilă imediat: trezire la 2:30, glicemie la 58 mg/dL. Sau trezire la 2:30, glicemie la 92 mg/dL (caz în care cauza nu e glicemică și trebuie căutată în altă parte).</p>
<p>Pentru persoanele cu diabet de tip 1 sau tip 2 aflate pe insulină sau sulfoniluree, hipoglicemia nocturnă e o problemă medicală care necesită ajustarea tratamentului, nu doar a alimentației. Dozele de insulină bazală luate seara pot fi prea mari. Sulfoniluree precum glibenclamidul sau glimepiridul au durată lungă de acțiune și pot scădea glicemia excesiv pe parcursul nopții. Asta nu se rezolvă cu gustări, ci cu recalibrarea medicației împreună cu medicul.</p>
<h2>Unde te lasă toate astea</h2>
<p>Partea frumoasă a acestei probleme, dacă poate fi numită frumoasă, e că soluția de prima linie e atât de simplă încât pare aproape trivial: o gustare înainte de somn, cu proteine și grăsimi, în jur de 200 de calorii. Mulți oameni care se trezeau de 2-3 ori pe noapte de luni de zile observă o diferență din primele nopți. E rar în medicină să ai un test atât de rapid și de ieftin: încerci o săptămână și vezi dacă funcționează.</p>
<p>Dacă nu funcționează, informația e tot utilă. Înseamnă că problema nu e simplu deficit de glicogen și merită investigată mai departe. Datele de la glucometru sau analizele metabolice duc o întrebare vagă ("de ce mă trezesc noaptea?") spre un răspuns specific.</p>
<p>Cercetarea despre stabilitatea glicemică nocturnă și calitatea somnului e încă tânără. Un studiu din 2022 publicat de Tsereteli și colaboratorii în PLOS Biology, folosind date de la 953 de participanți cu CGM, a arătat că variabilitatea glicemică nocturnă a corelat cu fragmentarea somnului independent de alți factori. Direcția e clară și intervențiile sunt lipsite de riscuri.</p>
<p>Dacă ai treziri nocturne recurente și nu ai încercat niciodată o gustare de seară structurată, există motive bune să începi de acolo.</p>
