<p>Ca să inițieze somnul, corpul face ceva contraintuitiv: încălzește mâinile și picioarele ca să disipeze căldura din interior. Dacă dormitorul e prea cald, căldura nu are unde să se ducă, temperatura centrală nu scade, iar creierul nu primește semnalul termic că e noapte. Gradul de vasodilatație al extremităților e un predictor al adormirii mai puternic decât nivelul de melatonină.</p>
<ul>
  <li>Corpul trebuie să-și scadă temperatura centrală cu 1-1.5 grade Celsius ca să inițieze somnul, iar o cameră prea caldă împiedică acest proces</li>
  <li>Termoregulatia nocturnă funcționează prin vasodilatație periferică: mâinile și picioarele disipă căldura, iar sânge cald din centrul corpului se răcește</li>
  <li>Temperatura optimă pentru dormitor e între 16 și 19 grade Celsius pentru majoritatea adulților, dar variabilitatea individuală e reală</li>
  <li>Un duș călduț cu 60-90 de minute înainte de culcare scade paradoxal temperatura centrală prin efectul de răcire rebound</li>
  <li>Materialele din care sunt făcute lenjeria și pijamaua contează mai mult decât temperatura setată pe termostat</li>
  <li>Transpirațiile nocturne au cauze multiple: temperatura camerei e doar una, iar hormonii, medicamentele și infecțiile sunt altele</li>
  <li>Partenerul de pat generează căldură echivalentă cu un radiator de 80-100 wați, ceea ce schimbă ecuația termică a patului</li>
  <li>Soluțiile nu necesită aer condiționat scump: ventilație, materiale naturale și câteva obiceiuri fac diferența cea mai mare</li>
</ul>
<p>Gândește-te la ultima noapte caldă de vară în care n-ai putut adormi. Te-ai întors dintr-o parte în alta, ai dat plapuma la o parte, ai pus-o înapoi, ai căutat cu piciorul zona rece a cearșafului. Disconfortul nu era doar subiectiv. Era fiziologic. Corpul tău încerca să facă ceva esențial pentru somn și nu reușea.</p>
<p>Termoregulatia e poate cel mai subestimat factor în calitatea somnului. E mai puțin discutat decât lumina albastră sau cofeina, dar efectul său e la fel de mare. Eus van Someren, cercetător la Netherlands Institute for Neuroscience și unul dintre cei mai productivi autori pe tema termoregulatiei și somnului, a publicat în 2021 în Current Opinion in Physiology un review în care argumentează că manipularea temperaturii corporale e una dintre cele mai eficiente și mai ieftine intervenții pentru îmbunătățirea somnului. Și datele îi dau dreptate.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Corpul uman nu menține o temperatură constantă de 37 grade Celsius. Temperatura centrală urmează un ritm circadian cu o amplitudine de circa 1-1.5 grade. Vârful e după-amiaza, pe la 17:00-18:00. Minimul e în a doua parte a nopții, pe la 4:00-5:00 dimineața. Adormitul coincide cu faza de scădere a acestei curbe. Nu e o coincidență. E o relație cauzală.</p>
<p>Ca să înțelegi mecanismul, gândește-te la corp ca la o clădire cu două zone: centrul (organele interne, creierul) și periferia (pielea, mâinile, picioarele). Când corpul vrea să-și scadă temperatura centrală, face un lucru contraintuitiv: încălzește periferia. Vasele de sânge din mâini și picioare se dilată, sânge cald din centrul corpului curge către extremități, iar căldura se disipă prin suprafața pielii în mediul înconjurător. E ca și cum ai deschide ferestrele unei case ca să lași căldura să iasă. Procesul se numește vasodilatație periferică distală.</p>
<p>Kräuchi și colaboratorii de la Universitatea din Basel au publicat în 1999 în Nature unul dintre cele mai citate studii pe această temă. Au demonstrat că gradul de vasodilatație al mâinilor și picioarelor (măsurat prin diferența de temperatură între piele și mediu) e cel mai bun predictor al latenței adormirii. Cu cât mâinile și picioarele se încălzesc mai repede, cu atât persoana adoarme mai repede. Relația era mai puternică decât oricare alt parametru măsurat, inclusiv nivelul de melatonină.</p>
<p>Aici intervine temperatura camerei. Dacă dormitorul e prea cald (peste 22-23 de grade), căldura corporală nu are unde să se ducă. Diferența de temperatură între piele și mediu e prea mică, disiparea e ineficientă și temperatura centrală nu scade suficient. Creierul nu primește semnalul termic de "e noapte." Adormitul se întârzie.</p>
<p>Dacă dormitorul e prea rece (sub 12-14 grade), un alt mecanism se activează: vasoconstricția periferică. Corpul închide vasele din extremități ca să conserve căldura centrală. Picioarele devin reci, disconfortul apare și adormitul e la fel de dificil, din motive opuse. Intervalul optim pentru majoritatea adulților e între 16 și 19 grade, cu 18 grade ca punct median citat cel mai frecvent în literatură.</p>
<p>Dar temperatura din cameră e doar jumătate din ecuație. Microclimatul patului contează enorm. Între corp, pijama, cearșaf și plapumă există o zonă cu temperatură și umiditate proprii. Temperatura optimă a acestui microclimat e de aproximativ 30-32 de grade Celsius (mult mai caldă decât camera, pentru că corpul încălzește spațiul imediat din jur). Umiditatea relativă optimă e între 40 și 60%. Dacă plapuma e prea groasă sau din materiale sintetice care nu respiră, microclimatul devine prea cald și prea umed, iar somnul se deteriorează chiar dacă camera are temperatura perfectă.</p>
<p>Un aspect pe care mulți îl ignoră: temperatura camerei nu afectează doar adormitul, ci și structura somnului. Haskell și colaboratorii au publicat în 1981 în Electroencephalography and Clinical Neurophysiology un studiu clasic care a arătat că temperaturile ambientale extreme reduc somnul REM și somnul profund și cresc trezirile nocturne. Somnul REM e deosebit de vulnerabil la temperatură, pentru că în această fază, termoregulatia corporală e parțial suspendată. Corpul nu mai transpiră și nu mai tremură în REM, ceea ce îl face dependent de temperatura mediului. Dacă camera e prea caldă, somnul REM e scurtat sau fragmentat.</p>
<p>Un detaliu care leagă termoregulatia de melatonină: melatonina însăși contribuie la scăderea temperaturii centrale. Acționează asupra hipotalamusului anterior, care coordonează termoregulatia, și facilitează vasodilatația periferică. Când secreția de melatonină e întârziată (de lumina albastră, de exemplu), scăderea temperaturii e și ea întârziată. Cele două sisteme lucrează în tandem, și perturbarea unuia îl afectează pe celălalt.</p>
<h2>Ce alimentează problema</h2>
<p>Încălzirea centrală modernă e principalul vinovat. În trecut, dormitoarele erau în mod natural mai reci noaptea. Astăzi, termostatele mențin 21-23 de grade constant, o temperatură confortabilă pentru starea de veghe dar prea caldă pentru somn. Mulți oameni nu au un termostat programabil sau nu știu că îl pot seta să coboare temperatura la 18 grade la ora culcării.</p>
<p>Plapumele sintetice și așternuturile din poliester sunt ieftine dar rău ventilate. Rețin căldura și umiditatea, creând un microclimat prea cald în care corpul se luptă să-și disipeze căldura. Efectul e amplificat de pijamalele din materiale sintetice.</p>
<p>Partenerul de pat adaugă o sursă de căldură pe care mulți nu o contabilizează. Un corp uman în repaus generează 80-100 de wați de căldură. Doi oameni într-un pat de 160 cm, sub aceeași plapumă, produc împreună cât un radiator electric mic. Temperatura microclimatului patului crește cu 2-3 grade față de somnul individual.</p>
<p>Alcoolul seara produce vasodilatație periferică inițială (senzația de căldură după un pahar de vin), care accelerează pierderea de căldură. Dar în a doua parte a nopții, metabolizarea alcoolului produce căldură metabolică, crește transpirația și fragmentează somnul prin dezechilibru termic.</p>
<p>Exercițiul intens seara ridică temperatura centrală cu 1-2 grade, iar revenirea la normal ia 2-3 ore. Un antrenament la 21:00 înseamnă că la 23:00 corpul e încă prea cald pentru a iniția somnul eficient.</p>
<p>Menopauza și bufeurile nocturne merită menționate separat. Fluctuațiile de estrogen destabilizează centrul de termoreglare din hipotalamus, producând episoade bruște de vasodilatație și transpirație urmate de frisoane. Aceste episoade pot trezi de 5-10 ori pe noapte și sunt responsabile pentru o parte importantă a insomniei perimenopuzale. Freedman și Roehrs au publicat în 2006 în Fertility and Sterility un studiu care a corelat direct bufeurile nocturne cu fragmentarea somnului măsurată prin polisomnografie.</p>
<p>Medicamentele care interferează cu termoregulatia: antidepresivele (mai ales SSRI și SNRI) pot produce transpirații nocturne la 10-20% din pacienți. Tamoxifenul (folosit în cancerul de sân) produce bufeuri similare celor din menopauză. Corticosteroizii cresc termogeneza. Paracetamolul și ibuprofenul scad temperatura (sunt antipiretice), dar efectul e relevant doar când există febră.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): temperatura camerei și obiceiuri de bază</h3>
<p>Setează temperatura dormitorului la 18 grade Celsius. Dacă ai termostat programabil, programează-l să coboare la 18 grade cu o oră înainte de culcare. Dacă nu ai termostat, deschide fereastra cu 30-60 de minute înainte de somn ca să răcorești camera. În nopțile calde de vară, un ventilator orientat spre fereastră (care împinge aerul cald afară) e mai eficient decât unul orientat spre pat (care mută doar aerul cald).</p>
<p>Un termometru ieftin pe noptieră e surprinzător de util. Mulți oameni supraestimează sau subestimează temperatura camerei. Datele concrete permit ajustări mai precise decât senzația subiectivă, care e influențată de oboseală, stres și hormoni.</p>
<p>Dușul călduț (nu fierbinte) cu 60-90 de minute înainte de culcare e una dintre cele mai bine documentate intervenții termice. Mecanismul: apa caldă dilată vasele periferice. După ce ieși din duș, căldura se disipă rapid prin vasele dilatate, iar temperatura centrală scade sub nivelul de dinainte de duș. E efectul de "răcire rebound" pe care Haghayegh și colaboratorii l-au confirmat într-o meta-analiză din 2019 publicată în Sleep Medicine Reviews, analizând 5.322 de participanți din 13 studii. Concluzia: un duș sau baie caldă cu 1-2 ore înainte de culcare reduce latența adormirii cu o medie de 10 minute.</p>
<p>Timing-ul contează: dușul luat chiar înainte de a te pune în pat nu dă timp vaselor să disipeze căldura. La 90 de minute, efectul de răcire e maxim. La 30 de minute, temperatura centrală poate fi încă crescută.</p>
<p>Șosete subțiri în pat par contraintuitive când vorbim de răcire, dar au un rol fiziologic precis. Încălzind picioarele, șosetele accelerează vasodilatația periferică și facilitează disiparea căldurii din centrul corpului. Kräuchi a confirmat asta în studiile sale de la Basel: picioarele calde accelerează adormitul nu pentru că oferă confort (deși fac și asta), ci pentru că deblochează mecanismul termic.</p>
<h3>Faza 2 (săptămânile 3-4): materiale și microclimat</h3>
<p>Plapuma merită evaluată în funcție de sezon și de temperatura camerei. Indicatorul util e "tog-ul" (unitate de rezistență termică). O plapumă de 4.5 tog e potrivită pentru camere la 18-20 de grade în sezonul rece. O plapumă de 7-10 tog într-o cameră la 20 de grade e prea multă. În nopțile calde, un cearșaf de bumbac sau o plapumă subțire de 2-3 tog e suficientă. Soluția ideală: două plapume de grosimi diferite pe care le alternezi în funcție de sezon, în loc de o singură plapumă "de compromis" care e prea groasă vara și prea subțire iarna.</p>
<p>Materialele naturale (bumbac, in, bambus, lână merinos) absorb și disipă umiditatea mult mai eficient decât poliesterul sau microfibra. Bumbacul absoarbe până la 25% din greutatea sa în umiditate înainte de a se simți umed. Poliesterul absoarbe sub 1%. Diferența practică: într-un cearșaf de bumbac, transpirația se evaporă. Într-un cearșaf de poliester, se acumulează pe piele și în microclimat, crescând disconfortul.</p>
<p>Lâna merinos are o proprietate termoregulatoare pe care puțini o cunosc: eliberează căldură când absoarbe umiditate și răcește când se usucă. Funcționează ca un regulator pasiv de temperatură. Pijamale sau cearșafuri din lână merinos fină (17-18 microni) nu produc mâncărime și sunt surprinzător de confortabile.</p>
<p>Salteaua contează și ea. Saltelele cu spumă memory rețin căldura mai mult decât cele cu arcuri sau latex. Dacă salteaua e din spumă memory și te trezești transpirat, un topper de latex perforat sau un protector de saltea din bumbac cu strat de răcire pot reduce retenția de căldură fără să înlocuiești salteaua.</p>
<p>Dacă dormiți doi în pat, plapume separate sunt o soluție pragmatică pe care multe culturi europene (Germania, țările scandinave) o practică de generații. Fiecare persoană își reglează propriul microclimat, fără compromisuri. E mai puțin romantic în teorie și mult mai funcțional în practică.</p>
<p>Mișcarea ușoară seara (plimbare de 15-20 de minute după cină) urmează o logică termică: efortul ușor ridică marginal temperatura centrală, iar răcirea ulterioară în aerul de seară mimează semnalul termic natural de adormire. Nu merge la sală. Nu transpiră. Doar mergi, afară dacă e posibil.</p>
<h3>Faza 3 (luna a doua și după): transpirații nocturne și cauze medicale</h3>
<p>Dacă transpirațiile nocturne persistă după optimizarea temperaturii camerei și a materialelor, cauza nu mai e ambientală. Lista de cauze medicale ale transpirațiilor nocturne e lungă și merită investigată sistematic.</p>
<p>Menopauza și perimenopauza: bufeurile nocturne afectează 75-85% din femei în această perioadă. Terapia hormonală de substituție (THS) e cea mai eficientă intervenție, reducând bufeurile cu 75-90%. Decizia de a începe THS implică o analiză individualizată a riscurilor și beneficiilor. Alternativele non-hormonale cu dovezi: venlafaxina în doze mici, gabapentina și, recent, fezolinetant (un antagonist de receptor de neurokinin B aprobat în 2023).</p>
<p>Hipertiroidismul crește termogeneza și produce transpirații nocturne, intoleranță la căldură și insomnie. TSH și T4 liber confirmă sau infirmă diagnosticul.</p>
<p>Infecțiile cronice (tuberculoza, endocardita, abcese) produc transpirații nocturne profuze, adesea însoțite de febră și pierdere ponderală. Limfoamele au transpirațiile nocturne ca simptom clasic (împreună cu febra și pierdere ponderală, triada cunoscută ca "simptome B"). Nu spun asta ca să creez anxietate. Spun ca să subliniez: transpirațiile nocturne persistente, neexplicate de temperatura camerei sau materiale, merită un set de analize de bază (hemoleucograma, VSH, proteina C reactivă, TSH).</p>
<p>Apneea de somn poate produce transpirații nocturne prin efortul respirator crescut. Dacă sforăi și transpiri, polisomnografia merită investigată.</p>
<p>Hipoglicemia nocturnă (descrisă detaliat în articolul despre glicemie) produce transpirații reci, cu puls rapid și anxietate. Dacă transpirațiile sunt însoțite de aceste simptome și apar în prima parte a nopții, glicemia e un suspect.</p>
<h2>Unde te lasă toate astea</h2>
<p>Dintre toate variabilele care afectează somnul, temperatura e una dintre cele mai ușor de controlat și mai ieftin de optimizat. Nu ai nevoie de echipament scump. Un termometru de cameră, o fereastră care se deschide, un duș cu 90 de minute înainte de culcare și materiale naturale în pat rezolvă o proporție surprinzător de mare din problemă.</p>
<p>Experimentează cu temperatura timp de o săptămână. Setează 18 grade (sau deschide fereastra) și notează cum dormi. Apoi încearcă 20 de grade. Apoi 16. Variabilitatea individuală e reală: unii dorm mai bine la 17, alții la 19. Datele tale personale valorează mai mult decât orice medie statistică.</p>
<p>Dacă după două săptămâni de temperatură optimizată și materiale potrivite transpirațiile nocturne persistă sau calitatea somnului nu se îmbunătățește, cauza e probabil în altă parte. Hormonii, medicamentele, apneea sau glicemia merită investigate. Temperatura camerei e o variabilă importantă, dar nu e singura. E un prim pas practic și accesibil, și pentru mulți e suficient ca să simtă o diferență.</p>
