<ul>
  <li>Inflamația cronică de grad scăzut nu produce simptome evidente. Nu doare, nu e roșie, nu se umflă. Dar perturbă mecanismele somnului profund în mod măsurabil.</li>
  <li>Citokinele proinflamatorii IL-6 și TNF-alfa, eliberate în inflamația cronică, fragmentează somnul și reduc proporția de somn cu unde lente (stadiul cel mai restaurativ).</li>
  <li>Sursele sunt adesea banale și trecute cu vederea: gingivita netratată, sinuzita cronică, intestin cu permeabilitate crescută, țesut adipos visceral, infecții dentare de grad scăzut.</li>
  <li>Țesutul adipos nu e inert. Adipocitele viscerale produc activ citokine inflamatorii, iar persoanele cu circumferință abdominală crescută au niveluri de IL-6 proporțional mai ridicate.</li>
  <li>Markerii sangvini CRP (proteina C reactivă) și VSH (viteza de sedimentare a hematiilor) pot detecta inflamația sistemică, dar valorile "normal înalte" sunt adesea ignorate.</li>
  <li>Relația e bidirecțională: somnul prost crește inflamația, iar inflamația înrăutățește somnul, creând un cerc vicios documentat în mai multe studii longitudinale.</li>
  <li>Dieta antiinflamatorie nu e un concept vag. Are componente concrete: omega-3, polifenoli, fibre, reducerea zaharurilor rafinate și a uleiurilor vegetale procesate.</li>
  <li>Intervenția cere identificarea sursei inflamatorii și abordarea ei, nu doar suprimarea markerilor cu suplimente.</li>
</ul>
<p>Când vorbim despre inflamație, imaginea imediată e de obicei ceva vizibil: o articulație umflată, o rană infectată, un gât roșu în angină. Aceste forme de inflamație acută sunt puternice, localizate și temporare. Sistemul imunitar se mobilizează, rezolvă problema și se retrage. Dar există o formă diferită de inflamație care nu se manifestă prin simptome pe care să le observi la suprafață. E de intensitate scăzută, distribuită sistemic și, crucial, cronică. Poate persista ani de zile fără să producă nimic pe care să îl identifici ca inflamație.</p>
<p>Această inflamație de grad scăzut a fost legată în ultimele două decenii de o listă lungă de probleme: boli cardiovasculare, diabet de tip 2, depresie, declin cognitiv. Dar una dintre consecințele cele mai directe și mai puțin discutate e efectul asupra somnului. Citokinele inflamatorii nu doar că circulă prin sânge. Interacționează direct cu neuronii și glia din regiunile cerebrale care reglează somnul, modificând arhitectura nopții în moduri pe care nu le simți ca inflamație, ci ca oboseală matinală, treziri frecvente și senzația că somnul nu te repară.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Ca să înțelegi cum inflamația ajunge să afecteze somnul, merită să vezi mai întâi ce sunt citokinele și cum acționează ele la nivelul creierului.</p>
<p>Citokinele sunt proteine mici de semnalizare eliberate de celulele imunitare (și nu numai) ca răspuns la stimuli inflamatori. În inflamația cronică de grad scăzut, cele mai relevante sunt interleukina-6 (IL-6), factorul de necroză tumorală alfa (TNF-alfa) și interleukina-1 beta (IL-1beta). Aceste molecule circulă în sânge și pot traversa bariera hemato-encefalică prin mecanisme specifice de transport sau prin zone ale barierei care sunt natural mai permeabile (organele circumventriculare).</p>
<p>Odată în creier, citokinele interacționează cu neuronii din hipotalamusul anterior și cu celulele gliale din cortexul prefrontal și talamusul, regiuni care coordonează ciclurile de somn. Krueger și colaboratorii au publicat în 2011 în Physiological Reviews o analiză extinsă a mecanismelor prin care citokinele modifică somnul. Concluzia centrală: IL-1beta și TNF-alfa, în concentrații mici, promovează somnul non-REM (funcționează ca semnale de "ai nevoie de odihnă pentru reparație"). Dar în concentrații cronice, moderate, efectul se inversează parțial: somnul devine fragmentat, fazele de somn profund se scurtează, iar trezirile se înmulțesc.</p>
<p>Veldhuijzen van Zanten și colaboratorii au publicat în 2020 în Brain, Behavior, and Immunity un studiu care a măsurat citokinele la pacienți cu artrită reumatoidă și a corelat nivelurile cu datele polisomnografice. Pacienții cu IL-6 și TNF-alfa mai ridicate aveau proporții reduse de somn cu unde lente (N3), mai multe treziri scurte pe parcursul nopții și eficiență scăzută a somnului, deși timpul total petrecut în pat era similar cu cel al grupului de control. Somnul era prezent ca durată, dar alterat ca structură.</p>
<p>Relația e bidirecțională, și asta e partea care creează cercul vicios. Irwin și colaboratorii au publicat în 2016 în Biological Psychiatry o meta-analiză pe 72 de studii care a arătat că privarea de somn, chiar și parțială (o noapte cu 4 ore de somn), crește IL-6 cu aproximativ 60% și CRP cu 80% a doua zi. Somnul fragmentat cronic produce o creștere susținută a markerilor inflamatori, care la rândul lor fragmentează și mai mult somnul. Ciclul se auto-întreține și se amplifică treptat.</p>
<p>Un aspect pe care mulți îl trec cu vederea: inflamația cronică nu afectează doar adormitul sau trezirile. Afectează ceea ce creierul face în timpul somnului. Somnul profund (N3) e faza în care se eliberează hormonul de creștere, în care se face curățarea deșeurilor metabolice prin sistemul glimfatic și în care se consolidează memoria procedurală. Când această fază e scurtată sau fragmentată, te trezești după 7-8 ore de somn și simți că nu ai dormit suficient. Informația e că ai dormit, dar calitatea internă a fost compromisă.</p>
<h2>Ce alimentează problema</h2>
<p>Sursele inflamației cronice sunt adesea surprinzător de banale. Gingivita, cea mai frecventă boală orală la adulți, menține o sursă constantă de bacterii și citokine la poarta de intrare în organism. Lockhart și colaboratorii au publicat în 2012 în Circulation o declarație științifică a American Heart Association care a documentat legătura între boala parodontală și inflamația sistemică. Sângerarea la periaj nu e un inconvenient minor. E un semnal că sistemul imunitar luptă constant cu o infecție locală care produce efecte la distanță.</p>
<p>Sinuzita cronică, prezentă la 10-15% din populația adultă conform datelor epidemiologice, menține un focar inflamator în sinusurile paranazale care eliberează citokine în circulația sangvină. Mulți oameni cu sinuzită cronică nu au simptome dramatice, doar o congestie ușoară, scurgere postnazală intermitentă și, fără să facă legătura, somn neodihnitor.</p>
<p>Permeabilitatea intestinală crescută ("leaky gut") permite trecerea lipopolizaharidelor (LPS) bacteriene din lumenul intestinal în sânge. LPS e unul dintre cei mai puternici activatori ai sistemului imunitar înnăscut. Chiar și cantități mici care ajung în circulație produc un răspuns inflamator sistemic. Factorii care cresc permeabilitatea intestinală sunt multipli: dieta săracă în fibre, stres cronic, alcool, antiinflamatorii nesteroidiene (ibuprofen, aspirină) luate frecvent, și disbioza intestinală.</p>
<p>Țesutul adipos visceral e o sursă de inflamație pe care mulți nu o asociază cu somnul. Adipocitele viscerale (cele din jurul organelor abdominale) nu sunt doar depozite de energie. Sunt celule endocrine active care produc IL-6, TNF-alfa și leptină în cantități proporționale cu volumul lor. Fontana și colaboratorii au publicat în 2007 în Proceedings of the National Academy of Sciences un studiu care a arătat că țesutul adipos visceral produce de trei ori mai multă IL-6 decât țesutul adipos subcutanat. Circumferința abdominală e un indicator mai bun al inflamației sistemice decât greutatea totală.</p>
<p>Zahărul rafinat și uleiurile vegetale rafinate (ulei de floarea soarelui, ulei de soia, ulei de porumb) contribuie la inflamație prin mecanisme diferite. Zahărul crește glicemia brusc, iar hiperglicemia postprandială activează NF-kB, un factor de transcripție care pornește producția de citokine. Uleiurile vegetale bogate în omega-6 furnizează acid arahidonic, precursorul prostaglandinelor proinflamatorii. Nu omega-6 în sine e problema, ci raportul omega-6/omega-3, care în dieta modernă ajunge la 15-20:1, față de raportul evolutiv de 2-4:1.</p>
<p>Sedentarismul reduce producția de miokine antiinflamatorii de către musculatura scheletică. Activitatea fizică produce IL-10 și IL-1ra (antagonist al receptorului IL-1), molecule care contracarează inflamația. În absența mișcării regulate, acest efect antiinflamator lipsește.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-3): identificare și eliminarea surselor evidente</h3>
<p>Vizita la dentist pentru evaluarea sănătății gingivale e un prim pas concret. Dacă există sângerare la periaj, pungi parodontale sau tartru subgingival, tratamentul parodontal profesional urmat de igienă orală riguroasă (periaj de două ori pe zi plus ață dentară zilnic) reduce o sursă directă de inflamație. Efectul pe markerii sangvini devine măsurabil după 4-6 săptămâni.</p>
<p>Evaluarea sinusurilor prin consultație ORL, dacă există congestie nazală cronică, respirație predominant orală sau senzație de presiune facială, identifică sau exclude o altă sursă frecventă.</p>
<p>Modificarea dietei: reducerea zahărului rafinat și a alimentelor ultraprocesate la maximum 10% din calorii, creșterea consumului de legume și fructe colorate (care conțin polifenoli antiinflamatori) și înlocuirea uleiurilor vegetale rafinate cu ulei de măsline extravirgin, unt sau ulei de cocos. Aceste schimbări nu necesită diete extreme. Sunt ajustări ale proporțiilor, nu eliminări totale.</p>
<p>Activitatea fizică moderată (30-40 de minute de mers alert, înot sau ciclism, de 4-5 ori pe săptămână) produce efecte antiinflamatorii măsurabile. Un studiu publicat de Gleeson și colaboratorii în 2011 în Nature Reviews Immunology a arătat că exercițiul regulat reduce CRP cu 20-30% pe parcursul a 12-16 săptămâni, independent de pierderea în greutate.</p>
<p>Analiza sangvină de bază: CRP cu sensibilitate ridicată (hs-CRP), VSH, hemoleucograma completă. hs-CRP sub 1 mg/L e considerat risc inflamator scăzut. Între 1 și 3 mg/L e un semnal de atenție. Peste 3 mg/L indică inflamație sistemică activă care merită investigată. Mulți medici tratează valori de 2-2.5 mg/L ca normale, dar cercetarea recentă sugerează că optimalul e sub 1.</p>
<h3>Faza 2 (săptămânile 4-8): dieta antiinflamatorie structurată</h3>
<p>Omega-3 din surse alimentare e intervenția nutrițională cu cele mai solide date antiinflamatorii. Peștele gras (somon, macrou, sardine, hering) de 2-3 ori pe săptămână furnizează EPA și DHA, acizii grași care concurează direct cu acidul arahidonic și reduc producția de prostaglandine inflamatorii. Nuci, semințe de in și semințe de chia oferă ALA, un omega-3 vegetal cu rată de conversie limitată în EPA/DHA (5-10%), dar util ca sursă complementară.</p>
<p>Polifenolii din fructe de pădure (afine, zmeură, mure), ceai verde, cacao neîndulcită și ulei de măsline extravirgin reduc NF-kB și producția de citokine. Un studiu publicat de Karlsen și colaboratorii în 2007 în Journal of Nutrition a arătat că consumul zilnic de afine pe parcursul a 4 săptămâni a redus NF-kB și mai mulți markeri inflamatori la adulți cu risc cardiovascular crescut.</p>
<p>Fibrele fermentabile (inulină, pectină, beta-glucani) hrănesc bacteriile producătoare de butirat, care la rândul lui reduce inflamația intestinală și sistemică. Leguminoasele, ovăzul, merele și usturoiul sunt surse practice.</p>
<p>Curcuma (condimentul) conține curcumină, un polifenol cu proprietăți antiinflamatorii documentate, dar biodisponibilitatea din condimentul simplu e foarte scăzută. Combinația cu piperină (piper negru) crește absorbția de aproximativ 20 de ori. Adăugarea curcumei cu piper negru în mâncare e o intervenție alimentară simplă, deși doza de curcumină obținută e modestă comparativ cu suplimentele.</p>
<p>Alcoolul, chiar și în cantități considerate moderate (1-2 unități pe zi), crește permeabilitatea intestinală și nivelurile de LPS circulant. Reducerea sau eliminarea alcoolului, în special în perioadele de somn problematic, e o intervenție antiinflamatorie directă.</p>
<h3>Faza 3 (luna a treia și după): suplimente și investigații țintite</h3>
<p>Dacă dieta și stilul de viață nu normalizează markerii inflamatori după 8-12 săptămâni, suplimentele țintite pot fi adăugate.</p>
<p>Omega-3 concentrat din ulei de pește (2-3 grame de EPA+DHA pe zi) e suplimentul antiinflamator cu cele mai multe date clinice. EPA pare să aibă un efect antiinflamator mai puternic decât DHA, iar suplimentele cu raport EPA:DHA de 2:1 sau mai mare sunt preferate în context inflamator.</p>
<p>Curcumina fitosomală sau cu piperină (500-1000 mg pe zi) a arătat în mai multe studii randomizate reduceri ale CRP și IL-6 comparabile cu antiinflamatoarele nesteroidiene la doze mici. Hewlings și Kalman au publicat în 2017 în Foods o meta-analiză care a confirmat efectul antiinflamator al curcuminei suplimentare.</p>
<p>Vitamina D merită verificată și corectată dacă e scăzută. Nivele sub 30 ng/mL sunt asociate cu inflamație crescută, iar suplimentarea până la nivele de 40-60 ng/mL a arătat reduceri ale CRP în mai multe studii observaționale.</p>
<p>Dacă hs-CRP rămâne persistent peste 3 mg/L după intervenții consistente de stil de viață, investigarea cauzelor specifice devine prioritară. Testarea pentru infecții cronice (Helicobacter pylori, parazitoze intestinale), evaluarea permeabilității intestinale (zonulină serică, deși testul are limitări), screeningul pentru boli autoimune subclinice (anticorpi antinucleari, anticorpi anti-tiroidieni) pot identifica sursa specifică.</p>
<p>Pierderea în greutate, dacă există exces de țesut adipos visceral, e probabil cea mai eficientă intervenție antiinflamatorie pe termen lung. Reducerea cu 5-10% din greutate produce scăderi măsurabile ale IL-6, TNF-alfa și CRP. Nu e nevoie să ajungi la greutatea ideală. Primele kilograme pierdute din zona abdominală au impactul cel mai mare.</p>
<h2>Unde te lasă toate astea</h2>
<p>Inflamația cronică de grad scăzut e o cauză a somnului de proastă calitate care trece nedetectată tocmai pentru că nu produce simptome specifice. Nu te doare nimic, nu ai febră, nu ai nimic vizibil. Dar creierul tău operează într-un mediu biochimic alterat, în care citokinele interferează cu mecanismele somnului profund noapte de noapte.</p>
<p>Vestea încurajatoare e că inflamația de grad scăzut răspunde la intervenții de stil de viață. Nu e o condiție ireversibilă. Dieta, mișcarea, somnul însuși (atunci când e protejat și îmbunătățit prin alte intervenții), igiena orală și reducerea expunerii la factori inflamatori produc schimbări reale în markerii sangvini pe parcursul săptămânilor și lunilor.</p>
<p>Dacă ai încercat să îți îmbunătățești somnul prin igiena somnului clasică (camera întunecată, ora fixă de culcare, fără ecrane seara) și rezultatele au fost limitate, inflamația merită verificată. O analiză de hs-CRP costă puțin și oferă un număr concret. Dacă numărul e ridicat, ai o direcție de investigat. Dacă e scăzut, ai eliminat o posibilitate și poți continua căutarea în altă parte.</p>
