<p>O glandă de 20 de grame de la baza gâtului reglează temperatura, neurotransmițătorii și arhitectura somnului tău. Dacă igiena somnului nu a funcționat și analizele par „normale", merită să te uiți mai atent la ce face tiroida, și mai ales la ce nu măsoară un TSH luat singur.</p>
<ul>
  <li>Tiroida reglează rata metabolică a fiecărei celule din corp, inclusiv neuronii responsabili de ciclul somn-veghe</li>
  <li>Hipotiroidismul produce un paradox: oboseala cronică dar somn superficial, cu mai puțin somn profund și treziri frecvente</li>
  <li>Hipertiroidismul accelerează tot ce ține de metabolism, inclusiv pulsul și temperatura, făcând adormitul și menținerea somnului extrem de dificile</li>
  <li>Hormonii tiroidieni T3 și T4 influențează direct producția de serotonină și conversia ei în melatonină</li>
  <li>Temperatura corpului, reglată parțial de tiroidă, trebuie să scadă cu 1-1.5 grade Celsius pentru inițierea somnului, iar disfuncțiile tiroidiene perturbă exact acest mecanism</li>
  <li>Testarea doar a TSH-ului ratează frecvent Hashimoto și hipotiroidismul subclinic; un panel complet include T3 liber, T4 liber, anticorpi anti-TPO și anti-tiroglobulină</li>
  <li>Tiroidita Hashimoto afectează estimativ 5-10% din populație și produce fluctuații imprevizibile între simptome hipo și hiper, inclusiv în calitatea somnului</li>
  <li>Optimizarea funcției tiroidiene poate rezolva probleme de somn care nu au răspuns la nicio altă intervenție</li>
</ul>
<p>Dacă ai încercat tot ce știi despre igiena somnului și nimic nu a funcționat cu adevărat, există o posibilitate pe care puțini oameni o iau în calcul înainte să fi epuizat alte opțiuni: că problema nu e în creier, nu e în obiceiuri și nu e în stres, ci într-o glandă de 20 de grame situată la baza gâtului. Tiroida.</p>
<p>Nu e o cauză exotică și nu e rară. Disfuncțiile tiroidiene afectează între 5 și 15% din populația adultă, cu o prevalență mult mai mare la femei și cu vârful după 40 de ani. Ce le face relevante pentru somn e că tiroida nu reglează un singur lucru. Reglează viteza la care funcționează practic tot. Iar "tot" include mecanismele care te adorm și cele care te țin adormit.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Tiroida produce doi hormoni principali: tiroxina (T4) și triiodotironina (T3). T4 e forma de depozitare, produsă în cantități mari dar relativ inactivă. T3 e forma activă, de aproximativ patru ori mai potentă, și rezultă în mare parte din conversia periferică a T4 în diverse țesuturi. Hipofiza, din creier, controlează tiroida prin TSH (hormonul tireostimulant): când nivelurile de T3 și T4 scad, TSH crește ca să stimuleze tiroida să producă mai mult. Când nivelurile sunt suficiente, TSH scade.</p>
<p>Acest sistem de feedback influențează somnul prin trei mecanisme distincte care merită înțelese separat.</p>
<p>Primul mecanism: temperatura corpului. Pentru ca adormitul să se întâmple normal, temperatura centrală trebuie să scadă cu aproximativ 1-1.5 grade Celsius. Această scădere e orchestrată de ritmul circadian și e unul dintre cele mai puternice semnale de somn pe care le avem. Hipotiroidismul reduce rata metabolică și scade temperatura bazală, dar în mod paradoxal face și mecanismul de termoreglare mai rigid. Corpul e deja rece și nu mai reușește să facă scăderea suplimentară necesară pentru somn. Gilbert Bhassali și colegii au documentat în 2017 în Thyroid Research că pacienții hipotiroidieni au o amplitudine circadiană redusă a temperaturii, adică diferența dintre temperatura din timpul zilei și cea din timpul nopții e mai mică. Acest "platou termic" e asociat cu somn superficial și treziri repetate.</p>
<p>În hipertiroidism, situația e inversă dar la fel de problematică. Rata metabolică e accelerată. Temperatura corporală e crescută. Pulsul e ridicat, frecvent peste 80-90 de bătăi pe minut chiar și în repaus. Corpul funcționează ca și cum ar fi permanent într-o stare de efort moderat. Scăderea de temperatură necesară pentru adormire devine mult mai dificilă. Insomnia de inițiere, dificultatea de a adormi, e unul dintre cele mai frecvente simptome ale hipertiroidismului, raportat de 60-80% din pacienții cu boala Graves, conform unui studiu din 2019 publicat în Journal of Clinical Endocrinology &amp; Metabolism de Baser și colegii.</p>
<p>Al doilea mecanism: neurotransmițătorii. T3 influențează direct sinteza de serotonină în nucleii raphe ai trunchiului cerebral. Serotonina e precursor al melatoninei, hormonul care semnalează creierului că e timpul să doarmă. În hipotiroidism, conversia triptofan-serotonină-melatonină e încetinită. Rezultatul: nivele mai scăzute de melatonină seara și un semnal de somn mai slab. Un studiu din 2012 publicat în Neuroendocrinology Letters de Bahammam și colegii a găsit că pacienții hipotiroidieni au niveluri seric de melatonină cu 30-40% mai mici decât controalele sănătoase, chiar și după controlarea pentru vârstă și expunerea la lumină.</p>
<p>În hipertiroidism, excesul de T3 crește noradrenalina și activează sistemul nervos simpatic. Asta produce starea pe care mulți o descriu ca "obosit dar cu creierul care nu se oprește." Gânduri rapide, anxietate, puls perceptibil în piept sau în urechi când stai în pat. Nu e "stres." E o activare fiziologică reală, condusă de exces hormonal.</p>
<p>Al treilea mecanism: arhitectura somnului. Studii polisomnografice au arătat că hipotiroidismul reduce proporția de somn profund (N3) și crește numărul de micro-treziri. Un studiu condus de Lancel și Steiger, publicat în 2000 în Journal of Endocrinology, a demonstrat pe modele animale că nivelurile de hormoni tiroidieni influențează direct EEG-ul din timpul somnului: hipotiroidismul suprimă undele delta (somnul profund), iar restaurarea nivelurilor normale de T3 normalizează patternul. La oameni, datele clinice confirmă aceeași direcție. Pacienții hipotiroidieni raportează constant că dorm mult dar se trezesc obosiți, ceea ce e consistent cu un somn lung dar superficial.</p>
<p>Aici apare și Hashimoto, care merită atenție specială. Tiroidita Hashimoto e o boală autoimună în care sistemul imunitar atacă treptat țesutul tiroidian. E cea mai frecventă cauză de hipotiroidism în țările dezvoltate. Ceea ce o face complicată pentru somn e că în stadiile incipiente produce fluctuații. Țesutul tiroidian distrus eliberează periodic cantități mari de hormoni stocați în glandă, producând episoade tranzitorii de hipertiroidism (hashitoxicoză) urmate de perioade de hipotiroidism pe măsură ce țesutul funcțional scade. Un pacient cu Hashimoto poate avea săptămâni de insomnie cu anxietate urmate de săptămâni de hipersomnie cu oboseală profundă, fără să înțeleagă de ce.</p>
<h2>Ce alimentează problema</h2>
<p>Primul și cel mai mare factor e subdiagnosticarea. În practica medicală standard, evaluarea tiroidiană înseamnă frecvent doar TSH. Dacă TSH e în intervalul de referință (de obicei 0.4-4.5 mIU/L), se consideră că tiroida e normală. Problema e că intervalul de referință e foarte larg și nu reflectă neapărat funcționarea optimă. Un TSH de 3.5 e "normal" pe hârtie, dar poate fi asociat cu simptome de hipotiroidism subclinic la unele persoane.</p>
<p>Hipotiroidismul subclinic, definit ca TSH ușor crescut cu T4 liber normal, afectează 4-10% din populația adultă. Nu apare întotdeauna pe analizele de rutină. Un studiu din 2007 publicat în Archives of Internal Medicine de Biondi și Cooper a argumentat că hipotiroidismul subclinic poate produce simptome reale, inclusiv tulburări de somn, oboseală și dificultăți cognitive, chiar dacă nu atinge pragul clasic de diagnostic.</p>
<p>Și mai important: anticorpii anti-TPO și anti-tiroglobulină pot fi crescuți cu ani înainte ca TSH-ul să se modifice. O persoană cu Hashimoto incipient poate avea TSH perfect normal și anticorpi de zece ori peste limită. Dacă nimeni nu măsoară anticorpii, diagnosticul vine cu 5-10 ani întârziere.</p>
<p>Al doilea factor: inflamația cronică. Stresul, lipsa somnului, dieta procesată și infecțiile cronice cresc citokinele inflamatorii (IL-6, TNF-alfa) care interferează cu conversia T4 în T3. Rezultatul e o situație în care tiroida produce T4 adecvat, TSH-ul arată normal, dar T3-ul la nivel celular e insuficient. Se numește "sindrom de T3 scăzut" sau "sindrom de boală non-tiroidiană" și nu apare pe analizele standard care măsoară doar TSH.</p>
<p>Al treilea factor: deficiențele nutriționale. Tiroida are nevoie de iod, seleniu, zinc și fier pentru a funcționa corect. Seleniul în particular e esențial pentru enzimele deiodinaze care convertesc T4 în T3. Un deficit de seleniu nu afectează neapărat TSH-ul, dar poate reduce conversia periferică și produce simptome hipotiroidiene cu analize aparent normale.</p>
<p>Stresul cronic merită menționat separat. Cortizolul crescut inhibă conversia T4 în T3 și crește conversia în rT3 (reverse T3), o formă inactivă. Asta înseamnă că o persoană sub stres cronic poate avea o tiroidă care funcționează normal dar hormoni tiroidieni activi insuficienți la nivel celular. Iar stresul însuși e agravat de somnul prost, creând un cerc vicios.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): investigare</h3>
<p>Solicită un panel tiroidian complet, nu doar TSH. Un profil util include: TSH, T4 liber, T3 liber, rT3 (reverse T3), anticorpi anti-TPO și anticorpi anti-tiroglobulină. Dacă medicul de familie nu e deschis la asta, un endocrinolog sau un medic de medicină funcțională va fi mai receptiv.</p>
<p>Intervalele optime (nu doar "normale") sunt orientativ: TSH între 1.0 și 2.5 mIU/L, T4 liber în jumătatea superioară a intervalului de referință, T3 liber în jumătatea superioară a intervalului de referință, anticorpi anti-TPO sub 35 IU/mL. Acestea sunt direcții, nu reguli absolute, și interpretarea corectă necesită un medic care înțelege nuanțele.</p>
<p>În paralel cu investigarea, ține un jurnal de simptome. Temperatura corporală bazală măsurată imediat după trezire (înainte de a te ridica din pat) poate fi un indicator util. O temperatură constant sub 36.3 grade Celsius sugerează metabolismul încetinit. Notează calitatea somnului, nivelul de energie pe parcursul zilei, toleranța la frig, starea părului și a pielii. Aceste date îl ajută pe medic să coreleze analizele cu tabloul clinic.</p>
<h3>Faza 2 (săptămânile 3-6): fundamente comportamentale</h3>
<p>Independent de rezultatele analizelor, anumite intervenții susțin funcția tiroidiană și calitatea somnului simultan.</p>
<p>Expunerea la lumină naturală dimineața (15-30 de minute în prima oră după trezire) sincronizează ritmul circadian și susține axa hipotalamo-hipofizo-tiroidiană. Nu e specific pentru tiroidă, dar întărește exact sistemele care sunt vulnerabile în disfuncțiile tiroidiene.</p>
<p>Gestionarea temperaturii seara devine critică dacă tiroida e în discuție. Un duș cald cu 60-90 de minute înainte de culcare produce un efect paradoxal: încălzirea periferică accelerează pierderea de căldură prin vasodilatația pielii, iar temperatura centrală scade mai rapid decât ar face-o natural. Acest truc e util pentru oricine, dar devine deosebit de valoros când termoreglarea e compromisă de disfuncție tiroidiană.</p>
<p>Mișcarea fizică regulată susține conversia T4 în T3. Nu e nevoie de exerciții intense. Plimbările de 30-40 de minute, înotul sau yoga sunt suficiente. Exercițiul intens poate fi contraproductiv în hipotiroidism prin creșterea cortizolului și a rT3. Dacă ești diagnosticat cu hipotiroidism și te simți mai rău după antrenamente intense, asta poate fi motivul.</p>
<p>Reducerea alimentelor inflamatorii (zahăr rafinat, uleiuri vegetale procesate, alcool) scade citokinele care interferează cu conversia T3. Nu e o dietă specială, ci o reducere a factorilor care agravează un sistem deja vulnerabil.</p>
<p>Pentru Hashimoto în particular, eliminarea glutenului timp de 6-8 săptămâni merită testată. Există date care arată o reactivitate încrucișată între anticorpii anti-gliadină și țesutul tiroidian. Un studiu din 2018 de Liontiris și Mazokopakis publicat în Endocrine, Metabolic &amp; Immune Disorders Drug Targets a găsit că dieta fără gluten a redus anticorpii anti-TPO la pacienții cu Hashimoto care nu aveau boală celiacă. Nu funcționează pentru toată lumea, dar raportul risc-beneficiu e favorabil: riscul e zero, beneficiul potențial e real.</p>
<h3>Faza 3 (luna a doua): suplimente țintite</h3>
<p>Seleniu (200 mcg/zi, preferabil selenometionină) e cel mai bine studiat supliment pentru Hashimoto. O meta-analiză din 2010 publicată în Thyroid de Toulis și colegii a arătat reducerea anticorpilor anti-TPO cu 20-40% după 3-6 luni de suplimentare. Seleniul susține și enzimele antioxidante din țesutul tiroidian și enzimele de conversie T4 în T3.</p>
<p>Zinc (15-30 mg/zi) susține conversia T4 în T3 și funcționarea receptorilor tiroidieni. Ia-l cu mâncare pentru a evita greața și combină-l cu cupru (1-2 mg) dacă suplimentezi pe termen lung, pentru a preveni dezechilibrul mineral.</p>
<p>Vitamina D, dacă nivelurile sunt sub 40 ng/mL, merită corectată. Există o asociere puternică între deficitul de vitamina D și bolile autoimune tiroidiene. Nu e demonstrat că suplimentarea previne Hashimoto, dar nivelurile adecvate susțin funcția imună și pot modula răspunsul autoimun.</p>
<p>Ashwagandha (300-600 mg extract standardizat) a arătat în câteva studii mici că poate îmbunătăți TSH și T4 în hipotiroidismul subclinic. Un studiu randomizat din 2018 de Sharma și colegii publicat în Journal of Alternative and Complementary Medicine a găsit îmbunătățiri la pacienții cu hipotiroidism subclinic după 8 săptămâni. Nu e un înlocuitor pentru medicația tiroidiană, dar poate fi util ca suport.</p>
<p>Dacă ești deja pe tratament cu levotiroxină și somnul rămâne o problemă, discută cu medicul despre adăugarea de T3 (Cytomel sau compounded T3) sau trecerea pe extract tiroidian natural (Armour Thyroid, NP Thyroid). Unii pacienți convertesc slab T4 în T3 și nu răspund optim la monoterapia cu levotiroxină. Studiile lui Hoang și colegii din 2009 în Journal of Clinical Endocrinology &amp; Metabolism au arătat că un subgrup de pacienți cu o variantă genetică specifică a deiodinazei tip 2 (polimorfismul Thr92Ala) răspund mai bine la terapia combinată T4+T3.</p>
<h2>Unde te lasă toate astea</h2>
<p>Tiroida nu e prima cauză la care te gândești când somnul nu funcționează. Și probabil nu ar trebui să fie. Igiena somnului, stresul, lumina și alimentația acoperă cele mai frecvente probleme. Dar dacă ai parcurs acele etape și somnul rămâne nerezonabil de prost față de efortul depus, un panel tiroidian complet poate fi piesa lipsă.</p>
<p>Nu trebuie să te diagnostichezi singur pe baza simptomelor. Hipotiroidismul și depresia se suprapun masiv simptomatologic. Hipertiroidismul și anxietatea la fel. Ai nevoie de analize. Dar ai nevoie de analizele corecte, interpretate în context clinic, nu doar bifate ca "în intervalul normal."</p>
<p>Dacă rezultatele ies altfel decât te așteptai, știi măcar în ce direcție să mergi. Iar dacă tiroida e normală cu adevărat, ai eliminat o cauză importantă și poți continua să cauți în altă parte fără să te întrebi "dar dacă era tiroida?" la fiecare noapte proastă.</p>
