<ul>
  <li>Receptorii de vitamina D există în zonele cerebrale care controlează somnul, inclusiv hipotalamusul și trunchiul cerebral, ceea ce sugerează un rol direct, nu doar indirect</li>
  <li>Deficitul de vitamina D afectează estimativ 40-60% din populația urbană din Europa, cu procente și mai mari în țările nordice și în lunile de iarnă</li>
  <li>Vitamina D influențează conversia triptofanului în serotonină, iar serotonina e precursorul melatoninei, hormonul care inițiază somnul</li>
  <li>Deficitul cronic de vitamina D crește markerii inflamatori (IL-6, TNF-alfa, CRP) care perturbă arhitectura somnului și reduc somnul profund</li>
  <li>Nivelurile considerate "normale" (30 ng/mL) pot fi insuficiente pentru funcționare optimă; cercetarea sugerează că 50-80 ng/mL e intervalul în care beneficiile sunt cele mai consistente</li>
  <li>Suplimentarea cu vitamina D fără vitamina K2 poate produce calcifiere vasculară pe termen lung, pentru că D crește absorbția calciului iar K2 îl direcționează spre oase în loc de artere</li>
  <li>Timing-ul suplimentării contează: dimineața, nu seara, pentru că vitamina D poate suprima melatonina dacă e luată în orele de dinainte de culcare</li>
  <li>Corectarea deficitului ia 2-3 luni la doze standard, iar efectele asupra somnului apar treptat, nu brusc</li>
</ul>
<p>Există un paradox care merită observat. Vitamina D e numită "vitamina soarelui" și o produci când ești afară, în lumină. Somnul se întâmplă noaptea, în întuneric. Și totuși, una dintre cele mai consistente corelații din cercetarea somnului e că oamenii cu niveluri scăzute de vitamina D dorm mai prost. Nu doar mai puțin, ci cu o arhitectură mai fragmentată, cu mai puțin somn profund și cu mai multă somnolență diurnă.</p>
<p>La prima vedere, pare să nu aibă logică. Dar dacă te uiți la mecanismele de legătură, conexiunea devine clară. Vitamina D nu e doar o vitamină. E un precursor hormonal care influențează expresia a peste 200 de gene, inclusiv gene implicate în producția de neurotransmițători, în reglarea inflamației și în funcționarea ritmului circadian. Iar deficitul ei e atât de răspândit încât a devenit aproape normalul statistic în populația urbană modernă.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Primul lucru de înțeles e că vitamina D funcționează mai mult ca un hormon decât ca o vitamină clasică. Forma activă, calcitriolul (1,25-dihidroxi vitamina D), se leagă de receptorii nucleari VDR și modifică expresia genică la nivel celular. Receptorii VDR au fost identificați în neuronii din hipotalamus, trunchiul cerebral și cortexul prefrontal, zone direct implicate în reglarea somnului și a ritmului circadian. Patrick și Ames, publicând în 2014 în FASEB Journal, au propus un model în care vitamina D reglează enzimele triptofan hidroxilază 1 și 2, responsabile de conversia triptofanului în serotonină. În creier, serotonina e produsă prin TPH2 (activată de vitamina D) și servește ca precursor pentru melatonină prin N-acetilare și metilare în glanda pineală.</p>
<p>Cu alte cuvinte: dacă nu ai suficientă vitamina D, produci mai puțină serotonină. Dacă produci mai puțină serotonină, ai mai puțin substrat pentru melatonină. Iar dacă melatonina e insuficientă, semnalul de somn e mai slab. Nu e singurul mecanism, dar e cel mai direct.</p>
<p>Al doilea mecanism trece prin inflamație. Deficitul de vitamina D e asociat cu niveluri crescute de citokine proinflamatorii: interleukina 6 (IL-6), factorul de necroză tumorală alfa (TNF-alfa) și proteina C reactivă (CRP). Aceste molecule nu sunt abstracte. IL-6 fragmentează somnul. TNF-alfa reduce somnul profund și crește micro-trezirile. Irwin și colegii de la UCLA au publicat în 2006 în Biological Psychiatry un studiu care a arătat că nivelurile crescute de markeri inflamatori corelează direct cu somnul de calitate proastă, independent de alte variabile.</p>
<p>Inflamația cronică la nivel scăzut (așa-numita "inflamație de grad jos") nu produce simptome dramatice. Nu ai febră, nu ai dureri acute. Dar produce oboseală difuză, somn neodihnitor și o stare generală de "nu mă simt bine fără să știu de ce." Și vitamina D e unul dintre cei mai importanți modulatori ai acestei inflamații.</p>
<p>Al treilea mecanism: legătura cu depresia. Meta-analize repetate, inclusiv cea a lui Anglin și colegilor publicată în 2013 în British Journal of Psychiatry, au găsit o asociere consistentă între nivelurile scăzute de vitamina D și riscul crescut de depresie. Depresia, la rândul ei, perturbă somnul prin multiple căi: reduce somnul profund, crește somnul REM în prima parte a nopții, produce treziri matinale și modifică arhitectura generală a somnului. Nu orice deficit de vitamina D produce depresie, evident, dar la o persoană cu vulnerabilitate genetică sau sub stres cronic, deficitul poate fi factorul care basculează echilibrul.</p>
<p>Un studiu prospectiv publicat în 2014 în Journal of Clinical Sleep Medicine de Majid și colegii a urmărit 3.048 de bărbați în vârstă și a găsit că nivelurile de vitamina D sub 20 ng/mL erau asociate cu somn mai scurt, latență crescută la adormire (adormeau mai greu) și eficiență a somnului redusă. Asocierea a persistat după ajustare pentru vârstă, indicele de masă corporală, depresia, activitatea fizică și alte variabile confundătoare.</p>
<p>Gao și colegii au publicat în 2018 în Nutrients o meta-analiză a 9 studii intervenționale și au găsit că suplimentarea cu vitamina D a îmbunătățit calitatea somnului măsurată prin Pittsburgh Sleep Quality Index (PSQI), cu efect mai mare la persoanele care aveau deficit la baseline. Nu a funcționat la toată lumea. Dar la cei cu deficit real, efectul a fost consistent.</p>
<p>Acum, un aspect de nuanță: corelația nu e neapărat cauzalitate simplă. Oamenii cu deficit de vitamina D tind să petreacă mai puțin timp afară, să se miște mai puțin și să aibă diete mai sărace. Toate aceste lucruri afectează independent somnul. Vitamina D poate fi parțial un marker al unui stil de viață care nu susține somnul bun, nu doar o cauză directă. Dar studiile intervenționale sugerează că există și o componentă cauzală reală: corectarea deficitului îmbunătățește somnul dincolo de ce s-ar explica doar prin schimbarea stilului de viață.</p>
<h2>Ce alimentează problema</h2>
<p>Prevalența deficitului e șocant de mare. În România, studii realizate de Niculescu și colegii au arătat că 60-70% din populația adultă urbană are niveluri sub 30 ng/mL în lunile de iarnă, iar 30-40% și vara. La nivel european, situația e similară: un studiu pan-european publicat în 2016 de Cashman și colegii în American Journal of Clinical Nutrition a găsit că 40% din populația europeană are niveluri sub 20 ng/mL.</p>
<p>Motivele sunt simple și cumulative. Viața modernă se petrece în interior. Un birou tipic oferă 300-500 de lucși, insuficient pentru producția de vitamina D (care necesită expunere directă la UVB, nu doar lumină). Protecția solară, deși esențială pentru prevenirea cancerului de piele, blochează 95-99% din producția de vitamina D. Persoanele cu piele mai închisă la culoare produc vitamina D mai lent. Vârsta reduce capacitatea pielii de a sintetiza vitamina D (o persoană de 70 de ani produce de 4 ori mai puțină decât una de 20 de ani la aceeași expunere).</p>
<p>Obezitatea e un factor adesea trecut cu vederea. Vitamina D e liposolubilă și se sechestrează în țesutul adipos. O persoană cu un indice de masă corporală peste 30 are nevoie de doze de suplimentare cu 50-100% mai mari pentru a atinge aceleași niveluri serice ca o persoană normoponderală. Wortsman și colegii au demonstrat asta într-un studiu din 2000 publicat în American Journal of Clinical Nutrition.</p>
<p>Alimentația contribuie minim. Foarte puține alimente conțin vitamina D în cantități relevante: peștele gras (somon, macrou, sardine), gălbenușul de ou, ciupercile expuse la UV. O porție de somon sălbatic oferă aproximativ 600-1000 UI de vitamina D. Necesarul zilnic estimat e de 2000-5000 UI pentru menținerea nivelurilor optime, uneori mai mult în funcție de greutate și nivelul de bază. Dieta singură nu acoperă acest necesar pentru majoritatea oamenilor.</p>
<p>Un factor subtil dar relevant: inflamația intestinală reduce absorbția vitaminei D din suplimente. O persoană cu permeabilitate intestinală crescută, SIBO sau boală celiacă nediagnosticată poate lua doze adecvate și să nu atingă nivelurile dorite, pentru că absorbția e compromisă.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): testare și intervenții comportamentale</h3>
<p>Fă o analiză de sânge pentru 25-hidroxi vitamina D (forma de depozitare, cea măsurată standard). Intervalul de referință al laboratorului va arăta probabil 30-100 ng/mL ca "normal." În medicina funcțională, intervalul optim considerat e 50-80 ng/mL, bazat pe studiile care arată că beneficiile pentru sănătatea osoasă, funcția imună și markerii inflamatori se maximizează în această zonă. Un nivel de 32 ng/mL e tehnic "normal" dar departe de optim.</p>
<p>În paralel cu testarea, începe cu sursa originală: lumina solară. Expunerea brațelor și feței la soare direct (fără protecție solară) timp de 15-20 de minute pe zi, în jurul orei 12:00-14:00, în lunile în care indicele UV e peste 3, produce 10.000-20.000 UI de vitamina D. În România, asta funcționează realist din aprilie până în septembrie. În restul anului, suplimentarea e practic obligatorie.</p>
<p>Lumina de dimineață (primele 30-60 de minute după răsărit) nu produce vitamina D în cantități relevante (UVB-ul e filtrat de atmosferă la unghiuri mici), dar sincronizează ritmul circadian, ceea ce susține calitatea somnului prin mecanisme separate. Cele două se completează: lumina de dimineață pentru ritm circadian, lumina de la amiază pentru vitamina D.</p>
<h3>Faza 2 (săptămânile 3-8): suplimentare structurată</h3>
<p>Dacă nivelul e sub 30 ng/mL, o fază de încărcare e utilă: 5000-10.000 UI pe zi timp de 8-12 săptămâni, urmată de retestare. Dacă nivelul e între 30 și 50 ng/mL, 4000-5000 UI pe zi e de obicei suficient ca doză de menținere. Persoanele cu obezitate pot necesita doze mai mari.</p>
<p>Forma recomandată e vitamina D3 (colecalciferol), nu D2 (ergocalciferol). D3 e forma pe care o produce pielea și e metabolizată mai eficient. Studiile lui Heaney și colegii din 2011 publicat în Journal of Clinical Endocrinology & Metabolism au arătat că D3 e de aproximativ 87% mai eficientă decât D2 în ridicarea nivelurilor serice pe termen lung.</p>
<p>Timing-ul suplimentării contează și e frecvent greșit. Vitamina D luată seara poate interfera cu producția de melatonină. Mecanismul nu e complet elucidat, dar Stumpf și Privette au propus încă din 1989 că vitamina D și melatonina au o relație de inhibiție reciprocă. Practic: ia vitamina D dimineața sau la prânz, cu o masă care conține grăsimi (vitamina D e liposolubilă și absorbția crește cu 50% când e luată cu grăsimi alimentare).</p>
<p>Vitamina K2 (forma MK-7, 100-200 mcg pe zi) trebuie luată împreună cu vitamina D. Motivul e fiziologic, nu comercial. Vitamina D crește absorbția intestinală de calciu. Vitamina K2 activează osteocalcina (care direcționează calciul spre oase) și proteina Gla matricială (care împiedică depunerea calciului în artere). Fără K2, calciul suplimentar absorbit datorită vitaminei D riscă să se depună în vasele de sânge și rinichi, nu în oase. Masterjohn, publicând în 2007 în Medical Hypotheses, a argumentat că toxicitatea vitaminei D e parțial o consecință a deficitului relativ de K2.</p>
<p>Magneziu (200-400 mg pe zi, forma glicinat sau citrat) susține conversia vitaminei D în forma activă. Magneziul e cofactor pentru enzimele care transformă 25-hidroxi vitamina D în calcitriol. Un deficit de magneziu, prezent la estimativ 50% din populație, poate limita eficacitatea suplimentării cu vitamina D. Uwitonze și Razzaque, publicând în 2018 în Journal of the American Osteopathic Association, au descris magneziul ca "partenerul uitat al vitaminei D."</p>
<h3>Faza 3 (luna a treia și după): monitorizare și ajustare</h3>
<p>Retestarea 25-hidroxi vitamina D la 8-12 săptămâni după începerea suplimentării e importantă. Răspunsul variază individual în funcție de greutate, absorbție intestinală, genetică (polimorfismele genei VDR și ale genei CYP2R1 influențează metabolismul vitaminei D) și expunerea la soare. Unii oameni ating 60 ng/mL cu 4000 UI pe zi. Alții au nevoie de 8000 UI pentru același nivel.</p>
<p>Dacă nivelurile nu cresc conform așteptărilor după 3 luni de suplimentare adecvată, investighează absorbția intestinală. Testele pentru boală celiacă (anticorpi anti-transglutaminază), SIBO (test respirator) și insuficiență pancreatică exocrină merită luate în considerare.</p>
<p>Observă efectul asupra somnului în timp. Corectarea deficitului de vitamina D nu produce rezultate peste noapte. Nivelurile serice cresc treptat, iar efectele asupra neurotransmițătorilor și inflamației necesită săptămâni până la luni. Un jurnal simplu de calitate a somnului pe parcursul a 3 luni de suplimentare poate arăta tendința, chiar dacă diferența de la o noapte la alta e greu de perceput.</p>
<p>Nu depăși 100 ng/mL fără supraveghere medicală. Niveluri foarte ridicate de vitamina D pot produce hipercalcemie (calciu seric crescut), cu simptome care includ greață, confuzie, poliurie și, ironic, insomnie. Toxicitatea e rară la doze sub 10.000 UI pe zi, dar monitorizarea periodică e prudentă.</p>
<h2>Unde te lasă toate astea</h2>
<p>Vitamina D nu e un remediu miraculos pentru somn. Dacă nivelul tău e deja la 60 ng/mL și dormi prost, cauza e în altă parte. Dar dacă ești ca 40-60% din populația urbană și ai un nivel sub 30 ng/mL, corectarea lui elimină un factor de fond care poate face orice altă intervenție mai puțin eficientă. E ca și cum ai încerca să reglezi un motor în timp ce una din bujii nu funcționează: poți optimiza tot restul, dar până nu repari bugia, motorul nu va merge bine.</p>
<p>Testarea e simplă, suplimentarea e ieftină și riscurile la doze rezonabile sunt minime. Dacă nu ți-ai măsurat niciodată vitamina D, sau dacă ai măsurat-o o dată acum câțiva ani și "era ok," merită o verificare actualizată. Nivelurile se schimbă cu sezonul, cu vârsta și cu stilul de viață. Iar diferența dintre un nivel de 25 și unul de 60 ng/mL se poate simți nu doar în oase, ci și în calitatea fiecărei nopți.</p>
