<p>Dacă seara, în pat, simți o agitație inexplicabilă în picioare care dispare doar când te miști, e posibil ca problema să nu fie stresul sau oboseala. Fierul joacă un rol direct în producția de dopamină, iar când rezervele scad sub un anumit prag, circuitele motorii din creier devin instabile, exact în momentul în care ai nevoie de liniște.</p>
<ul>
  <li>Sindromul picioarelor neliniștite (SPN) afectează 5-10% din populația adultă și e una dintre cele mai frecvente cauze tratabile de insomnie pe care medicii de familie rareori o investighează corect.</li>
  <li>Senzațiile din picioare nu sunt crampe și nu sunt durere clasică. Sunt o nevoie aproape imposibil de descris de a mișca picioarele, care se agravează seara și noaptea, exact când vrei să stai liniștit.</li>
  <li>Fierul e necesar pentru producerea dopaminei în creier, iar dopamina e neurotransmițătorul care reglează controlul motor și senzațiile senzoriale. Când fierul scade, dopamina scade, și circuitele motorii devin instabile.</li>
  <li>Hemoglobina poate fi normală și totuși fierul disponibil pentru creier să fie insuficient. Feritina e măsura reală a rezervelor de fier, și valorile considerate "normale" în laborator (12-150 ng/mL) sunt prea largi pentru a fi utile.</li>
  <li>Cercetarea neurologică arată că simptomele SPN se ameliorează consistent când feritina depășește 50-75 ng/mL, un prag pe care majoritatea laboratoarelor nu îl semnalează.</li>
  <li>Suplimentarea cu fier funcționează, dar forma, doza și momentul administrării contează enorm pentru absorbție și toleranță digestivă.</li>
  <li>Femeile aflate la menstruație, donatorii de sânge și persoanele cu diete restrictive sunt cele mai vulnerabile la această problemă.</li>
  <li>Corectarea fierului nu produce efecte imediate. Sunt necesare 6-12 săptămâni de suplimentare consistentă pentru a vedea o diferență reală în somn.</li>
</ul>
<p>Dacă te-ai întins vreodată în pat după o zi obositoare și ai simțit că picioarele pur și simplu refuză să stea liniștite, știi despre ce vorbesc. Nu e durere. Nu sunt crampe. E o senzație greu de pus în cuvinte: o agitație, un disconfort profund, o nevoie viscerală de a mișca picioarele care apare tocmai când ai vrea să te relaxezi. Unii o descriu ca o mâncărime interioară, alții ca o senzație de târâturi sau de curent electric. Mișcarea ameliorează temporar, dar în momentul în care te oprești, senzația revine.</p>
<p>Sindromul picioarelor neliniștite (SPN) afectează între 5 și 10% din populația adultă, conform datelor epidemiologice publicate de Allen și colaboratorii în Archives of Internal Medicine în 2005. La aproximativ o treime din acești oameni, simptomele sunt suficient de severe încât să afecteze adormitul și să producă privare cronică de somn. Și totuși, în practica medicală curentă, SPN rămâne subdiagnosticat. Motivul e simplu: mulți pacienți nu menționează simptomele pentru că le consideră banale sau ciudate, iar medicii care aud despre ele rareori se gândesc la fier.</p>
<p>Legătura dintre fierul scăzut și picioarele neliniștite e una dintre cele mai bine documentate conexiuni din neurologia somnului. Și e o veste bună, pentru că fierul se poate măsura, se poate corecta, iar rezultatele sunt predictibile.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Povestea începe cu dopamina, nu cu fierul. Dopamina e un neurotransmițător cu multe roluri, dar unul dintre cele mai puțin cunoscute publicului larg e controlul circuitelor senzorio-motorii. În ganglionii bazali, structuri din centrul creierului care filtrează și coordonează mișcarea, dopamina funcționează ca un moderator. Când nivelul ei e adecvat, semnalele motorii sunt fluide și controlate. Când scade, circuitele devin instabile: apar mișcări involuntare, senzații aberante și o nevoie compulsivă de mișcare.</p>
<p>Fierul intră în ecuație pentru că e un cofactor esențial în sinteza dopaminei. Enzima tirozin-hidroxilază, care transformă aminoacidul tirozină în L-DOPA (precursorul direct al dopaminei), are nevoie de fier ca să funcționeze. Fără fier suficient, reacția încetinește, și producția de dopamină scade. James Connor și echipa lui de la Penn State College of Medicine au publicat mai multe studii (2003, 2009, 2011) care au arătat că în creierul pacienților cu SPN, concentrația de fier din substanța neagră (o regiune critică pentru producerea dopaminei) e redusă cu 40-60% față de normal, chiar și atunci când nivelurile de fier din sânge sunt aparent acceptabile.</p>
<p>Aici e punctul care schimbă perspectiva: fierul din sânge și fierul din creier nu sunt același lucru. Fierul traversează bariera hemato-encefalică printr-un mecanism activ de transport, și acest transport are propriile lui limitări. Feritina serică (proteina care stochează fierul în organism) e cel mai bun indicator indirect al cât fier e disponibil pentru creier. Dar pragurile de referință ale laboratoarelor sunt concepute pentru a detecta anemia, nu pentru a evalua disponibilitatea fierului pentru neurotransmisie.</p>
<p>Un laborator tipic va marca feritina ca "normală" dacă e peste 12 ng/mL. Din perspectiva prevenirii anemiei, asta e corect. Din perspectiva neurologică, e complet insuficient. Richard Allen și colaboratorii de la Johns Hopkins au publicat în 2013 o analiză care a arătat că simptomele SPN se ameliorează consistent când feritina depășește 50 ng/mL, cu beneficii adiționale până la 75 ng/mL. Sub 50, chiar și în absența anemiei, creierul poate fi în deficit funcțional de fier.</p>
<p>Mai există un element de timing care face totul mai complicat. Nivelurile de dopamină în creier fluctuează pe parcursul zilei, cu un minim natural seara târziu și noaptea devreme. Asta explică de ce simptomele SPN se agravează seara, în repaus. Nu e doar că stai liniștit și le observi mai bine. E că sistemul dopaminergic e la punctul lui cel mai slab exact atunci când te pregătești de somn. Un nivel de fier care susține producția de dopamină suficient în timpul zilei (când dopamina e la maximum natural) poate fi insuficient noaptea, când sistemul funcționează deja la capacitate redusă.</p>
<p>Un studiu publicat de Earley și colaboratorii în Sleep Medicine Reviews în 2014 a demonstrat că pacienții cu SPN au un ritm circadian al fierului din lichidul cefalorahidian diferit de persoanele sănătoase: fierul disponibil în creier scade și mai mult noaptea. E un deficit pe un deficit, și rezultatul e că senzațiile devin insuportabile tocmai la ora culcării.</p>
<h2>Ce alimentează problema</h2>
<p>Pierderea cronică de fier e cea mai frecventă cauză și e adesea banală. Menstruația regulată e responsabila numărul unu la femeile de vârstă fertilă. O menstruație normală consumă 15-30 mg de fier pe ciclu. O menstruație abundentă poate dubla sau tripla această pierdere. Fără un aport alimentar consistent de fier heminic (din surse animale) sau non-heminic (din surse vegetale) însoțit de vitamina C pentru absorbție, rezervele scad încet, pe parcursul lunilor și anilor.</p>
<p>Donarea de sânge e un factor surprinzător de important. O singură donare elimină aproximativ 200-250 mg de fier. Pentru un bărbat cu rezerve normale, asta se recuperează în câteva luni. Pentru o femeie aflată la menstruație care donează de 2-3 ori pe an, pierderile se cumulează rapid. Un studiu din 2019 publicat de Spencer și colaboratorii în Transfusion a arătat că 25% din donatoarele regulate de sânge aveau feritina sub 20 ng/mL.</p>
<p>Absorbția redusă a fierului e al doilea mare factor. Persoanele cu boală celiacă, gastrită atrofică, infecție cu Helicobacter pylori sau care iau inhibitori de pompă de protoni (omeprazol, pantoprazol) pe termen lung absorb fierul ineficient. Acidul gastric e necesar pentru conversia fierului non-heminic în formă absorbabilă (fier feros, Fe2+). Reducerea acidității gastrice, fie prin boală, fie prin medicație, compromite direct această conversie.</p>
<p>Dietele restrictive contribuie și ele. Vegetarienii și veganii au un risc mai mare de deficit de fier, nu pentru că nu pot obține suficient fier din plante, ci pentru că fierul non-heminic are o rată de absorbție de doar 2-5%, comparativ cu 15-35% pentru fierul heminic din carne roșie. Cantitatea de fier din spanac sau linte poate părea adecvată pe hârtie, dar disponibilitatea reală e mult mai mică.</p>
<p>Sarcina consumă cantități masive de fier. Volumul de sânge crește cu 30-50%, fătul în dezvoltare extrage fier, iar nașterea însăși implică pierderi de sânge. Multe femei intră în perioada postpartum cu feritina practic la zero, și SPN postpartum e documentat ca o entitate clinică distinctă.</p>
<p>Un factor mai puțin evident: exercițiul fizic intens și de durată. Alergătorii de distanță, în special, pierd fier prin transpirație, prin microhemoragii gastrointestinale legate de efort și prin hemoliză mecanică (distrugerea globulelor roșii la impactul repetitiv al picioarelor cu solul). Fenomenul se numește "anemia alergătorului" și e suficient de frecvent încât unii medici sportivi recomandă monitorizarea feritinei la intervale regulate.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): măsurare și identificare</h3>
<p>Primul pas e să știi unde te afli. Cere medicului un set de analize care să includă hemoleucograma completă, fier seric, feritina serică și capacitatea totală de legare a fierului (TIBC). Hemoglobina singură nu e suficientă. Poți avea hemoglobina de 13 g/dL (normal) și feritina de 18 ng/mL (tehnic normal, funcțional scăzută).</p>
<p>Interpretează feritina cu pragurile neurologice, nu cu cele ale laboratorului. Sub 50 ng/mL, există o probabilitate reală ca SPN să fie legat de deficit de fier. Sub 30 ng/mL, probabilitatea crește considerabil. Sub 15 ng/mL, deficitul e clar și suplimentarea e practic obligatorie.</p>
<p>În paralel, observă tiparele simptomelor. Un jurnal scurt, ținut 7-10 zile, în care notezi ora la care apar senzațiile, intensitatea lor și cât de mult îți afectează adormitul, oferă informații utile atât pentru tine, cât și pentru medic.</p>
<h3>Faza 2 (săptămânile 3-8): intervenții alimentare și comportamentale</h3>
<p>Înainte de suplimente, merită optimizat aportul alimentar. Ficatul de vită sau de pui e cea mai concentrată sursă de fier heminic (6-9 mg per 100 de grame). Carnea roșie oferă 2-3 mg per 100 de grame. Peștele și puiul oferă cantități mai mici dar încă relevante.</p>
<p>Pentru sursele vegetale, combinația cu vitamina C crește absorbția de 3-6 ori. Lintea cu suc de lămâie, spanac cu ardei gras, fasole cu roșii. Combinația contează mai mult decât cantitatea brută.</p>
<p>Evită să bei ceai sau cafea în timpul meselor sau la 30 de minute după. Taninurile din ceai și polifenolii din cafea reduc absorbția fierului non-heminic cu până la 60-70%. Laptele și produsele lactate consumate simultan cu surse de fier reduc și ele absorbția, prin calciu.</p>
<p>Mișcarea ușoară seara poate ajuta la ameliorarea temporară a simptomelor. Întinderi blânde ale picioarelor, mers pe loc sau un masaj ușor al gambelor activează circuitele dopaminergice și pot reduce intensitatea senzațiilor suficient cât să permită adormitul.</p>
<p>Un duș cald pe picioare (nu fierbinte) cu 30-60 de minute înainte de culcare a fost raportat în mai multe studii ca ameliorând simptomele, probabil prin creșterea fluxului sangvin local și activarea receptorilor senzoriali care "acoperă" semnalele aberante.</p>
<h3>Faza 3 (luna a doua și după): suplimentare și monitorizare</h3>
<p>Dacă feritina e sub 50 ng/mL și simptomele de SPN sunt prezente, suplimentarea cu fier e justificată. Forma contează. Bisglicinat de fier (chelat de fier) are absorbție bună și produce mai puține efecte gastrointestinale decât sulfatul feros. Doza standard e 25-50 mg de fier elemental, luată pe stomacul gol, cu vitamina C (200-500 mg), pentru a maximiza absorbția.</p>
<p>Timing-ul administrării influențează rezultatul. Fierul se absoarbe cel mai bine pe stomacul gol, dimineața sau între mese. Administrarea la două zile, în loc de zilnic, a arătat în studiul lui Stoffel și colaboratorii publicat în The Lancet Haematology în 2017 că produce o absorbție procentuală mai mare. Hepcidina, hormonul care reglează absorbția fierului, crește după fiecare doză și rămâne ridicată 24 de ore. Administrarea la o zi distanță permite hepcidinei să revină la nivelul bazal.</p>
<p>Așteptările trebuie calibrate realist. Feritina crește lent. O creștere de 10-15 ng/mL pe lună e un ritm bun. Dacă pornești de la 20 ng/mL și țintești 60 ng/mL, sunt necesare 3-4 luni de suplimentare consistentă. Simptomele de SPN încep să se amelioreze de obicei după 6-8 săptămâni, când feritina trece de 40-50 ng/mL.</p>
<p>Retestarea feritinei la 3 luni de la începerea suplimentării confirmă dacă strategia funcționează. Dacă feritina nu crește, cauza e fie absorbție redusă (probleme gastrice, celiakie nedetectată), fie pierdere continuă care depășește aportul.</p>
<p>Un avertisment necesar: fierul în exces e toxic. Suplimentarea fără măsurare prealabilă nu e recomandată. Hemocromatoza (o condiție genetică de acumulare excesivă a fierului) afectează 1 din 200-300 de persoane de origine europeană și poate fi agravată de suplimentare nesupravegheată.</p>
<p>Magneziul (300-400 mg de glicinat sau citrat de magneziu seara) merită luat în considerare ca intervenție complementară. Magneziul contribuie la relaxarea musculară și la reglarea excitabilității neuronale. Nu înlocuiește fierul ca intervenție primară pentru SPN, dar poate reduce intensitatea simptomelor în perioada de așteptare până când feritina crește.</p>
<h2>Unde te lasă toate astea</h2>
<p>Dacă ai senzații neplăcute în picioare seara, care te forțează să te miști și care îți întârzie adormitul, există o cauză biologică concretă pe care merită să o verifici înainte de a pune totul pe seama stresului sau a oboselii. O analiză de sânge care include feritina costă puțin și răspunde la o întrebare precisă.</p>
<p>Frustrarea pe care mulți o simt cu SPN vine din faptul că simptomele par banale și greu de explicat. Dar fiziologia din spate e solidă, iar legătura fier-dopamină-simptome senzorio-motorii e susținută de decenii de cercetare. Nu e o zonă gri. E o problemă cu mecanism clar și soluție specifică.</p>
<p>Corectarea fierului cere răbdare. Nu e o intervenție care produce rezultate peste noapte. Dar e una dintre puținele situații în medicina somnului în care poți măsura un parametru, poți interveni țintit și poți urmări progresul cu numere. Asta e un avantaj pe care merită să îl folosești.</p>
