<p>Alcoolul te ajută să adormi mai repede, asta e real. Dar pe măsură ce ficatul îl metabolizează în orele care urmează, creierul intră într-o stare de hiperexcitabilitate compensatorie care fragmentează exact fazele de somn de care ai cea mai mare nevoie. Dacă te trezești între 2 și 4 dimineața după o seară cu un pahar sau două, mecanismul e foarte specific și merită înțeles.</p>
<ul>
  <li>Cum alcoolul te ajută să adormi mai repede dar îți sabotează exact fazele de somn care contează</li>
  <li>Ce se întâmplă în corp când metabolizezi alcoolul în timpul nopții și de ce te trezești la 3 dimineața</li>
  <li>Mecanismul de rebound simpatic care transformă a doua jumătate a nopții într-un câmp de luptă</li>
  <li>De ce somnul REM e prima victimă a alcoolului și ce consecințe are asta pe memorie și reglare emoțională</li>
  <li>Cât de mult contează cantitatea, timing-ul și tipul de băutură</li>
  <li>Mitul nightcap-ului și de ce bunicii noștri se înșelau elegant</li>
  <li>Intervalul minim dintre ultimul pahar și ora de culcare</li>
  <li>Cum arată un consum realist și compatibil cu un somn decent</li>
</ul>
<p>Probabil știi deja că alcoolul nu e ideal pentru somn. Dar ceea ce majoritatea oamenilor cred e că problema e una de cantitate: dacă bei mult, dormi prost; dacă bei puțin, e ok. Realitatea e mai complicată și, sincer, mai deranjantă. Chiar și cantități moderate de alcool, un pahar de vin, o bere, modifică arhitectura somnului tău în moduri pe care nu le simți direct, dar care se acumulează în timp.</p>
<p>Paradoxul e real și verificabil în orice laborator de somn: alcoolul reduce latența adormirii. Adormi mai repede, asta e cert. Sedarea pe care o produce etanolul funcționează. Dar sedarea nu e somn. Sau, mai precis, sedarea pe care o produce alcoolul mimează somnul fără să-i ofere toate beneficiile. Și pe măsură ce corpul metabolizează alcoolul pe parcursul nopții, efectele se inversează într-un mod pe care merită să-l înțelegi în detaliu.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Când bei alcool seara, etanolul ajunge în creier în câteva minute și interacționează cu mai multe sisteme de neurotransmițători simultan. Cel mai relevant pentru somn e sistemul GABA, principalul neurotransmițător inhibitor al creierului. Alcoolul amplifică efectul GABA, ceea ce produce relaxare, reducerea anxietății și, la doze suficiente, sedare. Simultan, alcoolul blochează glutamatul, principalul neurotransmițător excitator. Efectul combinat e o suprimare generalizată a activității neuronale care seamănă cu adormirea, și într-o oarecare măsură chiar e adormirea, dar cu o diferență importantă.</p>
<p>În prima parte a nopții, când nivelul de alcool din sânge e încă ridicat, somnul arată surprinzător de bine pe o polisomnogramă. Somnul profund (N3) e de fapt crescut față de normal. Asta e partea care îi face pe oameni să creadă că alcoolul îi ajută să doarmă. Și e adevărat, prima jumătate de noapte e relativ consolidată. Dar somnul REM din primele cicluri e suprimat aproape complet. Creierul nu intră în fazele de vis, sau intră foarte puțin.</p>
<p>Problemele serioase încep în a doua jumătate a nopții. Ficatul metabolizează etanolul cu o rată relativ constantă, aproximativ un pahar standard pe oră. Pe măsură ce nivelul de alcool scade, creierul trece printr-un fenomen numit rebound simpatic. Practic, toate sistemele pe care alcoolul le-a suprimat acum supracompensează. GABA scade sub nivelul normal, glutamatul crește peste nivelul normal, iar sistemul nervos simpatic se activează. Rezultatul e un somn fragmentat, superficial, plin de micro-treziri, cu o frecvență cardiacă crescută și transpirații.</p>
<p>Acest rebound explică de ce atât de mulți oameni care beau seara se trezesc între 2 și 4 dimineața și nu mai pot adormi la loc. Nu e o coincidență de timing. E momentul exact în care metabolizarea alcoolului se completează și creierul intră în modul de hiperexcitabilitate compensatorie.</p>
<p>Somnul REM, care ar trebui să domine a doua jumătate a nopții, rămâne perturbat chiar și după ce alcoolul a fost metabolizat complet. Și asta contează enorm, pentru că somnul REM e esențial pentru consolidarea memoriei emoționale, pentru procesarea experiențelor zilei și pentru reglarea afectivă. O noapte cu REM redus te lasă a doua zi mai iritabil, mai reactiv emoțional și cu o capacitate redusă de concentrare, nu din cauza lipsei de somn per se, ci din cauza lipsei de somn REM specific.</p>
<p>Mai e un mecanism pe care puțini îl cunosc: alcoolul crește temperatura corporală în primele ore, apoi produce o scădere sub normal în a doua parte a nopții. Termoreguarea e strâns legată de arhitectura somnului, iar aceste fluctuații destabilizează tranzițiile între stadii. Corpul tău folosește scăderea temperaturii ca semnal pentru menținerea somnului profund. Când alcoolul interferează cu acest semnal, ciclurile de somn se dezorganizează.</p>
<p>Alcoolul e și un diuretic, ceea ce înseamnă că te trezești să mergi la baie. Și relaxează musculatura căilor respiratorii superioare, agravând sforăitul și crescând riscul de episoade de apnee, chiar și la persoanele care în mod normal nu au această problemă. Un studiu din 2020 a arătat că un singur pahar de alcool crește severitatea apneei obstructive de somn cu aproximativ 25%.</p>
<p>Cantitatea contează, evident, dar nu în modul liniar la care te-ai aștepta. Cercetările arată că efectele negative pe arhitectura somnului apar de la cantități surprinzător de mici. Un singur pahar de vin (150 ml) la o persoană de 70 kg e suficient pentru a reduce somnul REM cu 10-15% în acea noapte. Două pahare duc la o reducere de 20-30% și adaugă fragmentarea din a doua jumătate a nopții. Trei pahare sau mai mult înseamnă practic o noapte în care somnul restaurativ e compromis aproape complet.</p>
<p>Mitul nightcap-ului, ideea că un pahar de whisky sau coniac înainte de culcare ajută somnul, vine dintr-o epocă în care nu aveam polisomnografie. Oamenii observau corect că adorm mai repede, dar nu aveau cum să știe ce se întâmplă după. E ca și cum ai evalua calitatea unei mese uitându-te doar la aperitiv.</p>
<h2>Ce alimentează problema</h2>
<p>Există câțiva factori care fac această problemă deosebit de persistentă. Primul e că feedback-ul subiectiv e înșelător. Mulți oameni simt că dorm mai bine când beau, pentru că adormirea e mai rapidă și prima parte a nopții e mai profundă. Fragmentarea din a doua jumătate e adesea uitată dimineața, și oboseala reziduală e atribuită altor cauze.</p>
<p>Al doilea factor e cultural. În multe societăți, paharul de vin la cină e un ritual social profund înrădăcinat. A sugera că acest obicei e problematic pentru somn simți că ataci un mod de viață, nu doar o informație medicală. Și de multe ori, alcoolul seara e o formă de automedicație pentru stres sau anxietate. Paharul de vin devine singurul moment de relaxare din zi, și a renunța la el pare imposibil fără un înlocuitor.</p>
<p>Al treilea factor e toleranța. Consumul regulat de alcool seara duce la adaptarea sistemului GABA. Ai nevoie de mai mult alcool pentru același efect sedativ, dar efectele negative pe arhitectura somnului nu se atenuează în același ritm. Ajungi într-o situație în care bei mai mult pentru a adormi, dar dormi din ce în ce mai prost.</p>
<p>Și mai e un factor subtil: confundarea între relaxare și sedare. Alcoolul produce o stare care seamănă cu relaxarea, dar mecanismul e fundamentalmente diferit. Relaxarea autentică reduce activarea simpatică fără suprimarea funcțiilor cerebrale. Sedarea alcoolică suprimă totul, inclusiv procesele de care ai nevoie pentru un somn de calitate.</p>
<h2>Ce poți face</h2>
<p><strong>Începe cu un experiment, nu cu o decizie permanentă.</strong> Nu-ți spun să nu mai bei niciodată. Îți spun să încerci 10 nopți consecutive fără alcool și să observi cum te simți dimineața. Folosește o aplicație de tracking al somnului sau pur și simplu notează-ți într-un caiet nivelul de energie la trezire, pe o scară de la 1 la 10. Majoritatea oamenilor observă o diferență clară din nopțile 3-4, odată ce efectele de rebound ale opriri consumului regulat se estompează.</p>
<p><strong>Dacă vei continua să bei, timing-ul e totul.</strong> Regula generală e că ai nevoie de cel puțin o oră pentru fiecare unitate standard de alcool, între ultimul pahar și culcare. Un pahar de vin la cină, la ora 19, cu culcare la 23, e o situație complet diferită de același pahar băut la 22. Cu patru ore distanță, cea mai mare parte a alcoolului e metabolizată, iar reboundul simpatic va fi mai blând. Cu o oră distanță, vei dormi practic cu alcool în sistem toată noaptea.</p>
<p><strong>Ajustează cantitatea cu onestitate.</strong> Dacă bei două pahare de vin, ia în calcul că ai nevoie de minim patru ore înainte de culcare pentru a minimiza impactul. Dacă cina cu vin se termină la 21 și te culci la 23, un singur pahar e limita realistă pentru un somn decent.</p>
<p><strong>Mănâncă înainte sau în timpul consumului de alcool.</strong> Alimentele încetinesc absorbția alcoolului, reduc vârful de alcool din sânge și extind metabolizarea. Efectul net e o interferență mai mică cu somnul, deși nu o elimină complet.</p>
<p><strong>Hidratează-te.</strong> Bea un pahar de apă pentru fiecare pahar de alcool. Nu rezolvă problema somnului REM, dar reduce deshidratarea și nevoia de a te trezi la baie.</p>
<p><strong>Găsește alternative reale pentru funcția pe care o îndeplinește alcoolul.</strong> Dacă bei pentru relaxare, experimentează cu ceai de mușețel, o baie caldă, exerciții de respirație, sau o plimbare scurtă după cină. Dacă bei pentru componenta socială, poți alterna un pahar de vin cu apă minerală. Dacă bei din obicei, simpla conștientizare că e un automatism poate fi suficientă pentru a-l întrerupe.</p>
<p><strong>Suplimente care pot susține tranziția:</strong> magneziul glicinat (200-400 mg seara) ajută la relaxare pe calea GABA fără efectele negative ale alcoolului. L-teanina (100-200 mg) reduce anxietatea fără sedare. Extractul de valeriană (300-600 mg) are un efect sedativ ușor care poate înlocui parțial senzația de relaxare de la alcool. Niciunul nu e la fel de puternic ca alcoolul, dar niciunul nu-ți distruge somnul REM.</p>
<h2>Unde te lasă asta</h2>
<p>Nu e vorba despre a demoniza alcoolul sau a transforma fiecare pahar de vin într-o sursă de vinovăție. E vorba despre a înțelege un compromis pe care îl faci de fiecare dată când bei seara, un compromis între plăcerea și relaxarea imediată pe de o parte, și calitatea somnului pe de altă parte. Când înțelegi mecanismul, poți face alegeri informate. Poți decide că vinul de sâmbătă seară merită prețul unei nopți mai slabe, dar că paharul zilnic la cină nu mai are sens. Poți ajusta timing-ul, cantitatea, frecvența. Ceea ce contează e că acum știi ce se întâmplă de fapt după ce stingi lumina, și poți decide în cunoștință de cauză ce faci cu această informație.</p>
