<p>Beta-blocantele pot suprima melatonina nocturnă cu până la 80%. Antidepresivele SSRI cresc mișcările involuntare ale picioarelor în somn la un sfert din pacienți. Dacă iei un medicament zilnic și dormi prost, legătura merită verificată, pentru că 10-15% din cazurile de insomnie cronică au o componentă medicamentoasă directă.</p>
<ul>
  <li>Peste 20 de clase de medicamente comune au insomnia ca efect secundar documentat, dar majoritatea pacienților nu fac legătura</li>
  <li>Beta-blocantele (metoprolol, atenolol, propranolol) suprimă secreția nocturnă de melatonină, mecanismul prin care produc insomnie</li>
  <li>Antidepresivele SSRI și SNRI pot crește mișcările picioarelor în somn și reduce somnul REM, mai ales în primele săptămâni</li>
  <li>Corticosteroizii orali (prednison, dexametazonă) cresc cortizolul exogen și produc o stare de hiperalertă care persistă până la 8 ore după administrare</li>
  <li>Decongestionantele cu pseudoefedrină și bronhodilatatoarele sunt stimulante pe care mulți le ignoră</li>
  <li>Levotiroxina în doză prea mare mimează hipertiroidismul și produce insomnie, transpirații nocturne și puls accelerat</li>
  <li>Statinele pot cauza dureri musculare nocturne la un subset de pacienți, fragmentând somnul prin disconfort</li>
  <li>Oprirea bruscă a oricărui medicament e mai periculoasă decât insomnia pe care o cauzează: ajustările se fac întotdeauna cu medicul</li>
</ul>
<p>Majoritatea oamenilor care iau medicamente zilnic știu să citească prospectul. Sau cel puțin știu că există unul. Dar secțiunea de efecte secundare e lungă, scrisă mărunt și formulată suficient de vag încât să nu pară personală. "Poate cauza tulburări de somn" nu sună la fel de concret ca o trezire la 3 dimineața, noaptea a treia la rând, fără nicio explicație aparentă.</p>
<p>Și totuși, medicamentele sunt una dintre cele mai frecvente cauze de insomnie pe care medicii de somn le întâlnesc. Un review din 2018 publicat de Neubauer în Sleep Medicine Clinics a estimat că 10-15% din cazurile de insomnie cronică au o componentă medicamentoasă, fie ca și cauză primară, fie ca și factor agravant. Problema nu e că medicamentele sunt rele. Problema e că efectul lor asupra somnului e rareori discutat la prescriere, și pacientul ajunge să caute cauze psihologice sau comportamentale când răspunsul e în cutia de medicamente de pe noptieră.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Ca să înțelegi cum un medicament prescris pentru tensiune sau depresie poate strica somnul, merită să înțelegi câte sisteme neurochimice sunt implicate în adormire și menținerea somnului.</p>
<p>Somnul nu e o stare pasivă. E un proces activ orchestrat de mai mulți neurotransmițători și hormoni care trebuie să acționeze în secvență corectă. Melatonina semnalează că e noapte. GABA (acidul gama-aminobutiric) reduce excitabilitatea neuronală și facilitează adormitul. Adenozina se acumulează pe parcursul zilei și crește presiunea de somn. Acetilcolina reglează somnul REM. Noradrenalina și serotonina scad în somnul profund, permițând creierului să intre în stadiile restaurative.</p>
<p>Orice medicament care modifică oricare dintre acești neurotransmițători poate afecta somnul, chiar dacă scopul lui e cu totul altul. Iar multe medicamente comune fac exact asta.</p>
<p>Beta-blocantele sunt probabil exemplul cel mai clar și cel mai studiat. Metoprolol, atenolol, propranolol și bisoprolol sunt prescrise pentru hipertensiune, aritmii și anxietate. Blochează receptorii beta-adrenergici, ceea ce reduce frecvența cardiacă și tensiunea arterială. Dar receptorii beta-adrenergici există și pe glanda pineală, unde sunt implicați în secreția de melatonină. Blocându-i, beta-blocantele reduc producția nocturnă de melatonină cu până la 80%. Stoschitzky și colaboratorii au publicat în 1999 în European Journal of Clinical Pharmacology un studiu care a măsurat exact asta: pacienții pe atenolol aveau niveluri de melatonină nocturnă de 5 ori mai mici decât grupul de control. Propranololul, fiind lipofilic și trecând bariera hemato-encefalică, are efectul cel mai pronunțat asupra somnului, producând și coșmaruri și somn agitat la unii pacienți.</p>
<p>Antidepresivele SSRI (fluoxetină, sertralină, escitalopram, paroxetină) și SNRI (venlafaxină, duloxetină) cresc serotonina și, în cazul SNRI, noradrenalina în spațiul sinaptic. Serotonina crescută poate reduce somnul REM și crește mișcările periodice ale membrelor în somn (PLMS), o condiție în care picioarele se contractă ritmic la fiecare 20-40 de secunde, fragmentând somnul fără ca persoana să fie conștientă. Wichniak și colaboratorii au publicat în 2017 în Journal of Sleep Research un review care a documentat că SSRI-urile cresc PLMS la 15-25% din pacienți. Fluoxetina, având cel mai lung timp de înjumătățire (2-6 zile cu metabolitul activ), e cel mai frecvent asociată cu insomnie.</p>
<p>Un aspect important: insomnia de la SSRI e adesea tranzitorie. Apare în primele 2-4 săptămâni și se ameliorează pe măsură ce creierul se adaptează. Mulți pacienți renunță la antidepresiv în această fereastră, crezând că nu îl tolerează, când de fapt aveau nevoie doar de răbdare. Alți pacienți nu sunt informați că luarea dozei dimineața (în loc de seara) poate face o diferență reală.</p>
<p>Corticosteroizii orali (prednison, prednisolon, dexametazonă, metilprednisolon) sunt prescriși pe termen scurt pentru inflamații acute și pe termen lung pentru boli autoimune. Sunt analogi sintetici ai cortizolului, iar efectul lor asupra somnului e previzibil: cresc alerta, reduc somnul profund și produc o stare de activare care poate persista 6-8 ore după administrare. Curtis și colaboratorii au publicat în 2006 în Journal of Clinical Sleep Medicine un studiu care a documentat că pacienții pe doze moderate de prednison (peste 20 mg/zi) aveau o creștere de 50% a trezirilor nocturne. Dozele mici (sub 10 mg) au efect mai modest, dar nu neglijabil.</p>
<p>Decongestionantele nazale cu pseudoefedrină sau fenilefrină sunt stimulante simpatice. Cresc noradrenalina, produc vasoconstricție (de asta funcționează pentru nas înfundat) și cresc alerta. Multe preparate combinate pentru răceală conțin pseudoefedrină fără ca pacientul să realizeze că ia un stimulant. Versiunile "de noapte" ale acestor preparate înlocuiesc de obicei pseudoefedrina cu un antihistaminic sedativ (difenhidramină), dar versiunile "de zi" luate după ora 16:00 pot perturba somnul.</p>
<p>Bronhodilatatoarele (salbutamol, teofilină, formoterol) sunt stimulante beta-adrenergice sau, în cazul teofilinei, inhibitori de fosfodiesterază. Teofilina e structural înrudită cu cofeina și produce efecte similare: crește alerta, reduce somnul profund și poate produce palpitații nocturne. La pacienții cu astm sau BPOC care iau teofilină seara, insomnia e frecventă și uneori atribuită greșit anxietății legate de boală.</p>
<p>Levotiroxina (Euthyrox, Letrox), hormonul tiroidian sintetic, e unul dintre cele mai prescrise medicamente din lume. În doză corectă, nu afectează somnul. Dar doza corectă nu e fixă pe viață: necesarul de hormon tiroidian variază cu vârsta, greutatea și alți factori. O doză care era potrivită acum doi ani poate fi prea mare astăzi. Simptomele supradozării sunt identice cu cele ale hipertiroidismului: insomnie, transpirații nocturne, puls în repaus peste 80-85, anxietate, tremor fin. Un TSH supresat (sub 0.1 mUI/L) la un pacient pe levotiroxină care nu doarme bine sugerează că doza e prea mare.</p>
<p>Stimulantele pentru ADHD (metilfenidat, lisdexamfetamină, atomoxetină) au insomnia ca efect secundar frecvent și previzibil. Sunt stimulante care cresc dopamina și noradrenalina. Efectul asupra somnului depinde de formulare (cu eliberare imediată versus prelungită) și de ora ultimei doze. Metilfenidatul cu eliberare prelungită luat după ora 12:00 poate încă produce insomnie la culcare. Kidwell și colaboratorii au publicat în 2015 în Journal of Attention Disorders un studiu care a confirmat că formulările cu eliberare prelungită luate dimineața produc mai puțină insomnie decât dozele multiple pe parcursul zilei.</p>
<p>Statinele (atorvastatin, rosuvastatin, simvastatin) sunt prescrise pe scară largă pentru reducerea colesterolului. Efectul lor asupra somnului e controversat, dar un subset de pacienți (estimat la 5-15%) raportează mialgii (dureri musculare) care se agravează noaptea. Mecanismul propus implică reducerea coenzimei Q10 la nivel muscular, ceea ce afectează metabolismul energetic al fibrelor musculare. Simvastatina, fiind lipofilică, trece bariera hemato-encefalică și a fost asociată și cu coșmaruri și tulburări de somn în unele rapoarte. Un studiu din 2012 publicat de Golomb și colaboratorii în JAMA Internal Medicine a raportat că pacienții pe statine aveau scoruri de calitate a somnului mai proaste decât grupul placebo.</p>
<p>Un element pe care multe persoane îl ignoră: cofeina mascată. Unele medicamente combinate conțin cofeină fără ca aceasta să fie evidentă din numele comercial. Analgezicele combinate (cum ar fi cele cu paracetamol + cofeină), preparatele antimigrenoase și unele suplimente energetice conțin 30-65 mg de cofeină per comprimat. Două comprimate de analgezic combinat luate seara pot echivala cu o cafea.</p>
<h2>Ce alimentează problema</h2>
<p>Politerapia (luarea mai multor medicamente simultan) e probabil cel mai important factor agravant. Fiecare medicament individual poate avea un efect modest asupra somnului, dar combinația lor produce insomnie pe care niciun singur medicament nu ar produce-o singur. Un pacient tipic de 65 de ani poate lua beta-blocant (reduce melatonina) + SSRI (reduce REM) + statină (mialgie nocturnă) + levotiroxină (dacă doza e prea mare) + paracetamol cu cofeină pentru dureri articulare. Fiecare medicament contribuie puțin, iar totalul e o noapte fragmentată pe care pacientul o atribuie vârstei sau stresului.</p>
<p>Timing-ul incorect al dozelor e un factor corectabil pe care mulți medici nu îl discută suficient. Beta-blocantele luate seara suprimă melatonina tocmai când e nevoie de ea. Corticosteroizii luați după-amiaza sau seara produc activare când corpul ar trebui să se liniștească. SSRI-urile luate seara pot cauza mai multă insomnie decât cele luate dimineața. Diureticele luate seara produc nicturie.</p>
<p>Schimbările de doză sau de medicament care nu sunt monitorizate. Un medic crește doza de prednison pentru o acutizare și nu reevaluează somnul. Doza de levotiroxină rămâne neschimbată deși pacientul a slăbit 10 kilograme. Farmacistul substituie un SSRI cu altul (de la paroxetină la fluoxetină, de exemplu) și profilele de somn sunt diferite.</p>
<p>Auto-medicația cu preparate care conțin stimulante. Suplimentele "energetice", preparatele de răceală cu pseudoefedrină, ceaiurile cu guarană sau yerba mate conțin cofeină sau compuși similari pe care mulți nu îi contabilizează.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): inventar și observație</h3>
<p>Primul pas e un inventar complet al tuturor medicamentelor, suplimentelor și preparatelor pe care le iei. Nu doar cele prescrise, ci și cele fără rețetă. Scrie-le pe o listă cu: denumire, doză, ora administrării. Adaugă suplimentele, vitaminele, preparatele de răceală ocazionale, analgezicele. Această listă e instrumentul de bază.</p>
<p>Cu lista în mână, verifică fiecare medicament pentru efecte asupra somnului. Prospectul e un început, dar o căutare rapidă cu numele medicamentului și "insomnie" sau "sleep disturbance" oferă informații mai detaliate. Caută și cofeina mascată în compoziție.</p>
<p>Notează într-un jurnal simplu, timp de două săptămâni: ora fiecărei doze și calitatea somnului. Corelațiile pot deveni vizibile: nopțile în care ai luat paracetamol cu cofeină versus cele fără, nopțile după decongestionant versus cele fără.</p>
<p>Nu opri niciun medicament pe cont propriu. Oprirea bruscă a beta-blocantelor poate produce tahicardie rebound și crize hipertensive. Oprirea bruscă a SSRI poate produce sindrom de discontinuare (amețeală, greață, senzații electrice). Oprirea bruscă a corticosteroizilor după uz prelungit poate produce insuficiență suprarenală. Lista asta nu e completă, dar mesajul e: orice modificare se discută cu medicul prescriptor.</p>
<h3>Faza 2 (săptămânile 3-4): discuție cu medicul și ajustări de timing</h3>
<p>Programează o consultație specifică cu subiectul: "Vreau să discutăm despre impactul medicației mele asupra somnului." Mulți medici sunt receptivi la această conversație, dar nu o inițiază ei, pentru că nu e motivul pentru care ai venit inițial. Lista de medicamente cu orele de administrare e punctul de plecare.</p>
<p>Întrebări concrete de adresat:</p>
<p>Pot lua beta-blocantul dimineața în loc de seara? (Răspunsul e frecvent da, cu monitorizarea tensiunii.)</p>
<p>Pot lua SSRI-ul dimineața? (Răspunsul depinde de medicament: fluoxetina și sertralina sunt recomandate dimineața; paroxetina și mirtazapina sunt mai sedative și pot fi luate seara.)</p>
<p>Corticosteroizii pot fi luați exclusiv dimineața? (Doza unică matinală mimează ritmul circadian natural al cortizolului și produce mai puțină insomnie decât dozele repartizate pe parcursul zilei.)</p>
<p>Există alternative în aceeași clasă cu profil de somn mai bun? (Nebivolol, un beta-blocant de nouă generație, are efect mai mic asupra melatoninei decât propranololul. Pravastatina, fiind hidrofilă, nu trece bariera hemato-encefalică și produce mai puține efecte neurologice decât simvastatina.)</p>
<p>Suplimentarea cu melatonină (0.5-3 mg seara) la pacienții pe beta-blocante are logică farmacologică: înlocuiește melatonina pe care beta-blocantul o suprimă. Scheer și colaboratorii au publicat în 2012 în Sleep un studiu care a confirmat că melatonina exogenă îmbunătățește somnul la pacienții pe atenolol.</p>
<h3>Faza 3 (luna a doua și după): evaluare și monitorizare</h3>
<p>După ajustările de timing și eventualele schimbări de medicament, reevaluează somnul după 4 săptămâni. Unele efecte (mai ales cele ale SSRI) se ameliorează spontan cu trecerea timpului, pe măsură ce creierul se adaptează. Altele (beta-blocantele și melatonina) necesită intervenția directă.</p>
<p>Dacă insomnia persistă după optimizarea medicației, cauza e probabil multifactorială. Stresul, obiceiurile de somn și alte condiții medicale pot coexista cu efectul medicamentos. În acest caz, o evaluare de somn completă (polisomnografie, consultație cu specialist în medicina somnului) poate identifica cauze suprapuse: apnee de somn, sindrom al picioarelor neliniștite, tulburare circadiană.</p>
<p>Coenzima Q10 (100-200 mg seara) merită încercată la pacienții pe statine care raportează mialgii nocturne. Un review din 2018 publicat de Qu și colaboratorii în Atherosclerosis a concluzionat că suplimentarea cu CoQ10 reduce mialgiile asociate statinelor la o proporție relevantă de pacienți, deși rezultatele nu sunt uniforme.</p>
<p>Monitorizarea TSH la fiecare 6-12 luni la pacienții pe levotiroxină previne supradozarea. O modificare ponderală de 5-10% poate necesita ajustarea dozei. Insomnia nouă la un pacient stabil pe levotiroxină merită un TSH de control.</p>
<p>O notă despre suplimentele de somn: mulți pacienți care suferă de insomnie medicamentoasă încearcă melatonină, magneziu, valeriană sau alte suplimente fără să adreseze cauza primară. Suplimentele pot ameliora simptomul, dar nu rezolvă conflictul farmacologic. E ca și cum ai încerca să dormi cu dopul de urechi în loc să oprești alarma.</p>
<h2>Unde te lasă toate astea</h2>
<p>Informația centrală din acest articol e una pe care mulți o subestimează: dacă insomnia ta a început sau s-a agravat în perioada în care ai început un medicament nou, schimbat o doză sau adăugat un preparat, corelația merită investigată înainte de a căuta cauze mai exotice. Nu înseamnă că medicamentul e vinovat. Înseamnă că merită exclus sau confirmat.</p>
<p>Partea încurajatoare e că soluțiile sunt adesea simple: mutarea dozei într-un alt moment al zilei, înlocuirea cu un medicament din aceeași clasă dar cu profil de somn mai bun, sau adăugarea de melatonină când cauza e suprimarea ei de către beta-blocante. Niciuna din aceste ajustări nu e complicată medical. Dar toate necesită o conversație pe care mulți pacienți nu o au pentru că nu știu că ar trebui să o aibă.</p>
<p>Lista de medicamente cu orele de administrare, ținută la zi, e cel mai util document pe care îl poți aduce la orice consultație medicală. Nu doar pentru somn, ci pentru orice. Faptul că ai făcut-o și că ai verificat fiecare medicament pentru efecte asupra somnului te pune într-o poziție în care poți pune întrebări concrete în loc de întrebări vagi. Iar întrebările concrete duc la răspunsuri utile.</p>
