<p>Magneziul amplifică semnalul GABA (frâna naturală a creierului), participă la producția de melatonină și reglează relaxarea musculară. Deficitul lui afectează aproximativ jumătate din populația adultă, dar analizele standard de sânge îl ratează aproape întotdeauna. Dacă adormi greu, te trezești cu mușchi încordați sau ai crampe nocturne, conexiunea merită explorată.</p>
<ul>
  <li>Magneziul participă la peste 600 de reacții enzimatice în corp, inclusiv cele care reglează relaxarea musculară, activitatea GABA și conversia triptofanului în melatonină</li>
  <li>Deficitul subclinic de magneziu afectează aproximativ 50-60% din populația adultă și rămâne aproape întotdeauna nediagnosticat prin analizele standard de sânge</li>
  <li>Simptomele deficitului se suprapun cu cele ale insomniei: tensiune musculară, dificultate de relaxare, treziri nocturne, anxietate de seară</li>
  <li>Solul sărăcit, procesarea alimentelor și stresul cronic sunt cele trei cauze principale ale deficitului generalizat</li>
  <li>Sursele alimentare cele mai bogate includ semințele de dovleac, ciocolata neagră, spanacul, migdalele și fasolea neagră</li>
  <li>Nu toate formele de magneziu sunt echivalente: glicinatul și treonatul au profiluri distincte pentru somn și funcție cognitivă</li>
  <li>Dozele optime variază între 200 și 400 mg de magneziu elemental seara, cu ajustare individuală</li>
  <li>Există contraindicații reale la suplimentare care merită cunoscute înainte de a începe</li>
</ul>
<p>Dacă ai încercat deja câteva lucruri pentru somn (ecrane oprite, cameră răcoroasă, program regulat) și tot simți că adormitul e o luptă sau că te trezești cu mușchi încordați și oboseală reziduală, există o posibilitate pe care puțini oameni o verifică: nu ai suficient magneziu.</p>
<p>Nu sună spectaculos. Un mineral. Nu un dezechilibru hormonal dramatic, nu o tulburare de somn cu nume complicat. Dar magneziul e implicat în atât de multe procese legate de somn încât deficitul lui, care e surprinzător de frecvent, poate sabota calitatea nopții din mai multe direcții simultan. Și partea interesantă e că nici nu știi că ți-l lipsește, pentru că analizele obișnuite de sânge nu îl detectează corect.</p>
<p>Merită înțeles de ce contează, cum se instalează deficitul și ce poți face concret, în ordinea corectă.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Magneziul e al patrulea cel mai abundent mineral din corpul uman și participă la peste 600 de reacții enzimatice documentate. În contextul somnului, trei roluri sunt esențiale.</p>
<p>Primul: reglarea GABA. Acidul gamma-aminobutiric (GABA) e principalul neurotransmițător inhibitor al creierului. Funcționează ca o frână. Când GABA se leagă de receptorii săi, activitatea neuronală scade, anxietatea se reduce și corpul se pregătește de somn. Magneziul se leagă de receptorii GABA de tip A și le potențiază efectul, funcționând ca un amplificator al semnalului de calmare. Fără magneziu suficient, GABA lucrează la jumătate de capacitate. Interesant, benzodiazepinele (Xanax, Diazepam) funcționează pe același receptor GABA, doar că mult mai agresiv. Magneziul oferă o versiune fiziologică, blândă și naturală a aceluiași mecanism.</p>
<p>Al doilea rol: conversia triptofanului în serotonină și apoi în melatonină. Lanțul biochimic arată așa: triptofanul (aminoacid esențial din alimente) e convertit în 5-HTP de enzima triptofan hidroxilază, apoi în serotonină, apoi în melatonină de enzima AANAT. Magneziul e cofactor necesar în mai multe etape ale acestui lanț. Când nivelul de magneziu e scăzut, conversia e încetinită, ceea ce înseamnă mai puțină serotonină ziua (dispoziție mai proastă) și mai puțină melatonină noaptea (adormire mai dificilă). Un studiu publicat de Abbasi et al. în Journal of Research in Medical Sciences (2012) a arătat că suplimentarea cu 500 mg de magneziu zilnic la persoane vârstnice cu insomnie a crescut nivelurile serice de melatonină și a îmbunătățit toți parametrii subiectivi ai somnului după 8 săptămâni.</p>
<p>Al treilea rol: relaxarea musculară. Magneziul reglează fluxul de calciu în celulele musculare. Calciul contractă mușchiul, magneziul îl relaxează. Când raportul e dezechilibrat în favoarea calciului (ceea ce se întâmplă în deficitul de magneziu), mușchii rămân într-o stare de semicontracție. Rezultatele: crampe nocturne, sindromul picioarelor neliniștite, tensiune în mandibulă (bruxism), incapacitatea de a simți corpul relaxat în pat. Multe persoane atribuie aceste simptome stresului sau oboselii, dar deficitul de magneziu e o cauză frecventă și corectabilă.</p>
<p>Un al patrulea mecanism, mai puțin discutat, privește axa HPA (hipotalamus-hipofiză-suprarenale). Magneziul modulează răspunsul la stres prin reglarea eliberării de cortizol. Cercetările lui Sartori et al., publicate în Nutrients (2012), au demonstrat că deficitul de magneziu crește reactivitatea axei HPA, rezultând în niveluri mai ridicate de cortizol, mai ales seara. Cortizolul crescut seara e unul dintre cele mai comune mecanisme ale insomniei de adormire. Corectarea magneziului nu oprește stresul, dar reduce amplificarea biologică a răspunsului la stres.</p>
<p>Acum, de ce e deficitul atât de frecvent? Datele NHANES (National Health and Nutrition Examination Survey) din SUA arată că aproximativ 50% din populația adultă nu atinge aportul zilnic recomandat de magneziu (400-420 mg pentru bărbați, 310-320 mg pentru femei). În Europa, cifrele sunt similare. Trei factori converg: solul agricol s-a sărăcit în magneziu pe parcursul ultimelor decenii din cauza agriculturii intensive (ceea ce înseamnă că alimentele conțin mai puțin magneziu decât acum 50 de ani); procesarea alimentelor elimină 80-95% din magneziu (făina albă are 16% din magneziul grâului integral); stresul cronic crește excreția urinară de magneziu, consumând rezervele mai repede.</p>
<p>Problema diagnosticării e reală. Doar 1% din magneziul total al corpului se află în sânge. Restul e în oase, mușchi și țesuturi moi. O analiză standard de magneziu seric poate fi normală chiar și când deficitul tisular e sever. Testul mai precis e magneziul eritrocitar (din globulele roșii), dar nici acesta nu e perfect. În practică, mulți medici de medicină funcțională evaluează magneziul prin combinația de simptome clinice, aport alimentar și răspuns la suplimentare, nu doar prin analize de laborator.</p>
<h2>Ce alimentează problema</h2>
<p>Cafeaua, consumată în cantități mari, crește excreția renală de magneziu. Un consum de 3-4 cești pe zi poate crește pierderile urinare cu 30-40%. Ironia e evidentă: cafeaua compensează oboseala cauzată (parțial) de deficitul de magneziu, care e agravat de cafea.</p>
<p>Alcoolul are un efect similar. Consumul regulat crește pierderile de magneziu prin urină și reduce absorbția intestinală. Un studiu publicat de Romani et al. în Archives of Biochemistry and Biophysics a documentat că alcoolul cronic poate reduce magneziul total al corpului cu 20-30%.</p>
<p>Transpirația intensă (antrenamente, saună, vară) elimină magneziu. Sportivii și persoanele foarte active fizic au cerințe mai mari și pierderi mai mari, o combinație care face deficitul probabil fără suplimentare conștientă.</p>
<p>Medicamentele contribuie nebănuit. Inhibitorii de pompă de protoni (omeprazol, pantoprazol), folosiți pentru reflux, reduc absorbția magneziului prin modificarea pH-ului gastric. Diureticele cresc excreția. Antibioticele fluoroquinolonice (ciprofloxacina) se leagă de magneziu. Dacă iei oricare dintre aceste medicamente pe termen lung, verificarea magneziului e cu atât mai importantă.</p>
<p>Dietele restrictive (keto strict, post prelungit, diete cu foarte puține calorii) limitează aportul alimentar și pot precipita deficitul în săptămâni.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): creșterea aportului alimentar</h3>
<p>Înainte de suplimente, merită să vezi cât magneziu primești din mâncare. Sursele cele mai concentrate (în mg per porție standard):</p>
<p>Semințele de dovleac: 150 mg per 30 g. Probabil cea mai densă sursă alimentară. O mână pe zi acoperă aproape jumătate din necesarul zilnic.</p>
<p>Ciocolata neagră (70%+ cacao): 65 mg per 30 g. Un pătrat sau două după masă au și efect hedonic, nu doar nutrițional.</p>
<p>Spanacul gătit: 157 mg per cană. Gătitul crește biodisponibilitatea magneziului din spanac prin reducerea oxalaților care altfel leagă mineralul.</p>
<p>Migdalele: 80 mg per 30 g. Ușor de incorporat ca gustare.</p>
<p>Fasolea neagră: 120 mg per cană gătită. Leguminoasele în general sunt surse bune, cu beneficiul adăugat al fibrelor.</p>
<p>Bananele: 32 mg per bucată. Mai puțin decât se crede popular, dar contribuie.</p>
<p>Avocado: 58 mg per bucată. Plus grăsimi sănătoase, plus potasiu.</p>
<p>O strategie practică: adaugă în fiecare zi cel puțin două din sursele de mai sus. Nu ca supliment dietetic, ci ca ingrediente normale în mesele existente. Semințe de dovleac pe salată sau în iaurt, spanac în omlete, fasole în supe sau tocane, migdale ca gustare. Aportul alimentar crescut are avantajul absorbției naturale, cu cofactorii necesari incluși.</p>
<p>Apa minerală bogată în magneziu (peste 50 mg/L) e o sursă subestimată. În România, există ape minerale cu conținut ridicat de magneziu care contribuie la aportul zilnic fără niciun efort suplimentar. Verifică eticheta.</p>
<p>Reducerea factorilor de pierdere e la fel de importantă ca creșterea aportului: limitează cafeaua la 2 cești pe zi (înainte de ora 14:00, ideal), moderează alcoolul și asigură-te că dieta nu e atât de restrictivă încât elimină grupuri întregi de alimente bogate în magneziu.</p>
<h3>Faza 2 (săptămânile 3-4): suplimentare țintită</h3>
<p>Dacă simptomele persistă după două săptămâni de aport alimentar crescut (sau dacă evaluarea inițială sugerează deficit probabil), suplimentarea e următorul pas. Dar forma de magneziu contează enorm.</p>
<p>Magneziul glichinat (magnesium glycinate, uneori scris bisglicinat) e cea mai recomandată formă pentru somn. Glicina, aminoacidul la care e legat, e ea însăși un neurotransmițător inhibitor cu efect calmant. Absorbția intestinală e bună și efectul laxativ e minim. Doza de pornire: 200 mg de magneziu elemental (nu masa totală a compusului, ci magneziul pur) seara, cu 30-60 de minute înainte de culcare. După o săptămână, dacă e bine tolerat, se poate crește la 300-400 mg.</p>
<p>Magneziul treonat (magnesium L-threonate, marca Magtein) e singura formă care a demonstrat că traversează bariera hematoencefalică și crește nivelul de magneziu direct în creier. Studiile lui Guosong Liu de la MIT, publicate în Neuron (2010), au arătat îmbunătățiri ale memoriei și funcției cognitive. Pentru somn, e relevant prin efectul direct pe receptorii GABA cerebrali. Doza tipică e 1-2 g de magneziu treonat (care conțin aproximativ 140 mg magneziu elemental). Poate fi combinat cu glicinatul.</p>
<p>Magneziul citrat are absorbție bună dar efect laxativ mai pronunțat. E util dacă constipația e o problemă asociată, dar pentru somn nu e prima alegere.</p>
<p>Magneziul oxid are absorbția cea mai slabă (4%), e ieftin și e ceea ce găsești în majoritatea suplimentelor generice de la farmacie. Nu îl recomand pentru corectarea deficitului.</p>
<p>Magneziul taurinat combină magneziul cu taurina, un aminoacid cu proprietăți calmante. Taurina susține funcția receptorilor GABA similar cu glicina. E o opțiune bună, mai ales pentru persoanele cu anxietate de seară pronunțată.</p>
<p>Momentul suplimentării contează. Seara, cu 30-60 de minute înainte de culcare, pe stomacul relativ gol (sau cu gustarea ușoară de seară). Absorbția e mai bună când magneziul nu concurează cu cantități mari de calciu din aceeași masă.</p>
<h3>Faza 3 (luna a doua și după): personalizare și menținere</h3>
<p>Efectele suplimentării devin vizibile treptat. Relaxarea musculară se îmbunătățește în primele 3-5 zile. Calitatea somnului urmează în 1-2 săptămâni. Reducerea anxietății și stabilizarea dispoziției pot lua 3-4 săptămâni. Dacă după o lună de suplimentare corectă nu observi nicio schimbare, magneziul probabil nu e factorul limitant în cazul tău și merită explorare alte direcții.</p>
<p>Monitorizarea se face prin simptome, nu prin analize serice. Întrebări de evaluare: mai am crampe nocturne? mă relaxez mai ușor în pat? mă trezesc mai rar? tensiunea din mandibulă s-a redus? Răspunsurile la aceste întrebări sunt mai relevante decât o valoare de laborator.</p>
<p>Doza de menținere pe termen lung e de obicei 200-300 mg de magneziu elemental, mai mică decât doza de încărcare inițială. Magneziul e hidrosolubil și excesul e eliminat renal, dar nu e un motiv să iei doze foarte mari. Respectarea intervalului 200-400 mg oferă beneficii fără riscuri.</p>
<p>Contraindicații reale: insuficiență renală (rinichii nu pot elimina excesul), miastenia gravis (magneziul relaxează mușchii și poate agrava slăbiciunea), blocuri cardiace (magneziul afectează conducția electrică a inimii). Dacă iei medicamente pentru inimă, litiu sau antibiotice, verifică interacțiunile cu medicul înainte de suplimentare. La persoanele sănătoase, magneziul în dozele menționate are un profil de siguranță excelent.</p>
<p>Combinația cu vitamina B6 crește absorbția și utilizarea magneziului. Multe formule de calitate includ B6 (sub forma de piridoxal-5-fosfat, formă activă) în combinație cu magneziul. Doza de B6: 25-50 mg, nu mai mult, pentru că dozele mari cronice pot cauza neuropatie periferică.</p>
<h2>Unde te lasă toate astea</h2>
<p>Magneziul nu e o soluție magică pentru insomnie și nu pretind că ar fi. Dar e un element de bază pe care mulți oameni îl ignoră pentru că nu știu că le lipsește. E ca și cum ai încerca să pornești o mașină fără ulei suficient în motor: totul pare în regulă la suprafață, dar motorul funcționează sub parametri și se uzează mai repede.</p>
<p>Dacă ai simptome care rezonează cu ce s-a descris aici (tensiune musculară seara, dificultate de relaxare, crampe, treziri, anxietate fără cauză evidentă), merită să încerci. Începe cu alimentele, adaugă suplimentul după două săptămâni dacă e nevoie, observă ce se schimbă. Riscul e minim, costul e mic, iar potențialul de îmbunătățire, la persoanele cu deficit real, e disproporționat de mare față de simplitatea intervenției.</p>
<p>Cumpără o pungă de semințe de dovleac și un flacon de magneziu glicinat. Începe săptămâna asta. Și lasă corpul să-ți arate dacă avea nevoie de acest lucru simplu pe care nu i-l dădeai.</p>
