<p>Sistemul nervos autonom funcționează ca un balans între accelerator și frână. Dacă stresul cronic ține acceleratorul apăsat prea mult timp, frâna parasimpatică slăbește, iar corpul rămâne în alertă chiar și atunci când te culci. Nu e o problemă de voință, ci de calibrare a unui sistem care a învățat că trebuie să fie mereu pregătit.</p>
<ul>
  <li>Sistemul nervos autonom are două ramuri principale: simpaticul (accelerator) și parasimpaticul (frână). Somnul necesită activarea frânei. Când frâna nu funcționează, corpul rămâne în alertă chiar și în pat.</li>
  <li>Stresul cronic nu crește doar cortizolul. Recalibrează întregul sistem nervos autonom, făcând ramura simpatică dominantă și reducând capacitatea parasimpaticului de a prelua controlul seara.</li>
  <li>Hipervigilența nocturnă se manifestă prin treziri cu puls rapid, tensiune musculară în maxilar sau umeri, respirație superficială în somn și senzația că dormi "cu un ochi deschis."</li>
  <li>Nervul vag, principalul canal parasimpatic, poate fi activat deliberat prin respirație, expunere la frig și alte tehnici, iar efectele sunt măsurabile în variabilitatea ritmului cardiac.</li>
  <li>Teoria polivagală a lui Stephen Porges explică de ce unii oameni nu pot "pur și simplu să se relaxeze": sistemul lor nervos evaluează mediul ca nesigur, și până când această evaluare se schimbă, relaxarea voluntară e aproape imposibilă.</li>
  <li>Somatic Experiencing și alte abordări orientate pe corp lucrează cu tiparele stocate în sistemul nervos, nu doar cu gândurile despre stres.</li>
  <li>Respirația diafragmatică cu expir prelungit e cea mai rapidă cale de activare vagală și poate fi învățată în câteva minute.</li>
  <li>Recalibrarea sistemului nervos autonom nu e instantanee. E un proces de antrenament care produce rezultate progresive pe parcursul săptămânilor.</li>
</ul>
<p>Există o situație pe care mulți o recunosc: ești obosit, ai avut o zi lungă, te bagi în pat la o oră rezonabilă și... corpul refuză să se predea. Mintea poate fi chiar relativ calmă, dar pulsul e ușor ridicat, mușchii sunt încordați, respirația e scurtă și superficială. Sau adormi relativ repede, dar te trezești la 2-3 dimineața cu inima bătând alert, fără niciun coșmar, fără niciun zgomot, aparent fără motiv.</p>
<p>Ce se întâmplă în aceste momente nu e o problemă psihologică în sensul tradițional. E o problemă de reglare a sistemului nervos autonom. Corpul tău e blocat pe poziția de alertă, iar sistemul care ar trebui să activeze modul de repaus nu reușește să preia controlul. E ca și cum ai încerca să adormi cu alarma de incendiu pornită la volum redus: nu e suficient de puternică să te sperie, dar e suficientă să te țină treaz.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Sistemul nervos autonom reglează tot ce funcționează fără voința ta conștientă: ritmul cardiac, digestia, respirația în somn, dilatarea pupilelor, temperatura pielii. Are două ramuri majore care funcționează într-un echilibru dinamic.</p>
<p>Ramura simpatică e sistemul de mobilizare. Când e activă, pregătește corpul pentru acțiune: crește pulsul, redirecționează sângele către mușchi, dilată pupilele, eliberează glucoză din ficat, suprimă digestia. E răspunsul de luptă sau fugă, dar nu doar în forma sa extremă. Simpaticul operează pe un spectru, de la o activare ușoară (vigilență sporită) până la răspunsul total de panică.</p>
<p>Ramura parasimpatică e sistemul de recuperare. Când e activă, încetinește pulsul, stimulează digestia, relaxează musculatura netedă, favorizează repararea tisulară și, relevant pentru discuția noastră, facilitează adormitul și menține somnul profund. Nervul vag e principalul canal prin care parasimpaticul își exercită efectele. Pornește din trunchiul cerebral, coboară prin gât (unde trece lângă arterele carotide), traversează toracele și ajunge în abdomen, inervând inima, plămânii, stomacul și intestinele pe drum.</p>
<p>În condiții normale, trecerea de la activitate diurnă la somn implică o tranziție graduală de la dominanță simpatică la dominanță parasimpatică. Această tranziție începe cu 1-2 ore înainte de adormire și se aprofundează pe parcursul primelor cicluri de somn. Somogyi și colaboratorii au publicat în 2004 în Autonomic Neuroscience un studiu care a arătat că variabilitatea ritmului cardiac (HRV), un marker al echilibrului autonom, crește progresiv în primele ore de somn la persoanele sănătoase, reflectând activarea parasimpatică tot mai puternică.</p>
<p>Problema apare când această tranziție nu se face complet. În stresul cronic, sistemul nervos autonom suferă o recalibrare. Nu e că simpaticul e activat la maximum permanent. E că pragul de activare parasimpatică crește. Gândește-te la un termostat reglat greșit: nu e că încălzirea e stricată, e că se oprește prea târziu și pornește prea devreme. Corpul rămâne într-o stare de activare simpatică ușoară dar persistentă, care noaptea e suficientă să fragmenteze somnul.</p>
<p>Irwin și colaboratorii au publicat în 2006 în Biological Psychiatry un studiu care a măsurat activitatea nervoasă simpatică la pacienții cu insomnie și la un grup de control pe parcursul a 24 de ore. Pacienții cu insomnie aveau activitate simpatică crescută nu doar noaptea, ci pe întreaga durată a zilei, cu un vârf seara. Concluzia cercetătorilor a fost că insomnia nu e doar o problemă de somn, ci o stare de hiperactivare autonomă pe 24 de ore care se manifestă cel mai evident noaptea, când lipsa activității externe lasă corpul singur cu propriile semnale interne.</p>
<p>Teoria polivagală, dezvoltată de Stephen Porges începând din anii 1990, adaugă un strat de înțelegere. Porges a propus că nervul vag are două ramuri funcționale distincte. Ramura vagală ventrală (mai nouă evolutiv) e asociată cu siguranță socială, relaxare și capacitatea de conectare. Ramura vagală dorsală (mai veche evolutiv) e asociată cu înghețarea, disocierea și colapsul. Între cele două, sistemul simpatic gestionează lupta și fuga.</p>
<p>Conform acestui model, capacitatea de a adormi necesită activarea vagalului ventral, starea în care sistemul nervos evaluează mediul ca sigur. Când această evaluare lipsește, fie din cauza stresului cronic, fie din cauza unor experiențe traumatice nesoluționate, sistemul rămâne blocat în modul simpatic (alertă) sau oscilează între simpatic și vagal dorsal (alternând între agitație și epuizare). Nici una dintre aceste stări nu susține un somn de calitate.</p>
<p>Un aspect pe care cercetarea recentă l-a clarificat: această evaluare a siguranței (pe care Porges o numește neurocepție) nu e conștientă. Nu poți decide rațional că ești în siguranță și să te relaxezi. Sistemul nervos face această evaluare automat, pe baza semnalelor senzoriale (sunet, lumină, temperatură, expresii faciale, postură corporală) și pe baza memoriei somatice stocate în corp. De aceea sfatul "relaxează-te" e atât de ineficient pentru persoanele cu hiperactivare autonomă. Nu e o problemă de voință, ci de calibrare a unui sistem automat.</p>
<h2>Ce alimentează problema</h2>
<p>Stresul cronic e factorul principal, dar nu în sensul generic în care termenul e folosit de obicei. Ceea ce contează nu e intensitatea unui singur eveniment stresant, ci durata expunerii la stres fără perioade adecvate de recuperare. Un proiect dificil la muncă urmat de o vacanță nu recalibrează sistemul nervos. Șase luni de presiune constantă, cu weekend-uri în care gândurile de lucru persistă, fără activități de deconectare reală, produc o recalibrare treptată a pragului simpatic.</p>
<p>Traumele nesoluționate sunt un factor pe care mulți îl subestimează. Nu vorbim neapărat de traume majore. Experiențe repetate de nesiguranță în copilărie, relații în care te simțeai constant evaluat sau criticat, perioade prelungite de izolare, toate lasă o amprentă în calibrarea sistemului nervos autonom. Corpul învață că trebuie să fie în alertă și menține această postură ani de zile sau decenii după ce circumstanțele s-au schimbat.</p>
<p>Sedentarismul reduce tonusul vagal. Activitatea fizică regulată e unul dintre cele mai puternice stimulente ale parasimpaticului. În absența ei, capacitatea nervului vag de a prelua controlul scade treptat.</p>
<p>Consumul excesiv de cofeină menține simpaticul activat artificial. Cofeina blochează receptorii de adenozină (molecula care semnalează oboseala) și crește eliberarea de noradrenalină. Efectul persistă 5-8 ore după consum. O cafea la 15:00 încă influențează echilibrul autonom la 23:00.</p>
<p>Expunerea constantă la informații alarmante (știri, social media cu conținut conflictual, notificări permanente) menține sistemul nervos în stare de scanare a amenințărilor. Sistemul nu face diferența între o amenințare reală și una percepută prin ecran. Reacția fiziologică e aceeași: activare simpatică, cortizol, vigilență.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): activare vagală directă</h3>
<p>Respirația diafragmatică cu expir prelungit e instrumentul cel mai rapid și cel mai bine documentat pentru activarea parasimpaticului. Mecanismul e direct: la expir, nervul vag trimite semnale de încetinire către inimă (prin eliberarea de acetilcolină la nodul sinoatrial). Când expirul e mai lung decât inspirul, efectul parasimpatic se amplifică.</p>
<p>Protocolul concret: inspir pe nas, 4 secunde, expir pe gură sau pe nas, 6-8 secunde. Nu e nevoie să fie forțat. Ritmul trebuie să fie confortabil. 5-10 minute înainte de culcare, în poziție culcat sau șezând. Un studiu publicat de Laborde și colaboratorii în 2017 în Frontiers in Psychology a arătat că respirația lentă (6 respirații pe minut) crește HRV și activează componenta parasimpatică în mod detectabil după doar 5 minute.</p>
<p>Expunerea scurtă la frig activează nervul vag printr-un reflex direct. Ceva simplu: spălarea feței cu apă rece seara sau un duș cu 30 de secunde de apă rece la final. Reflexul de imersie (diving reflex) activează parasimpaticul și încetinește pulsul. Nu e confortabil la început, dar efectul fiziologic e imediat și documentat.</p>
<p>Reducerea stimulării senzoriale cu 60-90 de minute înainte de somn nu e un sfat despre ecrane (deși include și asta). E un sfat despre crearea condițiilor în care neurocepția poate evalua mediul ca sigur. Lumină scăzută, sunete joase sau liniște, temperatură confortabilă, absența informațiilor noi. Sistemul nervos are nevoie de dovezi senzoriale că nu există amenințări active.</p>
<h3>Faza 2 (săptămânile 3-6): antrenament și restructurare</h3>
<p>Yoga restaurativă (nu yoga dinamică, ci posturi pasive ținute 5-10 minute, susținute de perne și pături) activează parasimpaticul printr-o combinație de poziție corporală, respirație lentă și absența efortului muscular. Un studiu publicat de Streeter și colaboratorii în 2010 în Journal of Alternative and Complementary Medicine a arătat că practicanții de yoga aveau niveluri mai ridicate de GABA (neurotransmițător inhibitor) decât grupul de control care făcea plimbări de aceeași durată. Efectul nu e doar relaxare subiectivă; e o modificare neurochimică măsurabilă.</p>
<p>Activitatea fizică aerobică moderată (30-40 de minute, 3-4 zile pe săptămână) crește tonusul vagal pe termen lung. Mersul alert, înotul, ciclismul la intensitate moderată. Efectul nu e imediat: HRV-ul începe să crească după 4-6 săptămâni de antrenament consistent. Dar e unul dintre cele mai robuste efecte documentate în literatura despre reglarea autonomă.</p>
<p>Meditația, în special formele orientate pe corp (body scan, mindfulness somatic), antrenează capacitatea de a detecta semnale corporale fără a reacționa la ele. Asta e relevant pentru hipervigilența nocturnă: mulți oameni cu sistem nervos hiperactiv percep senzații corporale normale (bătăile inimii, tensiune musculară ușoară) ca pe semnale de alertă, ceea ce amplifică activarea simpatică. Body scan-ul, practicat regulat, recalibrează această interpretare.</p>
<p>Conexiunea socială pozitivă activează vagalul ventral direct. Conversații față în față cu persoane în care ai încredere, contact fizic (îmbrățișări, ținutul de mână), chiar și ascultarea vocii unui prieten la telefon activează circuitele de siguranță socială descrise de Porges. Nu e metaforic. Tonul vocii umane, în special frecvențele joase și melodice, activează mușchii urechii medii inervate de nervul vag și semnalează siguranță la nivel subconștient.</p>
<h3>Faza 3 (luna a doua și după): abordări specializate</h3>
<p>Dacă după 6-8 săptămâni de practici autonome consistente somnul rămâne fragmentat și simptomele de hiperactivare persistă, merită explorată o abordare profesională orientată pe sistemul nervos.</p>
<p>Somatic Experiencing (SE), dezvoltată de Peter Levine, lucrează specific cu activarea stocată în sistemul nervos. Spre deosebire de terapia cognitivă clasică (care lucrează cu gândurile despre stres), SE lucrează cu senzațiile corporale și cu ciclurile incomplete de răspuns la stres. Principiul central e că corpul păstrează energia de mobilizare din experiențele stresante care nu au fost procesate complet, iar această energie menține sistemul nervos în alertă cronică. Procesul terapeutic ghidează descărcarea treptată a acestei energii, în ritm tolerat.</p>
<p>Suplimentele care susțin tonusul parasimpatic au un rol limitat dar pot fi utile ca adjuvante. Magneziul (300-400 mg de glicanat seara) susține relaxarea musculară și funcționarea GABA. L-teanina (200 mg seara) promovează undele alfa fără sedare. Ashwagandha (300-600 mg de extract standardizat) are date privind reducerea cortizolului și îmbunătățirea somnului în două studii randomizate controlate publicate de Langade și colaboratorii în 2019 și 2021.</p>
<p>Un dispozitiv de biofeedback HRV (disponibil ca aplicație de telefon cu senzor sau ca bandă de piept) poate transforma antrenamentul respirator într-o practică obiectivă. Vezi în timp real cum respirația îți afectează variabilitatea ritmului cardiac și înveți să maximizezi activarea vagală.</p>
<h2>Unde te lasă toate astea</h2>
<p>Recalibrarea unui sistem nervos autonom care a fost dominat de simpatic luni sau ani de zile nu se întâmplă într-un weekend. E un proces de antrenament, similar cu antrenamentul fizic: progresiv, cumulativ și dependent de consistență. Primele săptămâni pot părea frustrante, pentru că efectele sunt subtile. Dar răspunsul parasimpatic, ca un mușchi, se întărește cu fiecare repetiție.</p>
<p>Ce merită înțeles e că problema nu ești tu. Nu e lipsa de voință, nu e că nu știi să te relaxezi. E că sistemul tău nervos operează pe baza unor calibrări pe care nu le-ai ales conștient, și care s-au format ca răspunsuri legitime la circumstanțe reale. Recalibrarea înseamnă să oferi sistemului dovezi noi, repetate, că mediul actual e diferit de cel care a produs calibrarea inițială.</p>
<p>Instrumentele descrise aici nu sunt spectaculoase. Respirația, mișcarea, conexiunea, prezența corporală. Dar sunt exact instrumentele la care sistemul nervos autonom răspunde, pentru că ele furnizează tipul de informație pe care acest sistem o procesează: semnale senzoriale, ritmice, corporale. Nu e nevoie să înțelegi totul ca să începi. O sesiune de respirație diafragmatică în seara asta e un prim semnal trimis nervului vag că frâna e din nou disponibilă.</p>
