<p>Trezirea precoce repetitivă, în jurul orei 4, cu o luciditate care nu lasă loc somn, e unul dintre cele mai specifice semnale biologice ale depresiei. Cortizolul crește prematur în a doua parte a nopții, iar creierul interpretează acest semnal ca pe venirea dimineții. Dacă tiparul se repetă de câteva săptămâni, merită privit dincolo de igienă a somnului.</p>
<ul>
  <li>Trezirea precoce repetitivă (4-5 dimineața) cu imposibilitatea de a readormi e unul dintre cele mai specifice semne biologice ale depresiei</li>
  <li>Depresia perturbă arhitectura somnului prin disfuncții în sistemele de serotonină și noradrenalină, scurtând fazele profunde și modificând ciclurile REM</li>
  <li>Insomnia cu trezire precoce precede adesea conștientizarea depresiei cu săptămâni sau luni, funcționând ca un semnal de alarmă pe care mulți îl ignoră</li>
  <li>Diferența dintre insomnia primară și insomnia depresivă are markeri identificabili pe care merită să îi cunoști</li>
  <li>Screeningul PHQ-9, un chestionar simplu de 9 întrebări, poate oferi o primă orientare, accesibil oricui</li>
  <li>Tratamentul combinat (psihoterapie plus medicație) are cele mai bune rezultate, dar ordinea și alegerea depind de severitate</li>
  <li>Îmbunătățirea somnului fără adresarea depresiei subiacente produce rezultate temporare și incomplete</li>
  <li>Există intervenții comportamentale care funcționează pe ambele fronturi simultan</li>
</ul>
<p>Te trezești la 4:20 dimineața. Nu de la un zgomot, nu de la un vis. Pur și simplu, ochii se deschid și ești lucid într-un mod care nu lasă loc pentru revenirea somnului. Stai în pat și încerci. Închizi ochii, schimbi poziția, respiri adânc. Nimic. Mintea se pune în mișcare, și gândurile care vin nu sunt neutre. Sunt evaluări: ce n-ai făcut, ce ar fi trebuit să fi făcut, ce probabil nu o să meargă. La 5:30 renunți și te ridici. Ziua începe cu un deficit de energie pe care cafeaua îl maschează doar parțial.</p>
<p>Dacă această descriere e familiară și se repetă de săptămâni, nu ai de-a face cu o simplă insomnie. Există o probabilitate reală că trezirea precoce să fie un simptom al depresiei, nu o problemă de somn independentă. Distincția asta contează enorm, pentru că tratamentul e diferit și pentru că abordarea greșită poate întârzia rezolvarea cu luni.</p>
<p>Nu spun asta ca să alarmez. Spun asta pentru că, în practica clinică, trezirea precoce e unul dintre cele mai frecvent ignorate semnale ale depresiei. Mulți oameni ajung să încerce suplimente de melatonină, tehnici de igienă a somnului și aplicații de relaxare luni de zile înainte ca cineva să întrebe: "Cum te simți în general în ultima perioadă?"</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Ca să înțelegi de ce depresia te trezește la ore mici, trebuie să înțelegi ce face creierul în a doua jumătate a nopții. Somnul nu e uniform. Prima jumătate e dominată de somnul profund cu unde lente (faza N3), în care corpul face reparații fizice și consolidează memoria declarativă. A doua jumătate e dominată de somnul REM, în care creierul procesează emoțiile și consolidează memoria procedurală.</p>
<p>Tranziția de la somn profund la REM e reglată de un echilibru delicat între mai mulți neurotransmițători. Serotonina și noradrenalina scad progresiv pe parcursul nopții, permițând REM-ului să devină dominant. Acetilcolina crește, susținând visele și procesarea emoțională. Cortizolul începe să urce treptat după miezul nopții, pregătind corpul pentru trezire.</p>
<p>În depresie, acest echilibru se destabilizează în mod specific. Cercetările lui David Kupfer și Charles Reynolds de la University of Pittsburgh, publicate începând din anii 1980, au documentat un tipar consistent: la persoanele depresive, somnul REM apare mai devreme în noapte (latență REM redusă), e mai intens și mai lung, iar somnul profund e scurtat și fragmentat. Practic, creierul intră în REM prea repede și prea agresiv, comprimând somnul restaurativ.</p>
<p>Dar mecanismul trezirilor precoce e și mai specific. Arthur Spielman, în modelul său cu trei factori al insomniei (1987), a distins între factorii predispozanți, precipitanți și de menținere. În depresie, factorul precipitant e o creștere anormală a cortizolului în a doua parte a nopții. Edward Sachar și colaboratorii săi de la Columbia University au arătat încă din anii 1970 că pacienții depresivi au niveluri de cortizol nocturn cu 50-100% mai ridicate decât persoanele sănătoase. Această creștere prematură de cortizol funcționează ca un semnal de trezire pe care creierul îl interpretează ca pe venirea dimineții.</p>
<p>Serotonina joacă un rol dublu și merită înțeleasă separat. În timpul zilei, serotonina reglează dispoziția, apetitul și impulsivitatea. Noaptea, serotonina e precursorul melatoninei (lanțul triptofan, serotonină, melatonină). Când sistemul serotoninergic e disfuncțional, ambele funcții suferă: dispoziția scade ziua, iar producția de melatonină devine insuficientă sau instabilă noaptea. Nu e o coincidență că aceleași molecule sunt implicate în ambele probleme. Sunt aceleași molecule.</p>
<p>Un aspect care complică și mai mult tabloul: insomnia cu trezire precoce precede adesea depresia conștientă. Robert Perlis și echipa de la Harvard au publicat în 2006 în American Journal of Psychiatry un studiu longitudinal care a arătat că insomnia persistentă crește riscul de a dezvolta un episod depresiv major de 2-3 ori în următorul an. Dar și mai relevant, mulți pacienți raportează că tulburarea de somn a apărut cu 4-8 săptămâni înainte de a conștientiza că ceva s-a schimbat emoțional. Somnul se defectează primul. Dispoziția urmează.</p>
<p>Asta înseamnă că dacă te trezești la 4 dimineața de trei săptămâni și încă te simți "OK ziua" (poate puțin obosit, poate puțin mai iritabil, dar funcțional), nu e neapărat un argument împotriva depresiei. Poate fi pur și simplu o depresie în faza de instalare, care nu și-a atins încă intensitatea completă.</p>
<h2>Ce alimentează problema</h2>
<p>Privarea de somn rezultată din trezirile precoce creează un cerc vicios documentat. Somnul insuficient scade nivelul de serotonină disponibilă în sinapse, reduce neurogeneza în hipocamp și crește reactivitatea amigdalei. Toate aceste efecte agravează depresia, care la rândul ei agravează insomnia. Rachel Manber de la Stanford a publicat studii (2008, 2014) care arată că tratarea insomniei la pacienții depresivi îmbunătățește răspunsul la antidepresive cu 40-60%. Cercul vicios poate fi întrerupt din ambele direcții.</p>
<p>Izolarea socială se instalează insidios. Cine se trezește la 4 dimineața e obosit la 21:00, refuză ieșirile sociale, stă mai mult singur. Izolarea amplifică ruminarea, care e combustibilul principal al depresiei. Nu e un detaliu de stil de viață. E un mecanism patologic real.</p>
<p>Alcoolul, folosit uneori pentru a adormi mai ușor, suprimă somnul REM în prima parte a nopții și produce un "rebound REM" în a doua jumătate, exact acolo unde depresia deja creează probleme. Combinația agravează atât trezirile precoce, cât și intensitatea gândurilor negative care le însoțesc.</p>
<p>Autotratamentul cu suplimente de melatonină merită o mențiune separată. Melatonina exogenă ajută la reglarea orei de adormire, dar are efect minim pe trezirile precoce cauzate de cortizol crescut și disfuncție serotoninergică. Multe persoane cu depresie mascată iau melatonină luni de zile fără rezultat, ceea ce le confirmă (eronat) că "nu e nimic de făcut."</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): evaluare și fundamente comportamentale</h3>
<p>Primul pas e un screening onest. Chestionarul PHQ-9 (Patient Health Questionnaire-9) are 9 întrebări și se completează în 3 minute. E validat în sute de studii, tradus în română și disponibil gratuit online. Un scor de 10 sau peste sugerează depresie moderată și justifică o conversație cu un profesionist. Nu e un diagnostic, dar e un punct de plecare solid. Dacă obții un scor ridicat, nu îl ignora.</p>
<p>Expunerea la lumină naturală dimineața face două lucruri simultan: recalibrează ritmul circadian (util pentru insomnie) și crește producția diurnă de serotonină (util pentru dispoziție). Daniel Kripke de la UC San Diego a publicat cercetări (2005, 2011) care arată că terapia cu lumină puternică (10.000 lucși, 30 de minute dimineața) e eficientă atât în depresia sezonieră, cât și în depresia non-sezonieră, cu efecte comparabile cu antidepresivele la depresiile ușoare și moderate. Dacă nu ai acces la o lampă de luminoterapie, 30 de minute afară în primele două ore după trezire oferă 5.000-15.000 de lucși chiar și pe cer acoperit.</p>
<p>Exercițiul fizic moderat are o bază de dovezi impresionantă pentru depresie. Meta-analiza lui Schuch et al., publicată în Journal of Psychiatric Research (2016), a inclus 25 de studii controlate și a găsit un efect antidepresiv mare (effect size de 1.11), comparabil cu medicația. Nu trebuie să fie intens. 30 de minute de mers alert, de 5 ori pe săptămână, activează BDNF (factorul neurotrofic derivat din creier), crește serotonina și reduce cortizolul. Ideal dimineața sau la prânz, nu seara târziu.</p>
<p>Igiena somnului standard rămâne relevantă, dar cu o ajustare importantă: la persoanele cu trezire precoce, restricționarea timpului petrecut în pat poate fi contraintuitivă dar eficientă. Dacă te trezești la 4:30 și nu mai poți adormi, stai în pat până la 5:00, nu până la 7:00. Orele petrecute treaz în pat consolidează asocierea pat-frustrare și agravează insomnia. Arthur Spielman a demonstrat că restricția de somn (limitarea timpului în pat la numărul real de ore dormite) crește eficiența somnului în 2-3 săptămâni.</p>
<h3>Faza 2 (săptămânile 3-6): intervenție structurată</h3>
<p>Terapia cognitiv-comportamentală pentru insomnie (CBT-I) e recomandată de American College of Physicians ca primă linie de tratament, înaintea medicației. Dar la insomnia depresivă, abordarea optimă e combinarea CBT-I cu intervenții specifice pentru depresie. Colleen Carney de la Ryerson University a publicat în Sleep (2017) un studiu care arată că CBT-I administrată concomitent cu tratamentul depresiei îmbunătățește ambele condiții mai mult decât tratarea oricăreia singure.</p>
<p>Psihoterapia focalizată pe depresie (terapie cognitiv-comportamentală sau activare comportamentală) adresează mecanismele care mențin cercul vicios: ruminarea, retragerea socială, autocritica. Nu e vorba de "a vorbi despre probleme." E vorba de identificarea tiparelor cognitive și comportamentale specifice care mențin depresia activă și de înlocuirea lor sistematică.</p>
<p>Consultul psihiatric merită luat în considerare dacă scorul PHQ-9 e peste 15, dacă simptomele persistă după 6 săptămâni de intervenții comportamentale, sau dacă există gânduri recurente de inutilitate sau autodistrugere. Antidepresivele din clasa SSRI (fluoxetină, sertralină, escitalopram) au efect dual: cresc disponibilitatea serotoninei (îmbunătățind dispoziția) și, prin normalizarea ciclurilor de serotonină, tind să stabilizeze și somnul. Efectul pe somn apare de obicei în săptămânile 2-4, uneori cu o agravare tranzitorie în prima săptămână.</p>
<p>Mirtazapina merită menționată separat: e un antidepresiv cu efect sedativ pronunțat, prescris uneori specific când insomnia e simptomul dominant al depresiei. John Krystal și echipa de la Yale au studiat-o în acest context și au găsit îmbunătățiri ale somnului începând din prima săptămână.</p>
<h3>Faza 3 (luna a doua și după): optimizare</h3>
<p>Dacă tratamentul funcționează, somnul începe să se normalizeze în paralel cu dispoziția. Trezirile precoce devin mai rare, apoi dispar. Ordinea tipică e: întâi se îmbunătățește adormirea, apoi durata somnului crește, apoi calitatea subiectivă a dimineții se schimbă.</p>
<p>Suplimentarea poate susține procesul, dar nu îl înlocuiește. Omega-3 (EPA, 1-2 g zilnic) are dovezi moderate ca adjuvant în depresie, conform meta-analizei lui Liao et al. din Translational Psychiatry (2019). Vitamina D (2000-4000 UI zilnic, cu monitorizarea nivelurilor serice) e relevantă mai ales în sezonul rece, când deficitul e aproape universal la latitudinile noastre. Magneziul glicinat (300-400 mg seara) susține atât relaxarea musculară, cât și conversia triptofanului în serotonină. Niciunul dintre acestea nu e un substitut pentru terapie sau medicație la depresie moderată sau severă.</p>
<h2>Unde te lasă toate astea</h2>
<p>Poate cea mai importantă idee din tot ce s-a discutat aici e că insomnia cu trezire precoce nu e întotdeauna o problemă de somn. Uneori e fereastra prin care depresia devine vizibilă prima dată. Și dacă o tratezi ca pe o problemă de somn izolată, pierzi luni prețioase în care depresia subiacentă avansează.</p>
<p>Nu trebuie să fii sigur că ai depresie ca să acționezi. Trebuie doar să fii suficient de curios încât să completezi un PHQ-9, să observi dacă oboseala ta e însoțită de pierderea interesului, de autocritică sau de retragere, și să accepți că un consult cu un psiholog sau psihiatru nu e un semn de gravitate, ci unul de luciditate.</p>
<p>Ceea ce funcționează, în practică, e să începi cu ce poți controla: lumină dimineața, mișcare, program de somn reglat. Și să adaugi, când e nevoie, ajutorul profesionist care transformă o problemă cronică într-una rezolvabilă. Somnul și dispoziția sunt legate atât de strâns încât îmbunătățirea unuia tinde să o tragă pe cealaltă în sus. Contează doar să începi din direcția corectă.</p>
