<p>Mișcarea ajută somnul prin trei mecanisme concrete: metabolizarea cortizolului acumulat, creșterea adenozinei care construiește presiunea de somn și scăderea temperaturii centrale după efort. Dar tipul de exercițiu, ora la care îl faci și intensitatea contează la fel de mult ca faptul că te miști.</p>
<h2>Ce vei găsi în acest articol</h2>
<ul>
  <li>Cum metabolizează exercițiul fizic cortizolul și adrenalina acumulate în timpul zilei</li>
  <li>Rolul adenozinei generate de efort în construirea presiunii de somn</li>
  <li>Efectul mișcării asupra termoreglării și de ce asta contează pentru adormire</li>
  <li>Diferențele practice între cardio, antrenament de forță și yoga/stretching în raport cu somnul</li>
  <li>Fereastra critică de 2-3 ore înainte de culcare și ce se întâmplă când o ignori</li>
  <li>Cum să alegi între mișcare dimineața și mișcare seara</li>
  <li>Ce faci când ești obosit dar agitat și nu poți sta liniștit</li>
</ul>
<p>Probabil ai auzit sfatul „fă sport și vei dormi mai bine" de suficiente ori încât a început să sune ca un clișeu. Și ca multe clișee, conține un sâmbure de adevăr învelit în imprecizie. Da, exercițiul fizic îmbunătățește somnul. Dar nu orice exercițiu, nu la orice oră, și nu în orice doză. Relația dintre mișcare și somn este mai nuanțată decât o face să pară un afiș motivațional.</p>
<p>Ce vreau să explorez aici este mecanica reală din spatele acestei relații. Pentru că atunci când înțelegi de ce mișcarea ajută somnul, poți lua decizii mult mai bune despre ce tip de activitate alegi, când o programezi și cum o adaptezi în funcție de starea ta de moment. Nu e vorba despre reguli rigide, ci despre o logică biologică pe care o poți folosi flexibil.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Să începem cu cortizolul și adrenalina, pentru că aici e poate cel mai direct mecanism. În timpul unei zile obișnuite, mai ales una stresantă, corpul tău produce cortizol și catecolamine (adrenalină, noradrenalină) ca răspuns la factorii de stres. Aceste substanțe sunt utile pe moment, te ajută să fii alert, să reacționezi rapid, să faci față presiunilor. Dar dacă nu sunt metabolizate, rămân în circulație și mențin sistemul nervos simpatic activat. Seara, când ar trebui să treci pe „modul" parasimpatic de relaxare și recuperare, corpul tău încă rulează pe benzină de stres.</p>
<p>Exercițiul fizic este cel mai eficient mod de a „arde" aceste substanțe. Mișcarea face exact ceea ce cortizolul și adrenalina pregătesc corpul să facă: efort fizic intens. Când alergi, ridici greutăți sau pedalezi, consumi aceste molecule în scopul lor biologic original. După efort, nivelurile scad, iar tranziția spre starea parasimpatică devine mult mai naturală.</p>
<p>Al doilea mecanism important implică adenozina. Aceasta este o moleculă care se acumulează în creier pe măsură ce celulele nervoase consumă energie (sub formă de ATP). Cu cât ești mai activ metabolic pe parcursul zilei, cu atât mai multă adenozină se adună. Această acumulare creează ceea ce specialiștii numesc „presiune homeostatică de somn", senzația crescândă de somnolență pe măsură ce ziua avansează. Exercițiul fizic accelerează acest proces. Un antrenament moderat-intens crește consumul de ATP și, implicit, producția de adenozină. Rezultatul: o presiune de somn mai robustă seara.</p>
<p>Al treilea mecanism este termic. În timpul exercițiului, temperatura centrală a corpului crește cu 1-2 grade Celsius. După efort, corpul inițiază un proces de răcire care poate dura câteva ore. Această scădere a temperaturii centrale imită un proces natural care are loc seara, atunci când creierul semnalează corpului că se apropie timpul de somn. Scăderea temperaturii facilitează eliberarea de melatonină și promovează adormirea. Din acest motiv, momentul antrenamentului contează enorm, dar ajungem acolo.</p>
<p>Pe termen lung, exercițiul fizic regulat recalibrează ritmul circadian. Persoanele active fizic tind să aibă o amplitudine mai mare a oscilațiilor circadiene de temperatură și cortizol, adică zilele sunt mai „de zi" și nopțile sunt mai „de noapte" din perspectiva corpului. Acest contrast mai pronunțat între starea diurnă și cea nocturnă favorizează un somn mai profund și mai consolidat.</p>
<p>Acum, diferențele între tipurile de exercițiu. Antrenamentul cardiovascular (alergare, ciclism, înot, mers alert) este cel mai studiat în relație cu somnul. Efectul este consistent: cardio-ul moderat crește durata somnului profund (stadiul N3), reduce latența de adormire și scade numărul de treziri nocturne. Mecanismele dominante aici sunt metabolizarea cortizolului, creșterea adenozinei și efectul termic.</p>
<p>Antrenamentul de forță (greutăți, exerciții cu greutatea corporală, benzi elastice) are un profil ușor diferit. Crește proporția de somn profund, uneori chiar mai mult decât cardio-ul, posibil datorită necesității crescute de recuperare tisulară. Hormonul de creștere, esențial pentru repararea musculară, este eliberat predominant în timpul somnului profund N3, iar corpul pare să „solicite" mai mult somn profund după un antrenament de forță intens. Pe de altă parte, antrenamentele de forță foarte intense pot crește nivelul de cortizol post-efort mai mult decât cardio-ul moderat, ceea ce face momentul zilei și mai relevant.</p>
<p>Yoga și stretching-ul ocupă un spațiu diferit în această ecuație. Nu generează același nivel de adenozină sau efect termic ca exercițiile intense. Dar activează direct sistemul nervos parasimpatic. Respirația lentă și controlată, pozițiile susținute, focalizarea atenției reduc activitatea simpatică și promovează relaxarea. Pentru persoanele care au un nivel ridicat de activare seara (gânduri care nu se opresc, tensiune musculară, neliniște fizică), yoga sau stretching-ul blând pot fi mai utile decât un antrenament intens care ar amplifica temporar starea de activare.</p>
<h2>Ce alimentează problema</h2>
<p>Paradoxal, una dintre barierele cele mai comune în relația exercițiu-somn este tocmai lipsa de somn. Când ești obosit cronic, motivația de a face mișcare scade. Lipsă de energie, lipsă de voință, senzația că „nu am chef de nimic". Și atunci renunți la mișcare, ceea ce face somnul și mai prost, ceea ce te face și mai obosit. E un cerc vicios clasic.</p>
<p>O altă problemă frecventă este programarea neinspirată a antrenamentului. Multe persoane, din cauza programului de lucru, nu reușesc să facă mișcare decât seara târziu. Și aleg activități intense: o clasă de cycling, o sesiune de CrossFit, o alergare de 10 km. Antrenamentul se termină la 21:30, dușul la 22:00, iar la 22:30 sunt în pat cu ochii larg deschiși, cu pulsul încă ridicat, cu temperatura corporală crescută, întrebându-se de ce nu pot adormi. Fereastra critică de 2-3 ore înainte de culcare nu este o regulă arbitrară. Este timpul necesar corpului pentru ca temperatura centrală să scadă, pentru ca cortizolul post-efort să se normalizeze și pentru ca sistemul nervos să facă tranziția de la simpatic la parasimpatic.</p>
<p>Există și o problemă de „totul sau nimic". Fie antrenament complet de 60-90 de minute, fie nimic. Această mentalitate ignoră faptul că și 20-30 de minute de mers alert au un efect benefic asupra somnului. Nu trebuie să atingi un prag de intensitate sau durată pentru ca mișcarea să conteze.</p>
<h2>Ce poți face</h2>
<p><strong>Faza 1: Stabilește un nivel minim viabil (săptămânile 1-2)</strong></p>
<p>Dacă nu faci deloc mișcare regulată, nu începe cu un program ambițios de antrenament. Începe cu o plimbare de 20-30 de minute, în aer liber, preferabil dimineața sau la prânz. Acest lucru face trei lucruri simultan: metabolizează o parte din cortizolul acumulat, te expune la lumină naturală (care reglează ritmul circadian) și crește ușor temperatura centrală, inițiind ciclul termic care va facilita somnul seara.</p>
<p>Fă asta zilnic sau aproape zilnic timp de două săptămâni înainte de a adăuga ceva. Observă dacă se schimbă ceva în calitatea somnului tău. Multe persoane raportează o diferență perceptibilă doar din atât.</p>
<p><strong>Faza 2: Adaugă exercițiu structurat cu atenție la momentul zilei (săptămânile 3-6)</strong></p>
<p>Dacă ai opțiunea de a alege, dimineața (între 7 și 10) este fereastra optimă pentru exerciții de intensitate moderată-ridicată. Studiile arată că exercițiul matinal consolidează ritmul circadian, îmbunătățește alertența în timpul zilei și promovează un somn mai profund noaptea. Un beneficiu suplimentar: antrenamentul matinal crește temperatura corporală devreme în zi, ceea ce face ca scăderea termică de seară să fie mai pronunțată.</p>
<p>Dacă singurul moment disponibil este seara, adaptează tipul de exercițiu la oră. Regula orientativă: cu cât ești mai aproape de ora de culcare, cu atât intensitatea trebuie să fie mai mică. Dacă te antrenezi cu 4-5 ore înainte de somn, orice tip de exercițiu este acceptabil. Cu 2-3 ore înainte, treci la intensitate moderată. Cu mai puțin de 2 ore înainte, limitează-te la stretching, yoga blândă sau o plimbare lentă.</p>
<p>Pentru antrenamentele de forță intense, fereastra ideală este de 4-6 ore înainte de culcare. Aceasta permite suficient timp pentru ca cortizolul post-antrenament să scadă și pentru ca efectul termic să lucreze în favoarea somnului, nu împotriva lui.</p>
<p><strong>Faza 3: Gestionează starea de oboseală cu agitație (permanent)</strong></p>
<p>Există un tipar pe care mulți îl recunosc: ești epuizat fizic, dar mintea nu se oprește. Corpul vrea să se odihnească, dar sistemul nervos este blocat pe „pornit". În aceste momente, exercițiul intens ar fi contraproductiv. Ai adăuga stres fizic peste un sistem nervos deja suprasolicitat.</p>
<p>Ce funcționează: mișcări lente, repetitive, cu focalizare pe respirație. O sesiune de 15-20 de minute de stretching, cu respirații lungi (inspir pe 4 secunde, expir pe 6-8 secunde), activează nervul vag și inițiază răspunsul parasimpatic. Yoga restaurativă, unde menții poziții pasive susținute de perne sau pături timp de 3-5 minute fiecare, este excepțional de eficientă în acest context.</p>
<p>O altă opțiune: mersul lent, fără destinație, fără podcast, fără muzică. Doar mișcarea ritmică a pașilor. Acest tip de mișcare monotonă are un efect calmant asupra sistemului nervos care depășește efortul fizic minimal pe care îl implică.</p>
<p><strong>Faza 4: Suplimente care susțin relația mișcare-somn</strong></p>
<p>Magneziul este relevant aici din două perspective. Intervine în relaxarea musculară post-antrenament și susține calitatea somnului. Multe persoane active fizic au un necesar crescut de magneziu din cauza pierderilor prin transpirație. 200-400 mg de magneziu glicinat sau citrat seara pot acoperi acest deficit.</p>
<p>Tart cherry juice (sucul de vișine amare) este unul dintre puținele suplimente alimentare cu studii specifice pe combinația exercițiu-somn. Conține melatonină naturală și compuși antiinflamatori. Dozele studiate sunt de aproximativ 240 ml, consumat dimineața și seara.</p>
<p>Glicina (3 g înainte de culcare) a arătat în câteva studii mici că poate îmbunătăți calitatea subiectivă a somnului și reduce temperatura centrală, ceea ce ar putea fi util mai ales în serile post-antrenament.</p>
<h2>Unde te lasă toate acestea</h2>
<p>Relația dintre mișcare și somn nu este o ecuație simplă de tipul „mai multă mișcare egal somn mai bun". Este mai degrabă o relație de calibrare: tipul potrivit, la momentul potrivit, în doza potrivită. Și „potrivit" variază de la persoană la persoană, de la zi la zi. Ceea ce rămâne constant este direcția generală: un corp care se mișcă regulat doarme mai bine decât unul sedentar. Nu spectaculos mai bine peste noapte, ci progresiv, cumulativ, în mod sustenabil. Începe de unde ești, nu de unde crezi că ar trebui să fii, și ajustează pe parcurs. Corpul tău îți va spune, prin calitatea somnului, dacă ești pe drumul bun.</p>
