<p>Dacă dormi 7-8 ore și te trezești constant obosit, există o cauză care afectează 15-30% din bărbații adulți și care poate trece nediagnosticată ani de zile. Mecanismul e simplu: musculatura căilor respiratorii se relaxează în somn, respirația se oprește zeci sau sute de ori pe noapte, iar creierul intervine de fiecare dată cu o micro-trezire de care nu ești conștient.</p>
<ul>
  <li>Apneea obstructivă de somn înseamnă sute de micro-opriri ale respirației pe noapte, fiecare urmată de o micro-trezire de care persoana nu e conștientă</li>
  <li>Creierul intervine de fiecare dată ca să redeschidă căile respiratorii, dar fiecare intervenție fragmentează somnul profund și REM</li>
  <li>Sforăitul puternic și neregulat e semnul cel mai vizibil, dar oboseala cronică "fără explicație" e simptomul cu care trăiesc cei mai mulți ani de zile fără diagnostic</li>
  <li>Obezitatea e factorul de risc principal, dar anatomia gâtului, vârsta și poziția de somn joacă roluri independente</li>
  <li>Consecințele pe termen lung depășesc oboseala: hipertensiune, boli cardiovasculare, rezistență la insulină, probleme cognitive</li>
  <li>Polisomnografia (studiul de somn în laborator) rămâne standardul de diagnostic, dar există și variante simplificate la domiciliu</li>
  <li>Tratamentul cu CPAP funcționează din prima noapte, dar aderența pe termen lung e problema reală</li>
  <li>Scăderea în greutate, poziția de somn și exercițiile orofaringiene pot reduce severitatea fără echipament</li>
</ul>
<p>Dacă dormi 7 sau 8 ore pe noapte și te trezești obosit în mod constant, există tendința naturală să cauți problema în calitatea somnului, în stres, în alimentație. Și uneori acolo e. Dar există o cauză care afectează estimativ 15-30% din bărbații adulți și 10-15% din femeile adulte (conform datelor publicate de Benjafield și colaboratorii în Lancet Respiratory Medicine, 2019), pe care majoritatea o poartă ani de zile fără să o suspecteze: apneea obstructivă de somn.</p>
<p>Mecanismul central e simplu de înțeles. În timpul somnului, musculatura care menține căile respiratorii deschise se relaxează. La majoritatea oamenilor, relaxarea e suficientă, aerul trece, somnul continuă. La cei cu apnee, relaxarea duce la îngustarea sau închiderea completă a căii respiratorii la nivelul faringelui. Respirația se oprește, uneori pentru 10 secunde, alteori pentru 30 sau mai mult. Nivelul de oxigen din sânge scade. Iar creierul, detectând problema, declanșează o micro-trezire ca să reactiveze musculatura și să redeschidă pasajul. Persoana nu se trezește complet (de cele mai multe ori nici nu știe că s-a întâmplat ceva), dar somnul e scos din faza profundă în care se afla. Și ciclul se reia: adormire, relaxare, obstrucție, micro-trezire. De zeci sau sute de ori pe noapte.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Imaginea de ansamblu arată cam așa. Corpul petrece ore în pat, ochii sunt închiși, persoana crede că doarme. Dar creierul nu parcurge niciodată un ciclu complet de somn fără întrerupere. E ca și cum ai încerca să bei apă dintr-un pahar pe care cineva îl lovește din mână la fiecare câteva înghițituri. Tehnic, bei apă. Practic, nu te hidratezi niciodată cum trebuie.</p>
<p>Somnul are o arhitectură precisă. Un ciclu complet durează aproximativ 90 de minute și trece prin faze specifice: somn ușor (N1, N2), somn profund (N3, unde corpul face reparații celulare, eliberează hormon de creștere și consolidează sistemul imunitar) și somn REM (unde se consolidează memoria și se procesează emoțional ziua). Fiecare micro-trezire provocată de un eveniment de apnee resetează ciclul. Somnul profund și REM sunt cele mai afectate, pentru că apar în porțiunile mai vulnerabile ale ciclului.</p>
<p>Numărul de opriri respiratorii pe oră poartă numele de index de apnee-hipopnee (AHI). Sub 5 pe oră e considerat normal. Între 5 și 15 e apnee ușoară. Între 15 și 30 e moderată. Peste 30 e severă. Un lucru care surprinde pe mulți: la un AHI de 30, respirația se oprește de 240 de ori într-o noapte de 8 ore. Fiecare oprire e urmată de o micro-trezire. Creierul lucrează efectiv în ture scurte, fără să ajungă niciodată în zonele de somn care contează cel mai mult.</p>
<p>Consecințele imediate sunt cele pe care persoana le simte în fiecare zi: oboseala cronică, somnolența diurnă, dificultate de concentrare, iritabilitate. Ceea ce le face insidioase e că se instalează treptat. Mulți oameni nu știu că au o problemă pentru că nu au un punct de referință: nu își amintesc cum e să dormiți bine. Atribuie oboseala vârstei, stresului, volumului de muncă. "Așa sunt eu, nu am fost niciodată matinal" e o frază frecventă la persoane cu apnee nediagnosticată.</p>
<p>Consecințele pe termen lung sunt cele care fac apneea o problemă medicală serioasă, nu doar o neplăcere. Fiecare episod de apnee produce o scădere a oxigenului sanguin (hipoxemie intermitentă) urmată de o reoxigenare bruscă. Acest ciclu de hipoxie-reoxigenare e un stres oxidativ repetat care afectează pereții vaselor de sânge. Un studiu de referință publicat de Marin și colaboratorii în Lancet în 2005 a urmărit peste 1.600 de bărbați timp de 10 ani și a găsit că cei cu apnee severă netratată aveau un risc de 3 ori mai mare de evenimente cardiovasculare fatale comparativ cu cei fără apnee.</p>
<p>Mecanismul e direct: fiecare micro-trezire activează sistemul nervos simpatic (aceeași ramură care răspunde la stres acut). Frecvența cardiacă crește, tensiunea arterială urcă, adrenalina și cortizolul se eliberează. Repetat de sute de ori pe noapte, luni și ani la rând, acest stres simpatic cronic produce hipertensiune arterială (prezentă la 50-60% din persoanele cu apnee severă), crește riscul de fibrilație atrială, accident vascular cerebral și insuficiență cardiacă.</p>
<p>Legătura cu metabolismul e la fel de clară. Fragmentarea somnului profund reduce sensibilitatea la insulină. Tasali și colaboratorii de la Universitatea din Chicago au demonstrat în 2008 că suprimarea selectivă a somnului profund la voluntari tineri și sănătoși a redus toleranța la glucoză la un nivel comparabil cu cel al pre-diabetului, în doar 3 nopți. La persoanele cu apnee care pierd somnul profund cronic, rezistența la insulină devine un companion metabolic de lungă durată. Asocierea cu diabetul de tip 2 e bidirecțională: apneea crește riscul de diabet, iar diabetul agravează neuropatia care afectează controlul muscular al căilor respiratorii.</p>
<h2>Ce alimentează problema</h2>
<p>Factorul de risc cel mai puternic rămâne obezitatea. Nu prin mecanismul pe care mulți îl presupun (greutatea pe piept care împiedică respirația), ci prin depunerea de țesut adipos la nivelul faringelui și al bazei limbii. Aceste depuneri îngustează fizic calea aeriană. Când musculatura se relaxează în somn, spațiul deja redus devine insuficient. Un studiu publicat de Peppard și colaboratorii în JAMA în 2000 a arătat că o creștere în greutate de 10% crește riscul de apnee moderată-severă cu 600%. Relația e și inversă: apneea însăși favorizează creșterea în greutate prin perturbarea hormonilor leptină și grelină, care reglează foamea și sațietatea.</p>
<p>Anatomia joacă un rol independent de greutate. Un maxilar mic sau retrognație (mandibula poziționată posterior), o limbă proporțional mare, amigdale hipertrofiate sau o circumferință crescută a gâtului (peste 43 cm la bărbați, peste 38 cm la femei) cresc riscul chiar la persoane normoponderale. Există oameni slabi cu apnee severă, și această categorie e cea mai frecvent nediagnosticată, tocmai pentru că nu corespund profilului clasic.</p>
<p>Vârsta contribuie prin pierderea progresivă a tonusului muscular faringian. După 50 de ani, prevalența apneei crește substanțial la ambele sexe. La femei, tranziția hormonală de la menopauză reduce efectul protector al progesteronului asupra tonusului muscular respirator, ceea ce explică de ce riscul femeilor se apropie de cel al bărbaților după menopauză.</p>
<p>Poziția de somn contează mai mult decât pare. În decubit dorsal (pe spate), gravitația trage limba și țesuturile moi posterior, îngustând calea aeriană. Mulți oameni au apnee exclusiv pozițională: AHI-ul lor pe spate poate fi de 25, iar pe o parte de 5. Alcoolul și sedativele agravează situația prin relaxarea suplimentară a musculaturii faringiene. Un pahar de vin înainte de culcare poate transforma un sforăit benign într-un episod de apnee la cineva care altfel nu ar avea probleme.</p>
<h2>Ce se poate face concret</h2>
<h3>Faza 1 (săptămânile 1-2): recunoaștere și măsuri imediate</h3>
<p>Primul pas e să consideri posibilitatea. Dacă ai sforăit puternic, neregulat (cu pauze urmate de reluări zgomotoase ale respirației), oboseală cronică disproporționată față de orele dormite, treziri cu senzație de gură uscată sau dureri de cap matinale, apneea merită investigată. Un partener de pat e adesea sursa cea mai fiabilă de informație: persoana cu apnee nu își aude propriul sforăit și nu e conștientă de pauzele respiratorii.</p>
<p>Poziția de somn e intervenția cu efect imediat și cost zero. Dormitul pe o parte (lateral) reduce colapsul faringian la mulți oameni. O minge de tenis cusută într-un buzunar pe spatele tricoului de noapte e un truc vechi dar funcțional: face poziția pe spate suficient de inconfortabilă încât corpul se întoarce instinctiv pe o parte. Există și perne speciale de poziționare, dar principiul e același.</p>
<p>Evitarea alcoolului cu 3-4 ore înainte de culcare și a sedativelor (inclusiv antihistaminice cu efect sedativ) reduce frecvența și severitatea episoadelor. Menținerea unei ore de culcare regulate ajută și ea: privarea de somn crește pragul de trezire, ceea ce paradoxal face episoadele de apnee mai lungi și mai severe (creierul obosit întârzie reacția de micro-trezire, iar pauzele respiratorii se prelungesc).</p>
<h3>Faza 2 (săptămânile 3-8): diagnostic și intervenții structurate</h3>
<p>Diagnosticul propriu-zis necesită o evaluare obiectivă. Polisomnografia (PSG) în laborator rămâne standardul de aur: monitorizarea simultană a activității cerebrale, mișcării ochilor, tonusului muscular, fluxului respirator, saturației de oxigen și ritmului cardiac pe parcursul unei nopți întregi. Oferă date complete și un AHI precis. Alternativa mai accesibilă e poligrafia respiratorie la domiciliu, un dispozitiv simplificat care măsoară fluxul respirator, efortul respirator și saturația de oxigen. Nu e la fel de detaliată, dar e suficientă pentru diagnosticul apneei moderate și severe, și poate fi făcută în confortul propriului pat.</p>
<p>În paralel cu evaluarea medicală, exercițiile orofaringiene (miofuncționale) merită începute. Acestea întăresc musculatura limbii, a palatului moale și a faringelui. Gândește-te la ele ca la fizioterapie pentru gât. Un studiu randomizat publicat de Guimarães și colaboratorii în American Journal of Respiratory and Critical Care Medicine în 2009 a arătat că 3 luni de exerciții orofaringiene zilnice au redus AHI-ul cu 39% și circumferința gâtului cu peste un centimetru la pacienții cu apnee moderată. Exercițiile includ presarea limbii pe cerul gurii și menținerea timp de câteva secunde, mișcări laterale ale mandibulei și exerciții de înghițire. Durează 15-20 de minute pe zi. Nu înlocuiesc CPAP-ul la apneea severă, dar la forme ușoare și moderate pot face diferența singure.</p>
<p>Scăderea în greutate, acolo unde e cazul, rămâne intervenția cu cel mai mare potențial pe termen lung. Chiar și o reducere de 10-15% din greutate poate scădea AHI-ul substanțial. Studiul lui Peppard din JAMA citat mai sus a arătat și reversul: o scădere de 10% în greutate a redus AHI-ul cu 26%. Nu e un rezultat instantaneu, dar e unul durabil.</p>
<h3>Faza 3 (luna a doua și după): tratament specific și ajustare</h3>
<p>CPAP-ul (continuous positive airway pressure) rămâne tratamentul de referință pentru apneea moderată și severă. Funcționează printr-un mecanism simplu: un aparat mic de lângă pat generează un flux continuu de aer la presiune controlată, livrat printr-o mască nazală sau facială. Presiunea menține calea aeriană deschisă mecanic, prevenind colapsul. Efectul e imediat: prima noapte cu CPAP produce adesea o îmbunătățire pe care persoana o descrie ca revelatorie. Mulți spun că nu au dormit atât de bine de ani de zile.</p>
<p>Problema CPAP-ului nu e eficacitatea, ci aderența. Studiile arată că 30-50% din pacienți renunță sau folosesc aparatul inconsistent în primul an. Masca poate fi inconfortabilă, aerul uscat irită mucoasele, zgomotul aparatului deranjează, și există o componentă psihologică reală de a dormi cu un echipament pe față. Câteva lucruri ajută: un umidificator integrat (majoritatea aparatelor moderne îl au), testarea mai multor tipuri de măști până la găsirea celei potrivite, și o perioadă de acomodare de 2-3 săptămâni în care disconfortul scade progresiv. Aparatele auto-CPAP (APAP) care ajustează presiunea în timp real sunt mai bine tolerate decât cele cu presiune fixă.</p>
<p>Dispozitivele de avansare mandibulară (MAD) sunt o alternativă pentru apneea ușoară-moderată sau pentru persoanele care nu tolerează CPAP-ul. Sunt dispozitive dentare personalizate care poziționează mandibula ușor anterior, mărind spațiul faringian. Eficacitatea e inferioară CPAP-ului, dar aderența e superioară: fiind mai puțin intruzive, oamenii le folosesc mai constant.</p>
<p>În cazuri selectate, intervenția chirurgicală poate fi o opțiune. Uvulopalatofaringoplastia (UPPP) lărgește calea aeriană prin îndepărtarea țesutului în exces. Chirurgia de avansare maxilo-mandibulară repoziționează structurile osoase. Rezultatele variază și selecția pacienților e importantă. Chirurgia nu e un prim pas, ci o opțiune pentru cazurile în care tratamentele conservative au eșuat sau anatomia impune.</p>
<h2>Unde te lasă toate astea</h2>
<p>Apneea de somn are o particularitate care o face diferită de alte cauze ale somnului prost: nu o poți rezolva singur prin ajustări comportamentale. Poți reduce severitatea (poziție, greutate, alcool), dar diagnosticul și tratamentul necesită o evaluare medicală. Asta nu e un motiv de amânare, ci un motiv de acțiune. Un consult la un specialist în medicina somnului și o polisomnografie pot transforma ani de oboseală inexplicabilă într-un diagnostic clar cu un tratament care funcționează.</p>
<p>Pașii comportamentali din primele săptămâni (poziția laterală, evitarea alcoolului seara, exercițiile orofaringiene) sunt lucruri pe care le poți începe imediat și care produc efecte reale, chiar dacă nu înlocuiesc evaluarea completă. Mulți oameni observă o îmbunătățire a somnului din prima săptămână doar prin schimbarea poziției.</p>
<p>Cel mai greu pas, paradoxal, nu e tratamentul. E acceptarea faptului că somnul pe care îl consideri normal nu e de fapt somn real. Când ai trăit ani de zile cu fragmentare nocturnă pe care nu o percepi, oboseala devine linia de bază. Prima noapte cu respirație neîntreruptă, fie că vine de la CPAP, de la scădere în greutate sau de la un dispozitiv dentar, recalibrează întreaga percepție. Și de acolo, lucrurile devin mai clare.</p>
