<p>Histamina este unul dintre cele mai puternice semnale de veghe din creier, iar o parte din ea vine direct din ce ai în farfurie seara. Dacă nopțile tale variază imprevizibil, cu unele excelente și altele inexplicabil proaste, legătura s-ar putea să fie în cina, nu în stres.</p>
<ul>
  <li>Histamina e unul dintre principalii neurotransmițători care mențin starea de veghe, iar antihistaminicele produc somnolență exact prin blocarea acestui efect</li>
  <li>Intoleranța la histamină apare când corpul nu descompune histamina suficient de repede, de obicei din cauza deficitului de enzimă DAO (diaminoxidază)</li>
  <li>Alimentele bogate în histamină consumate seara (brânză maturată, vin roșu, mezeluri, pește conservat, alimente fermentate) pot produce insomnie prin creșterea nivelului cerebral de histamină în orele critice</li>
  <li>Mastocitele, celulele imune care stochează și eliberează histamină, pot deveni hiperactive în condiții de stres, infecții cronice sau SIBO</li>
  <li>Conexiunea histamină-somn explică de ce unii oameni dorm excelent câteva nopți și groaznic altele, aparent fără motiv, până când se uită la ce au mâncat</li>
  <li>O dietă scăzută în histamină timp de 2-3 săptămâni e cel mai fiabil test de diagnostic, mai informativ decât majoritatea analizelor de sânge</li>
  <li>Suplimentele de DAO luat înainte de mese, vitamina C și quercetina pot susține gestionarea histaminei, dar funcționează cel mai bine după ce dietar ai redus deja încărcătura</li>
  <li>Intoleranța la histamină nu e o alergie clasică și nu apare pe testele standard de alergologie, motiv pentru care rămâne frecvent nediagnosticată</li>
</ul>
<p>Dacă ai nopți inexplicabil diferite una de alta, unele în care adormi în zece minute și dormi solid și altele în care stai în pat cu mintea agitată, inima care bate puțin mai tare și un senzație difuză de disconfort fără o cauză clară, există o posibilitate pe care merită să o explorezi. Nu stresul (deși contribuie), nu cafeina (deși și ea contează), ci ceva mult mai subtil: ce ai mâncat la cină.</p>
<p>Nu vorbesc despre mâncare grea sau zahăr. Vorbesc despre histamină, o moleculă pe care corpul tău o produce natural și pe care o primești și din alimente. În cantități normale, histamina e esențială. În exces, în special seara, poate fi exact lucrul care te ține treaz fără să știi de ce.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Histamina e cel mai cunoscută în contextul alergiilor: strănuți, îți curge nasul, iei un antihistaminic. Dar rolul ei în corp e mult mai larg decât răspunsul alergic. În creier, histamina funcționează ca neurotransmițător excitator, unul dintre cele mai puternice semnale de veghe pe care le avem.</p>
<p>Neuronii histaminergici se află în nucleul tuberomamilar al hipotalamusului și proiectează spre aproape întregul cortex cerebral. În timpul zilei, acești neuroni sunt activi și eliberează histamină constant, menținând alerta și focusul. În timpul somnului, activitatea lor se oprește aproape complet. Thakkar, publicând în 2011 în Sleep Medicine Reviews, a descris histamina ca "gardianul trezirii": atâta timp cât histamina e prezentă în cantități suficiente în creier, somnul nu se poate instala normal.</p>
<p>Asta explică un lucru pe care mulți îl știu empiric fără să înțeleagă mecanismul: antihistaminicele produc somnolență. Difenhidramina (Benadryl), care traversează bariera hemato-encefalică, blochează receptorii H1 din creier și reduce semnalul de veghe al histaminei. Somnolența nu e un efect secundar accidental. E consecința directă a blocării unui neurotransmițător de veghe.</p>
<p>Acum vine partea interesantă. Histamina din creier nu provine doar din producția locală a neuronilor histaminergici. Histamina periferică, adică cea din intestin și din mastocite, poate influența indirect nivelurile cerebrale. Mecanismul nu e simplu (histamina periferică nu traversează ușor bariera hemato-encefalică), dar histidina, aminoacidul precursor al histaminei, traversează fără probleme. Un nivel ridicat de histamină în sânge crește disponibilitatea histidinei pentru creier, iar neuronii locali pot produce mai multă histamină.</p>
<p>Intoleranța la histamină apare când ritmul de acumulare depășește ritmul de degradare. În mod normal, histamina din alimente e descompusă în intestin de enzima diaminoxidază (DAO) înainte de a fi absorbită. DAO e produsă de celulele mucoasei intestinale și funcționează ca un filtru: cât timp e prezentă în cantități suficiente, histamina alimentară nu ajunge în circulație în concentrații problematice.</p>
<p>Dar mai mulți factori pot reduce activitatea DAO. Inflamația intestinală (de la SIBO, candidoză, boala celiacă sau alte cauze) deteriorează mucoasa și reduce producția de DAO. Anumite medicamente, inclusiv antiinflamatoare nesteroidiene, unele antibiotice și unele antidepresive, inhibă DAO. Deficiențele de vitamina B6, zinc, cupru și vitamina C scad activitatea enzimatică. Și există o componentă genetică: polimorfisme ale genei AOC1 (gena DAO) pot produce variante enzimatice cu activitate redusă.</p>
<p>Când DAO e insuficientă, histamina din alimente ajunge în sânge. Efectele sunt variate și adesea confuze: dureri de cap, flush facial, congestie nazală, prurit, palpitații, crampe abdominale, diaree. Și insomnie. Un studiu publicat în 2007 în American Journal of Clinical Nutrition de Maintz și Novak a descris intoleranța la histamină ca un sindrom cu prevalență estimată la 1-3% din populație, deși autorii au sugerat că cifra reală e probabil mai mare din cauza subdiagnosticării.</p>
<p>Ce face legătura cu somnul deosebit de insidioasă e timing-ul. Cina e de obicei cea mai complexă masă a zilei și cea mai probabil să conțină alimente bogate în histamină. Brânză maturată, vin roșu, mezeluri uscate, pește afumat sau conservat, roșii, spanac, avocado, alimente fermentate (varză murată, kimchi, kombucha). O masă care din perspectivă nutrițională arată excelentă poate fi o bombă de histamină pentru o persoană cu DAO insuficientă. Iar efectul apare tocmai când te pregătești să dormi, la 2-4 ore după masă.</p>
<p>Mastocitele adaugă un alt nivel de complexitate. Aceste celule imune, prezente în intestin, piele, căi respiratorii și creier, stochează histamină și o eliberează ca răspuns la diverse semnale: alergeni, stres, infecții, toxine. În sindromul de activare mastocitară (MCAS), mastocitele devin hiperreactive și eliberează histamină și alți mediatori în mod disproporționat față de stimul. O persoană cu MCAS poate avea nopți proaste declanșate de stres, de schimbări de temperatură, de alimente care la altcineva nu produc niciun efect.</p>
<p>SIBO (supracreșterea bacteriană în intestinul subțire) e un alt contributor frecvent. Bacteriile din SIBO produc histamină ca produs metabolic. O persoană cu SIBO poate avea niveluri crescute de histamină independent de ce mănâncă, pur și simplu pentru că flora bacteriană dezechilibrată generează histamină în exces. Asta explică de ce unii oameni au insomnie cronică care nu răspunde la nicio modificare dietetică până când SIBO-ul nu e tratat.</p>
<h2>Ce alimentează problema</h2>
<p>Acumularea de histamină e un fenomen cu prag. Nu funcționează ca o alergie clasică, unde un singur aliment produce un răspuns imediat și clar. Histamina se adună. Poți tolera brânză maturată la prânz, dar dacă adaugi și vin la cină și ai avut o zi stresantă (stresul activând mastocitele), totalul depășește capacitatea DAO și simptomele apar. A doua zi, cu aceeași brânză dar fără vin și fără stres, ești sub prag și dormi bine.</p>
<p>Acest efect de "pahar care se umple" face diagnosticul extrem de dificil. Oamenii nu pot corela un aliment specific cu insomnia pentru că nu e un aliment specific. E totalul dintr-o zi. Și totalul variază de la zi la zi.</p>
<p>Alcoolul merită atenție specială. Vinul roșu nu doar conține histamină, ci inhibă și DAO, combinând două mecanisme: crește încărcătura și reduce capacitatea de procesare. Asta explică de ce unii oameni reacționează disproporționat la un singur pahar de vin seara, cu flush, congestie nazală și insomnie. Nu e o "sensibilitate la alcool." E un efect histaminic dublu.</p>
<p>Ciclul menstrual la femei influențează toleranța la histamină. Estradiolul stimulează mastocitele și crește eliberarea de histamină, în timp ce progesteronul are efect stabilizator. În faza luteală târzie (zilele dinaintea menstruației), când estradiolul e ridicat și progesteronul scade, toleranța la histamină e la minim. Multe femei raportează insomnie premenstruală care răspunde parțial la o dietă scăzută în histamină în acele zile.</p>
<p>Stresul cronic menține cortizolul crescut, care inițial suprimă inflamația dar pe termen lung destabilizează mastocitele și crește permeabilitatea intestinală (permițând mai multă histamină să ajungă în circulație). Paradoxal, perioadele de relaxare după stres intens pot produce o eliberare masivă de histamină (fenomenul "let-down"), explicând de ce unii oameni dorm cel mai prost în prima noapte de vacanță.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-3): dieta de eliminare</h3>
<p>Cel mai informativ lucru pe care îl poți face e o dietă scăzută în histamină timp de 2-3 săptămâni. Nu e o dietă permanentă și nu e o dietă de slăbire. E un test diagnostic. Dacă simptomele (inclusiv calitatea somnului) se îmbunătățesc vizibil, ai o informație valoroasă. Dacă nu se schimbă nimic, histamina alimentară probabil nu e problema ta principală.</p>
<p>Alimente de evitat în aceste 2-3 săptămâni: brânzuri maturate, mezeluri și cărnuri procesate, pește conservat sau afumat, alimente fermentate (varză murată, miso, kimchi, kombucha, kefir), oțet (cu excepția oțetului de mere proaspăt), roșii, spanac, avocado, banane foarte coapte, citrice în cantități mari, vin, bere, ciocolată. Această listă pare lungă, dar restul alimentelor rămâne disponibil: carne proaspătă, pește proaspăt gătit imediat, ouă proaspete, majoritatea legumelor, orez, cartofi, fructe proaspete (cu excepția celor menționate).</p>
<p>Un principiu important: prospețimea contează enorm. Histamina se acumulează în alimente pe măsură ce bacteriile le descompun. Un piept de pui gătit imediat după cumpărare are histamină minimă. Același piept de pui gătit acum trei zile și ținut în frigider are de câteva ori mai multă. Gătirea în cantități mici și consumul imediat reduce semnificativ încărcătura histaminică.</p>
<p>Mută cina cu cel puțin 3 ore înainte de culcare și fă-o cât mai simplă posibil. Carne proaspătă gătită simplu, legume gătite (gătirea reduce parțial histamina în unele alimente) și o sursă de carbohidrați neproblematici (orez, cartofi dulci). Evită combinațiile complexe cu multe ingrediente, care fac imposibilă identificarea sursei dacă simptomele apar.</p>
<p>Ține un jurnal în aceste săptămâni: ce ai mâncat, la ce oră, cum ai dormit. După 2-3 săptămâni, reintroduce câte un aliment suspect pe zi și observă efectul. Asta îți permite să identifici ce tolerezi și ce nu, pentru că intoleranța la histamină nu înseamnă că trebuie să elimini totul permanent.</p>
<h3>Faza 2 (săptămânile 4-6): optimizarea funcției DAO și a sănătății intestinale</h3>
<p>Dacă dieta de eliminare a produs rezultate, pasul următor e să susții capacitatea corpului de a procesa histamina, nu doar să reduci încărcătura.</p>
<p>Probioticele necesită atenție. Nu toate tulpinile sunt egale în contextul histaminei. Lactobacillus casei, L. delbrueckii și L. bulgaricus produc histamină. L. rhamnosus, L. plantarum și Bifidobacterium longum tind să o degradeze sau să stabilizeze mastocitele. Alege probioticele în funcție de tulpini, nu de numărul de CFU de pe etichetă.</p>
<p>Reducerea inflamației intestinale prin eliminarea alimentelor la care ești sensibil (glutenul și lactatele sunt cele mai frecvente, dar nu singurele), prin gestionarea stresului și prin asigurarea unui tranzit intestinal regulat susține producția naturală de DAO.</p>
<p>Dacă suspectezi SIBO (balonare după mese, gaze excesive, alternanță constipație-diaree), un test de respirație cu lactuloză sau glucoză poate confirma sau infirma. Tratamentul SIBO-ului poate reduce dramatic nivelurile de histamină și poate îmbunătăți somnul indirect.</p>
<p>Activitatea fizică moderată regulată (plimbări, înot, yoga) reduce cortizolul și stabilizează mastocitele. Exercițiul intens, în special pe căldură, poate paradoxal să crească eliberarea de histamină și să agraveze simptomele, deci observă dacă există o corelație între antrenamentele intense și nopțile proaste.</p>
<h3>Faza 3 (luna a doua): suplimente specifice</h3>
<p>Enzima DAO exogenă (disponibilă ca supliment, de obicei 10.000-20.000 HDU per capsulă) luată cu 15-20 de minute înainte de mese poate compensa deficitul enzimatic. Nu rezolvă cauza, dar reduce simptomele asociate alimentelor bogate în histamină. E deosebit de util când mănânci în oraș sau în situații în care nu poți controla complet ingredientele. Un studiu pilot din 2019 publicat în Journal of Psychopharmacology de Izquierdo-Casas și colegii a arătat îmbunătățirea simptomelor la pacienții cu deficit de DAO după suplimentare.</p>
<p>Vitamina C (1000-2000 mg pe zi, împărțită în două doze) susține degradarea histaminei și stabilizează mastocitele. Clemetson, publicând în Journal of Nutrition încă din 1980, a demonstrat că vitamina C accelerează degradarea histaminei prin oxidare. E o intervenție sigură și ieftină.</p>
<p>Quercetina (500-1000 mg pe zi, luată cu mese) stabilizează membrana mastocitelor și reduce eliberarea de histamină. Efectul e preventiv, nu curativ: funcționează cel mai bine luată regulat, nu ca răspuns la simptome. Ozsoy-Sacan și colegii au arătat în mai multe studii că quercetina inhibă degranularea mastocitară in vitro și în modele animale. La oameni, datele sunt mai limitate dar direcția e consistentă.</p>
<p>Vitamina B6 (forma activă P5P, 25-50 mg pe zi) e cofactor pentru DAO. Dacă deficitul de B6 contribuie la activitatea DAO scăzută, suplimentarea poate îmbunătăți capacitatea enzimatică în 2-4 săptămâni.</p>
<h2>Unde te lasă toate astea</h2>
<p>Intoleranța la histamină nu e o etichetă pe care să ți-o pui și să o porți. E o informație despre cum funcționează digestia ta în acest moment, informație care se poate schimba pe măsură ce sănătatea intestinală se îmbunătățește, stresul scade și enzimele își revin.</p>
<p>Dacă experimentul de 2-3 săptămâni cu dieta scăzută în histamină produce o diferență clară în calitatea somnului, ai găsit ceva valoros. Nu înseamnă că trebuie să mănânci restrictiv tot restul vieții. Înseamnă că știi acum un factor pe care îl poți gestiona, mai ales seara, mai ales în perioadele de stres sau în jurul menstruației.</p>
<p>Dacă nu produce nicio diferență, ai eliminat o ipoteză și poți continua să cauți în altă parte fără să te întrebi dacă nu cumva brânza aceea de la cină e problema. Uneori, cel mai util răspuns e unul negativ, pentru că îți permite să te concentrezi pe ce contează cu adevărat în cazul tău.</p>
