<p>Un hormon numit vasopresină reduce în mod normal producția de urină pe timp de noapte cu aproape 50%. Dacă acest mecanism slăbește, sau dacă altceva crește volumul de urină nocturnă, vezica se umple înainte ca somnul să-și termine ciclurile. Iar cauzele depășesc cu mult cantitatea de apă băută seara.</p>
<ul>
  <li>Nicturie înseamnă trezirea de cel puțin o dată pe noapte ca să urinezi, iar de la două ori în sus, impactul asupra calității somnului devine măsurabil</li>
  <li>Rinichii nu filtrează la fel toată ziua: un hormon numit vasopresină (ADH) reduce producția de urină noaptea, iar scăderea lui cu vârsta e una din cauzele principale</li>
  <li>Lichidele consumate seara sunt doar o parte din ecuație, și adesea nu cea mai importantă</li>
  <li>Prostata mărită la bărbați și vezica hiperactivă la femei sunt cauze frecvente care necesită abordări diferite</li>
  <li>Diabetul (inclusiv cel nediagnosticat), insuficiența cardiacă și apneea de somn pot produce nicturie prin mecanisme pe care puțini le bănuiesc</li>
  <li>Diureticele și alte medicamente luate seara pot fi mutate dimineața cu efect imediat</li>
  <li>Exercițiile pentru musculatura pelviană funcționează și la bărbați, nu doar la femei</li>
  <li>Când nicturie apare brusc și e însoțită de sete intensă sau pierdere în greutate, investigarea medicală devine urgentă</li>
</ul>
<p>Mersul la baie o dată pe noapte pare un inconvenient minor. Și pentru mulți chiar e. Dar când devii două, trei, patru ori, situația se schimbă fundamental. Nu mai e vorba doar de inconfort. Somnul se fragmentează în bucăți prea scurte ca să permită cicluri complete de somn profund și REM, iar a doua zi arată în consecință: oboseală, iritabilitate, dificultate de concentrare.</p>
<p>Un studiu epidemiologic din 2003 condus de Coyne și colaboratorii, publicat în BJU International, a estimat că nicturie afectează aproape 50% din adulții peste 50 de ani și circa 70% din cei peste 70. Dar nu e exclusiv o problemă a vârstnicilor. Persoane de 30-40 de ani cu diabet incipient, anxietate sau obiceiuri de hidratare neadaptate se trezesc și ele de două ori pe noapte fără să înțeleagă de ce. Iar motivul pentru care mulți nu caută o soluție e că par să existe doar două opțiuni: bea mai puțin sau acceptă situația. În realitate, spectrul de cauze și intervenții e mult mai larg.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Ca să înțelegi nicturie, trebuie să înțelegi cum gestionează corpul apa în mod normal pe parcursul a 24 de ore.</p>
<p>Rinichii filtrează aproximativ 180 de litri de sânge pe zi. Din aceștia, 178-179 de litri sunt reabsorbiți. Doar 1-2 litri devin urină finală. Rata la care rinichii produc urină nu e constantă. În timpul zilei, producția e mai mare. Noaptea ar trebui să scadă cu 40-50%, permițând vezicii să acumuleze urină fără să se umple complet pe parcursul a 7-8 ore.</p>
<p>Responsabil de această reducere nocturnă e hormonul antidiuretic (ADH, sau vasopresină), produs de hipotalamus și secretat de hipofiza posterioară. Gândește-te la ADH ca la un robinet care controlează cât de multă apă lasă rinichii să treacă în urină. Când ADH e crescut, rinichii reabsorb mai multă apă, urina devine mai concentrată și volumul scade. Noaptea, la un adult tânăr sănătos, ADH crește și producția de urină scade la aproximativ jumătate față de zi.</p>
<p>Cu vârsta, acest mecanism se deteriorează. Secreția nocturnă de ADH scade, uneori dramatic. Un studiu din 1998 publicat de Asplund și colaboratorii în Scandinavian Journal of Urology and Nephrology a măsurat producția nocturnă de urină la bărbați între 70 și 80 de ani și a găsit că la mulți dintre ei, producția nocturnă o egalează sau o depășește pe cea diurnă. Rinichii lor funcționează noaptea ca și cum ar fi zi. Vezica se umple, semnalul de urinare vine, trezirea apare.</p>
<p>Dar ADH-ul nu e singura variabilă. Vezica urinară însăși se schimbă. Capacitatea funcțională a vezicii (volumul la care apare senzația de urinare) scade cu vârsta. O vezică tânără poate reține 400-500 ml confortabil. La 70 de ani, capacitatea funcțională poate scădea la 200-300 ml. Combinația dintre rinichi care produc mai multă urină noaptea și o vezică care tolerează mai puțină e rețeta clasică a nicturiei la vârstnici.</p>
<p>La bărbați, prostata adaugă un al treilea factor. Hiperplazia benignă de prostată (HBP) afectează aproximativ 50% din bărbații peste 50 de ani și 80% din cei peste 80. Prostata mărită comprimă uretra și irită vezica, producând senzația de urinare frecventă chiar și când vezica nu e plină. Jetul slab, senzația de golire incompletă și picurarea terminală sunt semne asociate.</p>
<p>La femei, slăbirea musculaturii pelviene (după sarcini, la menopauză, prin sedentarism) reduce suportul vezicii și poate contribui la vezica hiperactivă, o condiție în care mușchiul detrusor (peretele muscular al vezicii) se contractă involuntar, generând urgența urinară chiar și la volume mici.</p>
<p>Un mecanism mai puțin cunoscut, dar relevant: redistribuirea lichidelor din picioare. În timpul zilei, la persoanele care stau mult în picioare sau au insuficiență venoasă, lichidul se acumulează în țesuturile membrelor inferioare (edem periferic). Când se culcă, gravitația nu mai ține lichidul în picioare, și acesta se reabsoarbe în circulație și ajunge la rinichi, care îl transformă în urină. Friedman și colaboratorii au publicat în 2010 în Journal of Urology un studiu care a arătat că volumul de lichid redistribuit din picioare corelează direct cu volumul de urină produsă în primele ore de somn.</p>
<p>Apneea obstructivă de somn contribuie la nicturie printr-un mecanism elegant și contraintuitiv. Efortul respirator contra căilor aeriene închise crește presiunea intratoracică negativă, care stimulează eliberarea de peptid natriuretic atrial (ANP). ANP semnalează rinichilor să elimine sodiu și apă. Rezultatul: producție crescută de urină noaptea, cauzată nu de cât bei, ci de cum respiri. Unul din motivele pentru care tratamentul apneei cu CPAP reduce nicturie la mulți pacienți.</p>
<p>Diabetul, atât tip 1 cât și tip 2, produce poliurie (urinare excesivă) prin mecanism osmotic: glucoza în exces din sânge e filtrată de rinichi și "trage" apa cu ea în urină. Nicturie poate fi primul simptom al unui diabet nediagnosticat, motiv pentru care apariția sa bruscă, însoțită de sete intensă și pierdere ponderală, merită investigată rapid.</p>
<h2>Ce alimentează problema</h2>
<p>Consumul de lichide seara e factorul cel mai evident, dar nu întotdeauna cel mai important. Mulți oameni beau cantități mari de apă după cină din obișnuință, din sete reală după o cină sărată sau din convingerea că "trebuie să bei 2-3 litri pe zi." Recomandarea de 8 pahare de apă pe zi nu are bază științifică solidă. Heinz Valtin a publicat în 2002 în American Journal of Physiology un review care a căutat originea acestei recomandări și nu a găsit niciun studiu care să o susțină. Necesarul de lichide variază enorm și depinde de greutate, activitate, temperatura ambiantă și compoziția alimentației.</p>
<p>Cafeaua și alcoolul seara au efect diuretic direct. Cofeina inhibă reabsorbția de sodiu la nivel renal, crescând volumul urinar. Alcoolul suprimă secreția de ADH, exact hormonul care ar trebui să reducă producția de urină noaptea. Un pahar de vin la cină poate părea inofensiv, dar efectul asupra ADH durează 4-6 ore.</p>
<p>Medicamentele diuretice (furosemid, hidroclorotiazidă, indapamidă) sunt prescrise frecvent pentru hipertensiune și insuficiență cardiacă. Dacă sunt luate seara, efectul diuretic cade exact pe intervalul de somn. Mulți pacienți nu realizează că simpla mutare a diureticului dimineața reduce dramatic nicturie. Alte medicamente care cresc producția de urină sau irită vezica: litiul, inhibitorii SGLT2 (folosiți în diabet), antidepresivele triciclice în doze mici.</p>
<p>Insuficiența cardiacă compensată e o cauză pe care o descoperi doar dacă te gândești la ea. În timpul zilei, inima nu pompează suficient de eficient ca să perfuzeze rinichii la capacitate maximă. Noaptea, în poziția culcat, returul venos crește, inima lucrează ceva mai eficient, rinichii primesc mai mult sânge și produc mai multă urină. Nicturie poate fi primul semn al unei insuficiențe cardiace ușoare, înaintea edemelor vizibile sau a dispneei.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): comportament și timing</h3>
<p>Primul pas e un jurnal de lichide și urinări. Trei zile în care notezi ce bei (cantitate și oră), când urinezi (și volumul aproximativ, dacă e posibil) și câte treziri nocturne ai. Acest jurnal, numit frecvențial micțional, e instrumentul pe care urologul ți l-ar cere la prima consultație. Îl poți face singur și informațiile pe care le oferă sunt surprinzător de clare: arată dacă problema e producție excesivă nocturnă (poliurie nocturnă), capacitate vezicală redusă sau ambele.</p>
<p>Redistribuie consumul de lichide către prima parte a zilei. Nu e vorba de a bea mai puțin per total, ci de a bea mai mult dimineața și la prânz și mai puțin după ora 18:00. O regulă practică: 70-80% din lichide consumate înainte de ora 17:00-18:00. După această oră, sorbituri mici când e sete reală, nu pahare pline din obișnuință.</p>
<p>Elimină cafeaua și alcoolul după ora 14:00, respectiv după cină. Efectul diuretic al cofeinei persistă 4-6 ore după consum, iar alcoolul suprimă ADH-ul tocmai când ai nevoie de el cel mai mult.</p>
<p>Un truc simplu pe care puțini îl cunosc: ridică picioarele cu 20-30 de minute înainte de culcare (pe o pernă, pe peretele de lângă pat). Asta permite lichidului acumulat în picioare să se redistribuie și să fie procesat de rinichi înainte de somn, nu în timpul lui. Efectul e mai pronunțat la persoanele cu edeme de gambă sau job sedentare.</p>
<p>Golește vezica de două ori înainte de culcare: o dată cu 30 de minute înainte și încă o dată chiar înainte de a te pune în pat. Volumul rezidual din prima urinare se completează cu urina produsă în următoarele 30 de minute și poate fi suficient cât să treacă pragul de trezire după doar câteva ore.</p>
<h3>Faza 2 (săptămânile 3-4): mișcare, exerciții pelviene și nutriție</h3>
<p>Exercițiile Kegel nu sunt doar pentru femei după sarcină. Întărirea musculaturii planșeului pelvian crește controlul asupra vezicii și ridică pragul la care apare senzația de urgență. Tehnica: contracti mușchii pe care i-ai folosi ca să oprești jetul de urină (fără să oprești efectiv jetul), menții 5-10 secunde, relaxezi, repeți de 10-15 ori. Trei seturi pe zi. Rezultatele apar după 4-8 săptămâni de practică regulată. Un studiu din 2004 publicat în BJU International condus de Burgio și colaboratorii a arătat că exercițiile pelviene au redus episoadele de nicturie cu 50% la bărbați cu simptome de tract urinar inferior.</p>
<p>Activitatea fizică generală îmbunătățește circulația, reduce edemele periferice și ajută la reglarea ritmului circadian (inclusiv secreția de ADH). O plimbare de 30 de minute zilnic, în prima parte a zilei, are efecte multiple care converg către reducerea nicturiei.</p>
<p>Din punct de vedere nutrițional, reducerea sării la cină e relevantă. Sodiul în exces crește volumul urinar. Mesele procesate (conserve, mezeluri, snackuri sărate) consumate seara produc sete și cresc producția de urină în următoarele ore. Fructele bogate în apă (pepene, portocale) consumate seara adaugă lichid pe care mulți nu îl contabilizează.</p>
<p>Dacă suferi de constipație cronică, rezolvarea ei poate ameliora nicturie. Rectul plin pune presiune pe vezică și reduce capacitatea funcțională. Fibrele, hidratarea adecvată în timpul zilei și mișcarea sunt primii pași.</p>
<h3>Faza 3 (luna a doua și după): investigare și intervenții specifice</h3>
<p>Dacă nicturie persistă după 4 săptămâni de intervenții comportamentale, e momentul investigațiilor. Lista minimă: glicemie à jeun (exclude diabetul), sumar de urină și urocultură (exclude infecția urinară), PSA și ecografie de prostată la bărbați peste 45 de ani, evaluare cardiologică dacă există edeme sau dispnee de efort.</p>
<p>La bărbați cu HBP confirmată, medicația specifică (tamsulosin, finasterid) poate reduce simptomele urinare nocturne. Tamsulosina relaxează musculatura prostatică și a colului vezical, îmbunătățind fluxul urinar. Finasteridul reduce volumul prostatei pe parcursul a 3-6 luni.</p>
<p>La femei cu vezică hiperactivă, antispasticele vezicale (solifenacină, mirabegron) reduc contracțiile involuntare ale detrusorului. Efectul apare în 2-4 săptămâni. Efectele secundare (gura uscată, constipație) merită discutate cu medicul.</p>
<p>Desmopresina (o formă sintetică de ADH) e aprobată specific pentru nicturie prin poliurie nocturnă la adulți. Reduce producția de urină noaptea cu 30-50%. Se ia înainte de culcare și necesită monitorizarea sodiului seric (riscul principal e hiponatremia, mai ales la vârstnici). Nu e un medicament de prima linie, dar e o opțiune validată când cauza e deficit de ADH.</p>
<p>Dacă sforăi, ai somnolență diurnă excesivă sau partenerul de pat raportează pauze respiratorii, polisomnografia merită luată în considerare. Apneea de somn e o cauză surprinzător de frecventă a nicturiei și tratamentul cu CPAP rezolvă ambele probleme simultan.</p>
<p>Desmopresina, antispasticele și alfa-blocanții nu trebuie luate fără consultație medicală. Interacțiunile cu alte medicamente, comorbidităților (insuficiență renală, insuficiență cardiacă) și efectele secundare necesită evaluare individualizată.</p>
<h2>Unde te lasă toate astea</h2>
<p>Nicturie are o particularitate care o face frustrantă și încurajatoare în același timp: cauzele sunt multiple și se suprapun frecvent. Un bărbat de 65 de ani poate avea simultan prostată mărită, ADH scăzut și obiceiul de a bea două ceaiuri după cină. Fiecare cauză contribuie cu câte o trezire, iar împreună produc trei. Rezolvarea unei singure cauze poate fi suficientă ca să coboare numărul la o trezire pe noapte, ceea ce pentru mulți e diferența între somn fragmentat și somn funcțional.</p>
<p>Jurnalul frecvențial e probabil cel mai subevaluat instrument. Trei zile de notare îți spun dacă produci prea multă urină noaptea, dacă vezica ține prea puțin sau dacă ambele. Această distincție contează enorm, pentru că soluțiile sunt diferite. Poliurie nocturnă se rezolvă cu redistribuirea lichidelor și, eventual, desmopresină. Capacitate vezicală redusă se abordează cu exerciții pelviene și, dacă e nevoie, medicație vezicală. Fără jurnal, ghicești.</p>
<p>Dacă te trezești de două sau mai multe ori pe noapte de cel puțin câteva săptămâni, și intervențiile din prima fază nu au schimbat nimic în 3-4 săptămâni, consultul urologic nu e o exagerare. E pasul următor logic, și probabil că va începe exact cu acel jurnal frecvențial pe care îl poți pregăti dinainte.</p>
