<p>Cortizolul are un ritm precis pe parcursul a 24 de ore, cu un minim pe la miezul nopții care face somnul profund posibil. Dacă acel minim nu mai e chiar minim, creierul primește un semnal de "e dimineață" cu ore înainte de ceas, iar gândurile care apar imediat după nu sunt cauza trezirii, ci consecința ei.</p>
<ul>
  <li>Trezirile repetate între 2 și 4 dimineața nu sunt aleatorii. Coincid cu un moment vulnerabil din ciclul cortizolului.</li>
  <li>Axa HPA (hipotalamus-hipofiză-suprarenale) funcționează ca un termostat. Stresul cronic o recalibrează în sus, iar cortizolul nocturn rămâne ridicat.</li>
  <li>Gândurile care apar după trezire sunt consecință, nu cauză. Cortizolul trezește creierul, iar creierul face ce știe: gândește.</li>
  <li>Există un ciclu care se auto-alimentează: somn prost crește cortizolul, cortizolul strică somnul.</li>
  <li>Diferența dintre trezirile de cortizol și alte cauze (apnee, glicemie, reflux) are semne specifice.</li>
  <li>Intervențiile eficiente urmează o ordine clară: comportamentale mai întâi, suplimente la urmă.</li>
  <li>Testul de cortizol salivar pe 4 puncte e mai informativ decât cortizolul seric matinal.</li>
  <li>Recalibrarea axei HPA ia săptămâni sau luni. Impacienţa e cel mai frecvent motiv pentru care oamenii abandonează înainte să vadă rezultate.</li>
</ul>
<p>Cortizolul are un ritm de 24 de ore pe care majoritatea oamenilor nu îl observă până când se strică. În mod normal, nivelul scade la minim pe la miezul nopții și începe să urce lent spre dimineață, pregătind corpul pentru trezire. Acel minim nocturn e parte din ce face somnul profund posibil. Când minimul nu mai e minim, totul se mută.</p>
<p>Ce se întâmplă concret: dacă axa de stres a corpului e recalibrată în sus (din motive pe care le vom diseca mai jos), cortizolul începe să urce prea devreme sau prea abrupt. Creierul primește un semnal de "e dimineața" cu două sau trei ore înainte de trezirea reală. Și reacționează cum reacționează la orice trezire: pornește mintea. Problemele de la muncă, listele de făcut, conversațiile neîncheiate apar instantaneu, nu pentru că ele te-au trezit, ci pentru că cortizolul a făcut-o și creierul caută un motiv.</p>
<p>Un detaliu pe care mulți îl ignoră: trezirea asta nu vine cu somnolență confuză, cu ochii grei și senzația că poți readormi dacă găsești poziția potrivită. Vine cu alertă. Puls ușor crescut, claritate mentală nedorită, și o incapacitate de a readormi 30 până la 60 de minute. Dacă recunoști pattern-ul ăsta, nu e insomnie clasică. E o problemă de timing hormonal.</p>
<h2>Ce se întâmplă de fapt în corp</h2>
<p>Ca să înțelegi de ce ora 3 dimineața e atât de vulnerabilă, merită să înțelegi cum funcționează sistemul care produce cortizol. Nu e un robinet pe care corpul îl deschide și îl închide. E un lanț de comandă cu trei nivele.</p>
<p>Hipotalamusul (o structură din creier care reglează funcții de bază: temperatura, foamea, somnul) inițiază procesul trimițând un hormon numit CRH. Acesta ajunge la hipofiză, care răspunde cu ACTH. ACTH-ul călătorește prin sânge până la glandele suprarenale, care produc efectiv cortizolul. Acest lanț poartă numele de axa HPA (hipotalamus-hipofiză-suprarenale) și funcționează ca un termostat: când cortizolul din sânge atinge un anumit nivel, hipotalamusul reduce semnalul. Feedback negativ. Elegant, de obicei eficient.</p>
<p>Stresul cronic strică termostatul. Nu stresul acut, cel care vine și trece (un conflict, un deadline, o sperietură în trafic), ci cel persistent și de intensitate moderată. Presiunea constantă la muncă, grijile financiare, un conflict relațional nerezolvat, lipsa de odihnă însăși. Când semnalele de stres vin zilnic, săptămâni sau luni la rând, axa HPA se adaptează crescând pragul de răspuns. Termostatul se recalibrează în sus, iar nivelul de bază al cortizolului rămâne ridicat inclusiv noaptea.</p>
<p>Un studiu publicat în Psychoneuroendocrinology în 2006 de Gunnar și Vazquez a arătat că expunerea prelungită la stres ridică nu doar cortizolul matinal, ci și cel nocturn, tocmai prin această recalibrare a axei HPA. Efectul nu apare după o săptămână proastă la muncă. Apare după luni de stres susținut, ceea ce îl face și mai greu de identificat: schimbarea e graduală, și mulți oameni se obișnuiesc cu trezirile nocturne înainte să realizeze că sunt un simptom.</p>
<p>În ciclul normal, cortizolul începe să urce pe la 3-4 dimineața, în cadrul așa-numitei "cortisol awakening response" (CAR, răspunsul de cortizol la trezire). La o axă HPA sănătoasă, urcarea e lentă și progresivă. La una dereglată, e prematură sau abruptă. Creierul interpretează acest salt ca pe un semnal de trezire, iese din somnul profund sau din REM, și persoana se găsește brusc trează, cu mintea clară și inima bătând puțin mai repede decât ar trebui la ora respectivă.</p>
<p>Există și un mecanism indirect, prin glicemie. Cortizolul are printre funcțiile lui mobilizarea glucozei din depozite (e parte din răspunsul "luptă sau fugi"). Dacă nivelul nocturn de cortizol e crescut, glicemia fluctuează mai mult decât ar trebui în timpul somnului. O scădere bruscă a glucozei sanguine declanșează secreția de adrenalină ca mecanism de compensare. Adrenalina trezește creierul la fel de eficient ca un alarmă. Multe treziri nocturne însoțite de transpirație ușoară și o senzație vagă de anxietate sunt de fapt episoade de hipoglicemie reactivă, mediate indirect de cortizol.</p>
<p>Un lucru util de reținut pentru diferențiere: trezirile cauzate de cortizol au câteva semne specifice. Apar la ore relativ fixe (nu la 1 într-o noapte și la 5 în alta). Nu sunt declanșate de un stimul extern (zgomot, vezică urinară). Vin cu alertă, nu cu confuzie. Și implică o incapacitate de a readormi care durează 30-60 de minute. Compară cu trezirile din apnee de somn (scurte, frecvente, de care persoana nu e conștientă), din reflux gastric (arsură, gust acid) sau de vezică urinară (semnal clar și diferit). Dacă trezirile tale sunt în intervalul 2-4, cu alertă mentală rapidă și fără un declanșator evident, cortizolul e un suspect rezonabil.</p>
<h2>Ce alimentează dereglarea</h2>
<p>Stresul psihologic e sursa evidentă, dar mecanismul e mai specific decât formula "stres egal somn prost". Hipotalamusul răspunde la ceea ce corpul percepe ca amenințare, iar percepția asta nu se oprește la culcare. Dacă seara e momentul în care mintea face bilanțul zilei, analizează ce a mers prost, planifică ziua următoare, hipotalamusul primește aceleași semnale ca în timpul unui conflict real. Răspunsul hormonal nu face distincția între un email neplăcut și un pericol fizic.</p>
<p>Exercițiul fizic intens după ora 20 ridică cortizolul. E un stres controlat, util la ore potrivite, dar dacă antrenamentul se termină la 21:30, nivelul de cortizol nu apucă să revină la normal înainte de culcare. Un studiu din 2019 publicat în Sports Medicine de Stutz, Eiholzer și Spengler a confirmat că exercițiul intens cu mai puțin de două ore înainte de somn crește latența adormirii și reduce somnul profund.</p>
<p>Alcoolul e un contributor pe care mulți nu îl suspectează. Un pahar de vin seara ajută adormitul (efectul sedativ e real), dar metabolizarea lui produce acetaldehidă, care crește cortizolul și adrenalina în a doua parte a nopții. Intervalul în care aceste substanțe ating nivelul maxim coincide exact cu fereastra 2-4 dimineața. Studiul lui Roehrs și Roth, publicat în Alcohol Research and Health în 2001, a documentat acest pattern: adormire mai rapidă, dar treziri mai frecvente și somn mai fragmentat în a doua jumătate a nopții.</p>
<p>Ecranele seara contribuie nu doar prin lumina albastră (care suprimă melatonina), ci și prin conținut. Știri despre criza economică, un thread inflamant pe social media, o conversație tensionată pe WhatsApp la ora 23 ridică cortizolul la fel de eficient ca un conflict în persoană. Hipotalamusul nu știe că ești în pat. Răspunde la semnalul emoțional.</p>
<p>Și paradoxul care închide cercul: lipsa de somn însăși crește cortizolul. Leproult și Van Cauter au publicat în Sleep în 1997 un studiu care a măsurat o creștere de până la 45% a cortizolului seric după o singură noapte sub 6 ore. Ciclul se auto-alimentează: somn prost ridică cortizolul, cortizolul strică somnul, somnul stricat ridică și mai mult cortizolul.</p>
<h2>Ce se poate face concret</h2>
<h3>Faza 1 (săptămânile 1-2): zona tampon de seară și corp</h3>
<p>Primul pas nu e un supliment sau un test de sânge. E crearea unei separații clare între ziua activă și momentul culcării. Ultimele 60 până la 90 de minute înainte de somn fără decizii, planificare, știri, conversații dificile, emailuri de muncă. Aceste activități semnalează hipotalamusului că ziua de lucru continuă, și hipotalamusul nu știe să citească ceasul.</p>
<p>Un instrument simplu care funcționează: "jurnalul de descărcare". Zece minute de scris pe hârtie, fără cenzură, tot ce există în cap. Nu jurnal reflexiv, nu gratitudine, ci pur și simplu golirea ruminării pe hârtie. Scopul e mecanic: muți gândurile din circuitul activ al creierului într-un format extern, și hipotalamusul reduce alerta. Un studiu din 2018 publicat în Journal of Experimental Psychology de Scullin și colaboratorii a arătat că participanții care scriau o listă de sarcini pentru ziua următoare adormeau cu 9 minute mai repede decât cei care scriau despre activități completate. Pentru cineva care stă în pat 45 de minute, 9 minute reprezintă o reducere de 20%.</p>
<p>Respirația diafragmatică acționează direct pe fiziologie. Expirarea prelungită (4 secunde inspir, 7-8 secunde expir) activează nervul vag, frâna naturală a sistemului de stres. Nervul vag semnalează hipotalamusului să reducă producția de CRH. Efectul e măsurabil: variabilitatea ritmului cardiac (HRV, un indicator al activității parasimpatice) crește în câteva minute de respirație controlată. Cinci minute înainte de culcare, fără aplicații, fără ghidare audio, doar respirație și numărare.</p>
<p>Mișcarea fizică rămâne importantă, dar timing-ul contează. Mutarea antrenamentelor intense înainte de ora 18 permite cortizolului să revină la normal până la culcare. O plimbare ușoară de 15-20 de minute după cină e o alternativă bună: suficient de blândă încât să nu ridice cortizolul, suficient de activă încât să scadă tensiunea musculară acumulată în timpul zilei.</p>
<h3>Faza 2 (săptămânile 3-4): intervenții directe și context social</h3>
<p>Temperatura corporală e un instrument subestimat. Un duș cald cu 60-90 de minute înainte de culcare dilatează vasele de sânge periferice. După disiparea căldurii, temperatura centrală scade rapid. Această cădere mimează semnalul natural de "e noapte" pe care corpul îl folosește ca declanșator al somnului. Efectul indirect asupra cortizolului vine prin reducerea timpului de adormire: când nu mai stai treaz în pat 40 de minute, stresul generat de insomnia însăși scade.</p>
<p>Componenta socială și psihologică merită atenție aici. Dacă sursa stresului cronic e un conflict relațional sau o situație profesională nesustenabilă, intervențiile de seară sunt un plasture pe o rană deschisă. Identificarea sursei de stres care menține axa HPA recalibrată e la fel de importantă ca rutina de somn. Uneori o conversație dificilă pe care o tot amâni e mai eficientă pentru cortizol decât orice supliment.</p>
<p>Din punct de vedere nutrițional: ultima masă cu cel puțin 3 ore înainte de culcare, cu proteine, grăsimi și carbohidrați complecși. Carbohidrații complecși seara (orez, cartofi dulci, ovăz) stabilizează glicemia în prima parte a nopții, reducând riscul de hipoglicemie reactivă. Un mic snack înainte de culcare (câteva nuci, o lingură de unt de arahide) poate ajuta persoanele care suspectează că trezirile lor au și o componentă glicemică.</p>
<p>Ashwagandha (Withania somnifera) are dovezi rezonabile. Un studiu randomizat din 2019 publicat în Medicine de Lopresti, Smith și Drummond a arătat o reducere cu 23% a cortizolului matinal după 8 săptămâni de suplimentare cu 300 mg extract standardizat KSM-66, de două ori pe zi. Efectul apare după 4-6 săptămâni, nu imediat. Fosfatidilserina (100-300 mg seara) are studii mai mici dar consistente privind reducerea cortizolului indus de stres, și poate fi o alternativă pentru persoanele care iau medicație incompatibilă cu ashwagandha.</p>
<h3>Faza 3 (luna a doua și după): testare și personalizare</h3>
<p>Dacă trezirile persistă după 6 săptămâni de implementare consistentă, testarea cortizolului devine utilă. Testul standard de cortizol seric matinal măsoară un singur punct în timp și spune prea puțin. Mai informativ e testul de cortizol salivar pe 4 puncte (dimineața la trezire, la prânz, seara, înainte de culcare), care arată curba întregii zile. O curbă plată (cortizol care nu variază suficient între dimineață și seară) sau un cortizol crescut la punctul de seară sunt indicii concrete de disfuncție a axei HPA.</p>
<p>La acest punct merită și o evaluare mai largă. Trezirile nocturne recurente pot avea cauze care coexistă cu cortizolul crescut: apnee obstructivă de somn (micro-treziri respiratorii de care persoana nu e conștientă), disfuncții tiroidiene, sindrom metabolic sau anxietate generalizată. Un endocrinolog sau un specialist în medicina somnului poate diferenția între aceste cauze pe baza testelor și a istoricului.</p>
<h2>Unde te lasă asta</h2>
<p>Recalibrarea unei axe HPA care a funcționat în regim de stres luni sau ani nu se întâmplă în două săptămâni. Asta e poate informația cea mai importantă din tot articolul, și cea pe care cei mai mulți nu vor să o audă. Primele săptămâni de rutină de seară pot părea complet ineficiente. Nu pentru că nu funcționează, ci pentru că efectul e cumulativ: fiecare seară cu cortizol mai scăzut contribuie la recalibrarea treptată a termostatului, dar recalibrarea nu devine vizibilă decât după un prag.</p>
<p>Cel mai greu lucru nu e respirația sau jurnalul. E renunțarea la telefon cu 90 de minute înainte de somn. Pentru mulți, scrolling-ul de seară e un anestezic emoțional: acoperă gândurile, umple liniștea. Jurnalul de descărcare poate fi inconfortabil tocmai pentru că scoate la suprafață exact ce scrolling-ul masca. Inconfortul ăsta trece, de obicei în câteva zile.</p>
<p>Dacă după două luni de implementare reală (nu intermitentă, nu "mai mult sau mai puțin"), trezirile rămân frecvente, cel puțin 3 nopți pe săptămână, e momentul pentru testul de cortizol salivar și o consultație. Există situații în care intervențiile comportamentale au nevoie de sprijin medical. A recunoaște asta nu e un eșec. E următorul pas logic.</p>
