<ul>
  <li>Sfincterul esofagian inferior funcționează ca o supapă între stomac și esofag, iar poziția culcat elimină avantajul gravitației care îl ajută să rămână închis</li>
  <li>Producția de acid gastric urmează un ritm circadian și crește natural între orele 22 și 2 dimineața, exact când majoritatea oamenilor dorm</li>
  <li>Reflexul de înghițire și producția de salivă scad dramatic în somn, ceea ce înseamnă că acidul ajuns în esofag rămâne acolo mai mult timp</li>
  <li>Trezirile cauzate de reflux nu vin întotdeauna cu arsura clasică: tusea seacă, senzația de sufocare sau gustul amar sunt la fel de frecvente</li>
  <li>Mesele târziu, grăsimile, alcoolul și cafeaua relaxează sfincterul esofagian și cresc riscul de episoade nocturne</li>
  <li>Dormitul pe partea stângă reduce expunerea esofagului la acid cu până la 70% față de poziția pe dreapta</li>
  <li>Inhibitorii de pompă de protoni funcționează, dar nu sunt meniți să fie luați pe viață fără investigație</li>
  <li>Endoscopia devine necesară când simptomele persistă peste 8 săptămâni sau apar semne de alarmă</li>
</ul>
<p>Dacă ai simțit vreodată o arsură în piept la 20 de minute după ce te-ai întins în pat, știi că nu e ceva ce poți ignora și adormi. Refluxul gastro-esofagian nocturn e una dintre acele probleme care par minore până le experimentezi la 1 dimineața, cu gust acid în gât și senzația că ceva nu e în regulă. Și totuși, pentru mulți, episoadele devin atât de frecvente încât ajung să le considere normale.</p>
<p>Nu sunt. Un studiu din 2005 condus de Fass și colaboratorii, publicat în Chest, a arătat că 79% dintre persoanele cu reflux gastro-esofagian (GERD) raportează simptome nocturne, iar dintre acestea, 75% spun că simptomele le afectează somnul direct. Refluxul nocturn nu e doar o variantă mai incomodă a celui diurn. Are mecanisme proprii, consecințe specifice asupra somnului și, din fericire, soluții care funcționează dacă știi unde să intervii.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Ca să înțelegi de ce refluxul se agravează noaptea, merită să înțelegi mai întâi cum funcționează sistemul de protecție în mod normal.</p>
<p>Între stomac și esofag există un inel muscular numit sfincterul esofagian inferior (SEI). Gândește-te la el ca la o supapă unidirecțională: se deschide când înghiți ca să lase mâncarea să treacă în stomac, apoi se închide ca să împiedice acidul să urce înapoi. În condiții normale, tonusul muscular al SEI și presiunea pozitivă din abdomen mențin supapa închisă. Stomacul produce acid clorhidric cu un pH între 1 și 3, suficient de puternic încât să dizolve un cui mic. Esofagul nu are aceeași protecție mucoasă și suferă când e expus la acest acid.</p>
<p>În timpul zilei, când stai în picioare sau așezat, gravitația lucrează în favoarea ta. Chiar dacă SEI se relaxează momentan (ceea ce e normal, se întâmplă de 20-30 de ori pe zi la oricine), acidul care urcă puțin în esofag e tras înapoi de gravitație și spălat de saliva pe care o înghiți în mod reflex. Clearance-ul esofagian, așa cum îl numesc gastroenterologii, funcționează eficient în poziție verticală.</p>
<p>Noaptea, trei lucruri se schimbă simultan. Primul: te culci. Gravitația nu mai ajută. Stomacul și esofagul ajung la același nivel, iar acidul se poate deplasa liber în ambele direcții. Al doilea: producția de salivă scade cu aproximativ 80% în somn. Saliva e ușor alcalină și neutralizează acidul din esofag. Fără ea, acidul care ajunge sus rămâne acolo minute în șir în loc de secunde. Al treilea: frecvența înghițirilor reflexe scade de la o dată pe minut în starea de veghe la aproape zero în somnul profund.</p>
<p>William Orr, unul dintre cercetătorii care au studiat cel mai mult relația dintre GERD și somn, a publicat în 2003 în American Journal of Gastroenterology un studiu care a măsurat timpii de clearance esofagian: în starea de veghe, un episod de reflux era neutralizat în medie în 1-2 minute. În somn, același episod persista 15-20 de minute. Asta înseamnă că mucoasa esofagului e expusă la acid de 10 ori mai mult timp noaptea.</p>
<p>Un alt element care complică lucrurile: producția de acid gastric nu e constantă pe parcursul zilei. Urmează un ritm circadian descris încă din anii 1970 de Moore și Englert, cu un vârf de secreție între orele 22 și 2 dimineața. Deci nu doar că mecanismele de protecție sunt la minim noaptea, dar cantitatea de acid e la maxim. E o combinație nefericită pe care fiziologia nu a avut motive să o rezolve în cursul evoluției, pentru că strămoșii noștri nu mâncau mese grele la 22:00 și nu se culcau imediat după.</p>
<p>Trezirile cauzate de reflux au un profil distinct. Uneori vin cu arsura retrosternală clasică. Dar la fel de des vin cu tuse seacă, senzația de nod în gât, voce răgușită dimineața, sau chiar senzația bruscă de sufocare (când acidul ajunge până la laringe sau chiar aspiră în căi respiratorii). Gastroenterologii numesc asta reflux laringofaringian, și mulți pacienți cu această formă nu raportează niciodată arsura clasică. Merg la ORL pentru tuse cronică sau la pneumolog pentru "astm" nocturn, când sursa e stomacul.</p>
<p>Și un cerc vicios pe care cercetarea recentă l-a documentat: refluxul nocturn fragmentează somnul, iar somnul fragmentat crește sensibilitatea viscerală. Omer Schuster și echipa lui au publicat în 2019 în Neurogastroenterology and Motility un studiu care a arătat că privarea de somn scade pragul de percepție a durerii esofagiene. Cu alte cuvinte, după o noapte proastă, esofagul simte mai intens chiar și cantități mici de acid. Refluxul fragmentează somnul, somnul prost amplifică refluxul, ciclul se perpetuează.</p>
<h2>Ce alimentează problema</h2>
<p>Mesele tardive sunt probabil factorul numărul unu. Stomacul are nevoie de 2-4 ore ca să golească o masă, în funcție de compoziție. Dacă te culci cu stomacul plin, presiunea intragastrică e crescută, SEI e solicitat mai mult și probabilitatea de reflux crește proporțional. Un studiu din 2005 condus de Fujiwara și colaboratorii la Universitatea din Osaka a arătat că persoanele care mâncau cu mai puțin de 3 ore înainte de culcare aveau un risc de 7.5 ori mai mare de reflux nocturn față de cele care respectau un interval mai lung.</p>
<p>Grăsimile încetinesc golirea gastrică și relaxează tonusul SEI prin eliberarea de colecistokinină (CCK), un hormon intestinal care semnalează digestia grăsimilor. O cină bogată în grăsimi nu doar că stă mai mult în stomac, ci și slăbește activ supapa care ar trebui să țină acidul jos. Combinația grăsimi + culcat la scurt timp după e poate cel mai fiabil declanșator.</p>
<p>Alcoolul relaxează musculatura netedă, inclusiv SEI. Un studiu din 2006 publicat în American Journal of Gastroenterology de Pehl și colaboratorii a măsurat direct presiunea SEI după consum de alcool și a găsit o scădere cu 30-40% care persistă 2-3 ore. În plus, alcoolul stimulează secreția acidă și irită direct mucoasa esofagiană.</p>
<p>Cafeaua, inclusiv cea decofeinizată, crește secreția acidă și relaxează ușor SEI. Ciocolata are un efect similar prin teobromină. Mentolul (inclusiv ceaiurile de mentă) relaxează musculatura netedă, motiv pentru care ceaiul de mentă după cină, deși pare inofensiv, poate agrava refluxul.</p>
<p>Excesul ponderal crește presiunea intra-abdominală, care se transmite direct asupra stomacului și împinge conținutul către esofag. Fiecare kilogram în plus în zona abdominală crește presiunea. Un studiu epidemiologic din 2006 condus de Jacobson și publicat în New England Journal of Medicine a arătat că persoanele cu un IMC peste 30 aveau un risc de 2.5 ori mai mare de simptome de reflux față de cele cu greutate normală. Chiar și o creștere moderată în greutate (5-7 kg) a fost asociată cu agravarea simptomelor.</p>
<p>Tutunul reduce presiunea SEI și scade producția de salivă, ambele mecanisme de protecție împotriva refluxului. Medicamentele antiinflamatoare nesteroidiene (ibuprofen, naproxen) irită direct mucoasa gastrică și esofagiană. Unele medicamente pentru tensiune (blocantele canalelor de calciu, nitrații) relaxează musculatura netedă, inclusiv SEI.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): poziție, timing și comportament</h3>
<p>Cea mai importantă schimbare nu costă nimic și are efect imediat: nu te culca în primele 3 ore după masa principală. Dacă cina e la 20:00, nu în pat înainte de 23:00. Dacă programul nu permite asta, mută cina mai devreme și fa-o mai ușoară. O masă mai mică la 18:30 plus o gustare mică la 21:00 (câteva biscuiți integrali cu brânză, nimic gras) e mai bună decât o cină copioasă la 21:30.</p>
<p>Poziția de somn face o diferență surprinzător de mare. Dormitul pe partea stângă menține joncțiunea gastro-esofagiană deasupra nivelului acidului gastric, datorită anatomiei stomacului. Person și colaboratorii au publicat în 2015 în Journal of Clinical Gastroenterology un studiu care a arătat că poziția pe stânga a redus timpul de expunere a esofagului la acid cu 71% față de poziția pe dreapta. E o diferență enormă pentru ceva ce nu implică niciun medicament. O pernă de corp plasată la spate poate ajuta să menții poziția pe parcursul nopții.</p>
<p>Ridicarea capului patului cu 15-20 cm (nu doar perne suplimentare, ci înclinarea întregului pat, cu blocuri sub picioarele de la capul patului sau o pană sub saltea) folosește gravitația chiar și în poziția culcat. Pernele suplimentare singure nu funcționează bine: flexează corpul la nivelul abdomenului, ceea ce poate crește presiunea asupra stomacului.</p>
<p>O plimbare ușoară de 15-20 de minute după cină accelerează golirea gastrică și reduce presiunea intragastrică. Nu e nevoie de nimic intens. Ritmul contează mai puțin decât faptul că ești în picioare și în mișcare, ceea ce permite gravitației și peristaltismului să lucreze împreună.</p>
<p>Seara, evită hainele strânse în zona abdominală (centuri, pantaloni inguști). Presiunea externă se transmite la stomac și crește riscul de reflux.</p>
<h3>Faza 2 (săptămânile 3-4): alimentație și context social</h3>
<p>Identifică-ți declanșatorii personali. Lista clasică (grăsimi, cafea, alcool, citrice, roșii, mentă, ciocolată, mâncare picantă) e un punct de pornire, dar nu toți oamenii reacționează la toate. Un jurnal alimentar simplu, ținut două săptămâni, în care notezi ce ai mâncat seara și dacă ai avut simptome nocturne, îți dă informații personalizate mai utile decât orice listă generală.</p>
<p>Cafeaua merită mutată exclusiv în prima parte a zilei, înainte de 14:00. Nu doar pentru efectul asupra somnului (cofeina), ci pentru stimularea acidă care persistă ore după consum. Alcoolul seara, chiar și un pahar de vin, combină relaxarea SEI cu stimularea acidă și încetinirea golirii gastrice. Dacă refluxul nocturn e o problemă recurentă, eliminarea alcoolului seara timp de 2-3 săptămâni e un test simplu și informativ.</p>
<p>Mesele mai mici și mai frecvente pun mai puțină presiune pe stomac decât mesele mari. Dacă cinezi copios pentru că nu ai mâncat suficient în timpul zilei, problema începe de fapt la prânz. Un prânz consistent reduce nevoia de a compensa seara.</p>
<p>Fumatul, dacă e cazul, are impact direct și măsurabil. Renunțarea nu e simplă, dar e relevant să știi că fiecare țigară reduce presiunea SEI pentru 30-60 de minute.</p>
<p>Componenta socială: cinele în grup tind să fie mai copioase, mai tardive și însoțite de alcool. Nu e vorba de a renunța la ele, ci de a fi conștient că o seară socială cu cină grea la 22:00 plus vin va produce aproape sigur simptome. Planificarea (o masă mai ușoară la prânz în zilele cu cină socială, poziția pe stânga la culcare) reduce impactul fără să elimine plăcerea.</p>
<h3>Faza 3 (luna a doua și după): medicație și investigare</h3>
<p>Antiacidele (hidroxid de aluminiu și magneziu, carbonat de calciu) neutralizează acidul deja prezent în stomac și oferă ameliorare în 5-15 minute. Sunt utile ca intervenție de urgență, dar efectul durează 1-2 ore. Nu rezolvă cauza.</p>
<p>Blocanții receptorilor H2 (famotidină, ranitidină) reduc producția de acid cu 50-70% și au efect în 30-60 de minute. Famotidina 20 mg luată cu 30 de minute înainte de culcare e o opțiune rezonabilă pentru refluxul nocturn intermitent.</p>
<p>Inhibitorii de pompă de protoni (IPP: omeprazol, esomeprazol, pantoprazol) sunt cele mai puternice medicamente antiacide. Reduc secreția acidă cu 90-95% și sunt eficiente pentru refluxul frecvent. Dar au o nuanță importantă: sunt gândite pentru cure de 4-8 săptămâni, nu pentru uz indefinit. Utilizarea pe termen lung (peste 1 an) a fost asociată în mai multe studii cu risc crescut de deficit de magneziu, deficit de vitamina B12, și posibil risc de fracturi (un studiu din 2006 publicat în JAMA de Yang și colaboratorii a raportat o asociere între IPP pe termen lung și fracturi de șold). Aceste riscuri sunt încă dezbătute, dar principiul rămâne: IPP-urile trebuie folosite în doza minimă eficientă și pe durata minimă necesară.</p>
<p>Endoscopia digestivă superioară devine necesară în câteva situații clare: simptome care persistă peste 8 săptămâni în ciuda tratamentului, dificultate la înghițire (disfagie), scădere ponderală inexplicabilă, anemie, vărsături cu sânge sau scaune negre. Aceste semne pot indica esofagită erozivă, stricturi esofagiene sau, rar, esofag Barrett (o modificare a mucoasei esofagiene care necesită monitorizare). Vârsta peste 50 de ani cu simptome noi de reflux e un alt motiv pentru endoscopie, conform ghidurilor Societății Americane de Gastroenterologie.</p>
<p>Un aspect pe care mulți îl subestimează: refluxul nocturn cronic poate cauza probleme respiratorii. Microaspirația de acid în căile respiratorii e asociată cu astm nocturn, tuse cronică și chiar pneumonii recurente. Dacă ai tuse seacă nocturnă care nu răspunde la tratament pneumologic, refluxul merită investigat ca sursă.</p>
<h2>Unde te lasă toate astea</h2>
<p>Refluxul gastro-esofagian nocturn are ceva particular față de alte probleme de somn: răspunde rapid la modificări simple. Mulți oameni care ridică capul patului, se culcă pe stânga și mută cina cu două ore mai devreme observă o diferență clară în primele nopți. Nu în săptămâni, în nopți.</p>
<p>Asta nu înseamnă că toate cazurile sunt la fel de simple. Refluxul care persistă în ciuda modificărilor de stil de viață merită investigat, nu doar tratat cu antiacide la nesfârșit. Un gastroenterolog poate evalua dacă există o hernie hiatală (o deplasare a porțiunii superioare a stomacului deasupra diafragmului care compromite semnificativ funcția SEI), esofagită sau alte complicații care schimbă abordarea.</p>
<p>Dar pentru majoritatea persoanelor care citesc asta și se recunosc în descriere, următorul pas e concret și accesibil: două săptămâni fără mâncare în ultimele 3 ore înainte de culcare, poziția pe stânga, și un blocnotes pe noptieră în care notezi ce ai mâncat și ce ai simțit. Datele tale proprii îți vor spune mai mult decât orice ghid general.</p>
