<p>Fiecare episod de scrâșnit produce o micro-trezire corticală, iar 40-60 de astfel de episoade pe noapte pot transforma un somn aparent suficient într-unul profund fragmentat. Dacă te trezești cu maxilarul încordat sau cu durere în tâmple, e posibil ca somnul tău să fie sabotat de un mecanism de care nu ești conștient.</p>
<ul>
  <li>Bruxismul nocturn (scrâșnitul și strângerea dinților în somn) afectează estimativ 8-13% din populația adultă și produce micro-treziri repetate care fragmentează somnul fără ca persoana să fie conștientă</li>
  <li>Episoadele de bruxism apar predominant în somnul ușor (fazele N1 și N2) și în tranzițiile dintre faze, reducând timpul petrecut în somnul profund restaurativ</li>
  <li>Forța exercitată în timpul bruxismului nocturn poate depăși 250 de kilograme pe centimetru pătrat, de câteva ori mai mare decât mestecatul voluntar, ceea ce explică uzura severă a dinților și durerile faciale cronice</li>
  <li>Există o legătură bidirecțională între bruxism și apneea obstructivă de somn: în unele cazuri, scrâșnitul e un mecanism compensator prin care corpul încearcă să redeschidă căile aeriene</li>
  <li>Stresul și anxietatea sunt cei mai frecvent citați factori declanșatori, dar bruxismul are și componente neurologice (dopamină, serotonină) și mecanice (malocluzii, postură mandibulară)</li>
  <li>Semnele pe care le poți observa singur: dureri de maxilar sau de tâmple dimineața, dinții cu margini tocite sau aplatizate, sensibilitate dentară inexplicabilă, dureri de urechi fără infecție</li>
  <li>Gutiera ocluzală protejează dinții dar nu tratează cauza; abordarea completă include relaxarea musculaturii masticatorii, gestionarea stresului și investigarea cauzelor subiacente</li>
  <li>Bruxismul care nu răspunde la management de stres merită investigat pentru apnee de somn, reflux gastro-esofagian sau disfuncții ale articulației temporo-mandibulare (ATM)</li>
</ul>
<p>Dacă te trezești dimineața cu maxilarul încleștat, cu durere în tâmple sau cu o senzație de rigiditate în partea laterală a feței, s-ar putea să faci ceva în somn de care nu știi. Bruxismul nocturn e surprinzător de frecvent și surprinzător de ignorat, tratat de multe ori ca o curiozitate minoră sau ca un "tic de stres." În realitate, e un fenomen care îți afectează somnul, dinții, articulația mandibulară și calitatea vieții în moduri care se acumulează în timp.</p>
<p>Ce îl face relevant pentru o conversație despre somn e că bruxismul nu e doar o consecință a somnului prost. Îl și cauzează. Episoadele de scrâșnit produc micro-treziri corticale repetate, fragmentează arhitectura somnului și pot reduce timpul în somnul profund. Poți dormi 8 ore și să te trezești obosit nu pentru că nu ai stat suficient în pat, ci pentru că maxilarul tău a lucrat toată noaptea.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Bruxismul nocturn e clasificat ca o tulburare de mișcare legată de somn. Spre deosebire de bruxismul diurn (strângerea sau scrâșnitul în timpul zilei, care e de obicei legat de concentrare sau stres), cel nocturn se întâmplă în mod involuntar, în absența conștienței, și are caracteristici fiziologice distincte.</p>
<p>Un episod tipic de bruxism nocturn durează 4-15 secunde și implică contracții ritmice ale mușchilor maseter și temporali (mușchii principali ai mestecatului), cu o frecvență de aproximativ 1 contracție pe secundă. Forța generată e remarcabilă. În timpul mestecatului normal, forțele ocluzale ajung la 70-100 kg/cm2. În bruxism, studiile lui Nishigawa și colegilor publicate în 2001 în Journal of Dental Research au măsurat forțe de până la 250-300 kg/cm2. Această diferență explică de ce bruxismul poate produce uzură dentară vizibilă în câțiva ani, poate fractura restaurări dentare și poate deteriora treptat articulația temporo-mandibulară.</p>
<p>Episoadele apar predominant în fazele de somn ușor (N1 și N2) și în tranzițiile dintre fazele de somn. Lavigne și colegii, publicând în 2001 în Journal of Dental Research, au demonstrat că 80% din episoadele de bruxism sunt precedate de o secvență specifică: mai întâi o activare autonomă (creșterea ritmului cardiac cu 10-25%), apoi o activare EEG corticală (micro-trezire), și abia apoi contracția musculară. Cu alte cuvinte, bruxismul nu e un fenomen izolat muscular. E parte dintr-o cascadă de activare care implică întregul sistem nervos.</p>
<p>Aceste micro-treziri asociate bruxismului se numesc RMMA (rhythmic masticatory muscle activities) și pot apărea de 5-8 ori pe oră de somn la o persoană cu bruxism moderat. Fiecare episod produce o trecere tranzitorie de la somnul profund sau intermediar spre somnul ușor sau chiar veghe parțială. Cumulativ, pe o noapte, asta înseamnă 40-60 de micro-treziri suplimentare. Rezultatul: un somn care pe ceas arată adecvat dar care la nivel de structură internă e fragmentat.</p>
<p>Neurobiologia bruxismului implică mai multe sisteme de neurotransmițători. Dopamina joacă un rol central. Studii pe modele animale și observații clinice au arătat că medicamentele care cresc activitatea dopaminergică (amfetamine, L-DOPA) pot induce bruxism, în timp ce intervențiile care o scad îl reduc uneori. Lobbezoo și colegii au publicat în 1997 în Brain un studiu care a arătat că administrarea de L-DOPA la voluntari sănătoși a crescut activitatea de bruxism în somn. Serotonina e și ea implicată: inhibitorii selectivi ai recaptării serotoninei (SSRI), o clasă frecventă de antidepresive, produc bruxism ca efect secundar la aproximativ 25% din utilizatori.</p>
<p>Legătura cu apneea obstructivă de somn merită înțeleasă în detaliu. Studii mai recente au găsit o prevalență de bruxism de 2-3 ori mai mare la pacienții cu apnee comparativ cu populația generală. Mehta și colegii au propus în 2015 în Journal of Clinical Sleep Medicine că bruxismul poate fi, în unele cazuri, un mecanism protector: contracția mușchilor mandibulari împinge mandibula înainte și redeschide parțial căile aeriene colapsate. Corpul scrâșnește ca să poată respira. În aceste cazuri, tratarea apneei (prin CPAP sau dispozitive de avansare mandibulară) reduce și bruxismul.</p>
<p>Refluxul gastro-esofagian nocturn e un alt trigger subestimat. Acidul care ajunge în esofag și faringe stimulează reflexe de deglutiție și de contracție mandibulară. Miyawaki și colegii au publicat în 2003 în Sleep date care arată o corelație temporală între episoadele de reflux și episoadele de bruxism în cursul aceleiași nopți. Salivația stimulată de bruxism ar putea fi un mecanism de tamponare a acidității esofagiene, ceea ce ar face și din bruxismul asociat refluxului un răspuns compensator.</p>
<h2>Ce alimentează problema</h2>
<p>Stresul și anxietatea sunt factorii cel mai frecvent invocați și pe bună dreptate. Studii epidemiologice, inclusiv cele ale lui Manfredini și colegilor publicate în 2005 în Journal of Oral Rehabilitation, au găsit o asociere consistentă între nivelurile percepute de stres și severitatea bruxismului. Mecanismul probabil implică activarea axei hipotalamo-hipofizo-suprarenale și creșterea tonusului simpatic, care menține musculatura masticatorie într-o stare de hipertonus chiar și în somn.</p>
<p>Dar stresul nu explică totul. Mulți oameni stresați nu fac bruxism, și unii oameni cu bruxism sever nu raportează stres deosebit. Componenta genetică e reală: studii pe gemeni au arătat că bruxismul are o heritabilitate de aproximativ 50%. Dacă un părinte face bruxism, probabilitatea ca și copilul să facă e crescută semnificativ.</p>
<p>Postura diurnă a mandibulei influențează noaptea. Strângerea dinților în timpul zilei (de obicei inconștientă, asociată cu concentrarea sau utilizarea ecranelor) menține mușchii masticatori în contracție cronică și reduce pragul la care se activează bruxismul nocturn. Mulți oameni nu realizează că își strâng dinții ziua până când observă că maxilarul e încleștat la sfârșitul programului.</p>
<p>Consumul de alcool seara crește riscul de bruxism. Rintakoski și colegii, publicând în 2012 în Journal of Oral Rehabilitation, au găsit că consumul de alcool crește frecvența episoadelor de bruxism cu 30-50% comparativ cu nopțile fără alcool, probabil prin efectul asupra nivelurilor de dopamină și prin fragmentarea somnului. Cafeina în cantități mari și tutunul au asocieri similare, deși mai slabe.</p>
<p>Malocluziile (contactele dentare anormale) au fost considerate multă vreme cauza principală a bruxismului. Cercetarea recentă a nuanțat această idee: malocluziile severe pot contribui, dar nu sunt nici necesare, nici suficiente pentru a produce bruxism. Mulți oameni cu ocluzii imperfecte nu fac bruxism, și mulți cu ocluzii normale fac. Factorul neuromuscular și cel psihologic par să cântărească mai mult decât cel mecanic.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-2): conștientizare și protecție</h3>
<p>Primul pas e să confirmi că faci bruxism. Dacă dormi cu un partener, întreabă-l dacă aude scrâșnit noaptea. Dacă dormi singur, semne indirecte includ: dureri de maxilar sau de tâmple la trezire, dinții cu margini aplatizate sau cu fisuri de smalț, sensibilitate dentară la rece fără carie evidentă, dureri de urechi fără infecție, dureri de cap matinale (în special în zona temporo-frontală), indentări pe limbă (marcajele dinților pe marginile limbii).</p>
<p>Un control stomatologic orientat specific spre semne de bruxism e util. Dentistul poate identifica uzură dentară, fracturi incipiente de smalț și semne de suferință ATM pe care tu nu le observi.</p>
<p>Gutiera ocluzală (splint de bruxism) e prima linie de protecție. Nu oprește bruxismul, dar distribuie forțele și protejează suprafețele dentare. O gutieră personalizată, făcută de dentist pe model, e preferabilă variantelor universale din farmacii, care pot modifica ocluzia și agrava problema ATM. Gutiera se poartă noaptea și se înlocuiește când se uzează vizibil (de obicei la 1-3 ani).</p>
<p>În paralel, începe să observi ce face mandibula ta în timpul zilei. Regula de repaus mandibular: în poziția de relaxare, buzele sunt închise, dinții nu se ating, limba stă pe cerul gurii. Dacă descoperi frecvent că dinții tăi sunt strânși în timpul zilei, ai identificat o sursă de tensiune cronică care se transferă în noapte.</p>
<p>Pune mici remindere vizuale în locurile unde petreci timp (un sticker pe monitor, un semn pe telefonul de birou). De fiecare dată când le observi, verifică: sunt dinții strânși? Mandibula e relaxată? Limba e pe cerul gurii? Această tehnică simplă, numită "conștientizare proprioceptivă," reduce bruxismul diurn în 2-4 săptămâni conform studiilor lui Glaros și colegilor din 2005 publicate în Journal of Oral Rehabilitation.</p>
<h3>Faza 2 (săptămânile 3-6): relaxare musculară și management stres</h3>
<p>Exerciții de relaxare a musculaturii masticatorii, făcute înainte de culcare. Un protocol simplu: deschide gura larg timp de 5 secunde, apoi închide ușor și relaxează complet mandibula. Repetă de 10 ori. Apoi apasă ușor cu degetele pe mușchii maseter (în zona dintre urechea și colțul mandibulei) și masează circular timp de 60 de secunde de fiecare parte. Aplică căldură umedă (prosop cald) pe zona maseter și temporal timp de 10-15 minute. Această rutină reduce hipertonusul muscular acumulat în timpul zilei.</p>
<p>Tehnici de gestionare a stresului care au dovezi specifice pentru bruxism: relaxarea musculară progresivă (tensionarea și relaxarea grupelor musculare de la picioare spre cap) practicată înainte de somn reduce frecvența episoadelor de bruxism conform unei revizuiri sistematice publicate de Ilovar și colegii în 2014 în Head &amp; Face Medicine. Respirația diafragmatică (4 secunde inspir, 7 secunde expir) activează parasimpaticul și reduce tonusul muscular general.</p>
<p>Evaluează dacă există semne de apnee obstructivă de somn. Sforăit puternic, pauze de respirație observate de partener, treziri nocturne cu senzație de sufocare, somnolență diurnă excesivă. Dacă oricare dintre acestea coexistă cu bruxismul, o investigație polisomnografică merită luată în serios. Tratarea apneei rezolvă frecvent și bruxismul asociat.</p>
<p>Evaluează refluxul gastro-esofagian. Arsuri, gust acid dimineața, tuse nocturnă sau senzație de nod în gât pot sugera reflux nocturn. Ridicarea capului patului cu 15-20 de centimetri (nu doar perna suplimentară, ci înclinarea efectivă a patului) și evitarea meselor mari cu 3 ore înainte de culcare reduc refluxul și, indirect, pot reduce bruxismul asociat.</p>
<p>Reducerea alcoolului seara și a cofeinei după ora 14:00 are efect dublu: reduce factorii de activare a bruxismului și îmbunătățește calitatea somnului. Dacă bei alcool regulat seara, încearcă 2-3 săptămâni fără și observă dacă partenerul raportează mai puțin scrâșnit sau dacă semnele matinale se reduc.</p>
<h3>Faza 3 (luna a doua și după): intervenții avansate</h3>
<p>Biofeedback-ul EMG (electromiografic) pentru mușchii masticatori e una dintre cele mai promițătoare intervenții. Dispozitive purtabile măsoară activitatea mușchilor maseter în somn și emit o vibrație ușoară când detectează contracție. Jokubauskas și colegii au publicat în 2018 în Journal of Oral Rehabilitation o meta-analiză care a găsit reduceri de 40-60% în activitatea de bruxism cu biofeedback comparativ cu placebo.</p>
<p>Fizioterapia orofacială e valoroasă dacă există disfuncție de ATM asociată: crepitație, limitarea deschiderii gurii, deviația mandibulei, durere în articulație. Terapia include mobilizări articulare, tehnici miofasciale și exerciții de coordonare neuromusculară.</p>
<p>Dacă bruxismul coexistă cu utilizarea de SSRI, discută cu medicul prescriptor. Buspirone (5-10 mg seara) a fost raportat ca reducând bruxismul indus de SSRI. Ajustarea dozei sau schimbarea antidepresivului pot fi opțiuni. Nu modifica niciodată medicația psihiatrică pe cont propriu.</p>
<p>La nivel de suplimente, magneziul glicinat (300-400 mg seara) susține relaxarea musculară și poate reduce hipertonusul nocturn. Hornyak și colegii au arătat în 1998 în Sleep că magneziul îmbunătățește parametrii somnului la persoanele cu deficit. L-teanina (100-200 mg seara) reduce activitatea beta corticală și poate diminua activarea neuronală care precede episoadele de bruxism.</p>
<p>Injecțiile cu toxină botulinică în mușchii maseter sunt o opțiune pentru bruxismul sever care nu răspunde la alte intervenții. Reduce forța de contracție cu 60-80% și protejează dinții și ATM-ul. Efectul durează 3-6 luni și necesită repetare.</p>
<h2>Unde te lasă toate astea</h2>
<p>Bruxismul nocturn e rareori un fenomen izolat. E aproape întotdeauna conectat cu altceva: stres procesat insuficient, apnee nediagnosticată, reflux, efecte de medicație sau o combinație dintre ele. Gutiera protejează dinții și e un prim pas înțelept, dar oprirea investigației acolo înseamnă să tratezi efectul fără să te uiți la cauză.</p>
<p>Dacă faci bruxism și ai și somnolență diurnă, dacă partenerul raportează și sforăit, dacă te trezești cu gura uscată, investigația pentru apnee nu e opțională. E necesară. Multe cazuri de bruxism se rezolvă odată cu tratarea apneei, fără altă intervenție.</p>
<p>Dacă stresul e factorul dominant, abordarea lui nu e un sfat vag de "relaxează-te." E o serie de instrumente concrete (relaxare musculară, respirație, fizioterapie, biofeedback) care funcționează cu atât mai bine cu cât sunt folosite consistent. Maxilarul tău îți arată noaptea ce nu procesezi ziua. Mesajul merită ascultat.</p>
