<p>Somnul profund necesită o scădere a temperaturii corporale cu 1 până la 1,5 grade. Dacă cearșafurile sau pijamaua sunt din materiale sintetice care rețin căldura și nu absorb transpirația, acest proces e încetinit, iar corpul compensează prin microtreziri de care nici nu ești conștient. Materialul de pe piele contează mai mult decât pare.</p>
<ul>
  <li>De ce cearșafurile și pijamaua pot sabota termoreglarea nocturnă fără să-ți dai seama</li>
  <li>Cum funcționează țesăturile sintetice versus cele naturale în raport cu căldura și umiditatea</li>
  <li>Ce rol joacă temperatura pielii în inițierea și menținerea somnului profund</li>
  <li>Bumbac, in, bambus, lână merinos: proprietăți reale, nu marketing</li>
  <li>Sistemul de plapume pe sezoane (togs) și de ce stratificarea bate grosimea</li>
  <li>Ce faci când partenerul tău vrea altă temperatură la somn</li>
  <li>Transpirațiile nocturne și legătura lor cu materialele din pat</li>
  <li>Un plan practic de tranziție, fără să arunci totul peste noapte</li>
</ul>
<p>Există un detaliu pe care aproape toată lumea îl ignoră când vine vorba de calitatea somnului. Nu e temperatura camerei, nu e cafeaua de după-amiază, nu e ecranul de pe noptieră. E ceea ce ai direct pe piele în cele opt ore în care dormi. Cearșafurile, pijamaua, plapuma. Materialele alea pe care le-ai ales probabil după cum arătau în magazin sau după preț, fără să te gândești că ele interacționează cu corpul tău toată noaptea.</p>
<p>Și nu vorbesc despre confort subiectiv, deși și ăla contează. Vorbesc despre termoregulare, despre capacitatea corpului de a-și ajusta temperatura în timpul ciclurilor de somn. Pentru că somnul profund are nevoie de o scădere de temperatură corporală. Iar dacă materialele în care dormi lucrează împotriva acestui proces, poți face totul corect în restul zilei și tot să te trezești obosit.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Ca să înțelegi de ce materialele contează, trebuie să înțelegi ce face corpul tău cu temperatura în timpul nopții. Nu e un proces static. Temperatura ta centrală scade cu aproximativ 1-1,5 grade Celsius în primele ore de somn, atingând minimul undeva între 3 și 5 dimineața. Această scădere nu e un efect secundar al somnului, ci un mecanism activ care facilitează intrarea în fazele profunde.</p>
<p>Corpul scade temperatura centrală prin vasodilatație periferică. Tradus: trimite sânge spre extremități și spre suprafața pielii ca să radieze căldura în exterior. De aceea ți se încălzesc mâinile și picioarele înainte de a adormi. E un semn bun, înseamnă că procesul funcționează.</p>
<p>Acum gândește-te la ce se întâmplă dacă ai pe tine un material care nu permite căldurii să se disipeze. Polyesterul, nylonul, microfibra sintetică. Aceste materiale sunt, în esență, derivate din plastic. Fibrele lor sunt impermeabile, cu structură închisă. Nu absorb umiditatea, nu permit aerului să circule eficient. Căldura radiată de piele se blochează într-un strat subțire între corp și material, creând un microclim cald și umed.</p>
<p>Corpul detectează asta și răspunde. Crește producția de transpirație pentru a compensa. Dar materialul sintetic nu absoarbe transpirația. O ține pe suprafața pielii. Rezultatul: te trezești transpirat, te miști să cauți o zonă rece a patului, ciclul de somn se fragmentează. Și asta se poate întâmpla fără să ajungi la trezire completă. Microdeșteptări de câteva secunde, suficiente cât să te scoată din somnul profund sau din REM, fără să-ți amintești dimineața.</p>
<p>Un studiu din 2019 publicat în Nature and Science of Sleep a arătat că materialul lenjeriei de pat influențează direct latența somnului și timpul petrecut în fazele profunde. Participanții care dormeau pe cearșafuri de bumbac sau lână aveau cu 15-20 de minute mai mult somn profund decât cei pe sintetice, în condiții identice de temperatură ambientală.</p>
<p>Lâna merinos e probabil cel mai subestimat material pentru somn. Majoritatea oamenilor asociază lâna cu căldura, cu pulovere groase de iarnă. Dar lâna merinos fină funcționează bidirecțional: izolează când e frig și eliberează căldura când temperatura crește. Fibrele de merinos pot absorbi până la 35% din greutatea lor în umiditate fără să se simtă ude la atingere. Studii de la Universitatea din Sydney au demonstrat că participanții care dormeau în pijamale de lână merinos adormeau mai repede și aveau somn mai eficient decât cei în bumbac sau poliester.</p>
<p>Bumbacul rămâne o alegere solidă, accesibilă. Absoarbe umiditatea bine, e respirabil, e ușor de întreținut. Limitarea lui: când se udă (de la transpirație), rămâne ud mai mult timp decât lâna sau inul. Pentru cineva cu transpirații nocturne moderate, bumbacul funcționează. Pentru cineva cu transpirații importante, poate deveni inconfortabil spre dimineață.</p>
<p>Inul (lenul) are o proprietate interesantă: e natural rece la atingere. Fibrele de in sunt mai groase și mai rigide decât cele de bumbac, ceea ce creează mici spații de aer între material și piele. E excelent vara sau pentru dormitoarele mai calde. Absorbția de umiditate e superioară bumbacului. Dezavantajul: se șifonează ușor și are o textură mai aspră inițial, care se îmbunătățește cu spălările repetate.</p>
<p>Bambusul merită menționat cu o nuanță importantă. Bambusul "natural" sună extraordinar din perspectivă de marketing. Dar majoritatea țesăturilor de bambus din comerț sunt de fapt viscoză de bambus, un material procesat chimic care păstrează unele proprietăți ale bambusului original (moliciune, respirabilitate) dar pierde altele. E mai bun decât polyesterul pur, dar nu e materialul miraculos descris în reclame.</p>
<h2>Ce alimentează problema</h2>
<p>Industria lenjeriei de pat a migrat masiv spre sintetice în ultimele două decenii, și motivul e simplu: costă mai puțin la producție, sunt ușor de colorat, rezistă la șifonare și arată bine în ambalaj. Etichetele spun "microfibră premium" sau "satin de lux", dar baza e tot poliester. Cifrele de pe etichetă contează: dacă vezi polyester, poliamidă sau "100% microfibră" fără altă specificație, e sintetic.</p>
<p>Există și o problemă de percepție. Multe persoane care dorm pe sintetice nu fac conexiunea cu calitatea somnului. Se trezesc obosite, eventual transpirare, și pun pe seama stresului sau a vârstei. Pentru că efectul nu e dramatic, e subtil. Nu te trezești udat leoarcă (deși și asta se poate întâmpla). Pur și simplu nu atingi adâncimea de somn de care ai nevoie.</p>
<p>Plapumile adaugă un alt nivel de complexitate. Multe sunt umplute cu fibre sintetice și acoperite cu material sintetic. Chiar și cele cu puf natural pot avea toc sintetic, ceea ce reduce beneficiile. Și grosimea contează diferit de cum cred majoritatea oamenilor: o plapumă prea groasă pentru sezon te supraîncălzește, indiferent de material.</p>
<p>Apoi e factorul cuplu. Două persoane cu metabolisme diferite, preferințe termice diferite, într-un pat cu aceeași plapumă. Unul are cald, celălalt are frig. Compromisul tipic: plapumă medie în care nimeni nu doarme optim.</p>
<h2>Ce poți face</h2>
<p><strong>Faza 1: Evaluează ce ai acum</strong></p>
<p>Verifică etichetele a tot ce ai în pat. Cearșafuri, fețe de pernă, pijama, plapumă (atât umplutura cât și tocul). Notează procentele. Dacă ai peste 50% sintetice la orice piesă care atinge pielea direct, ai identificat un punct de intervenție.</p>
<p>Fă un test simplu: într-o noapte cu temperatură confortabilă în cameră (18-20 grade), observă dacă te trezești transpirat, dacă arunci plapuma peste noapte, dacă cauți zone reci ale patului. Acestea sunt indicii că materialele rețin prea multă căldură.</p>
<p><strong>Faza 2: Prioritizează schimbările</strong></p>
<p>Nu trebuie să înlocuiești totul deodată. Ordinea de impact, de la cel mai mare la cel mai mic:</p>
<p>Cearșaful de pat, pentru că e suprafața cea mai mare în contact cu pielea. Un cearșaf de bumbac percale (nu satin, nu jersey) cu densitate de 200-400 fire e un punct de plecare excelent. Percale are o țesătură strânsă, matură, respirabilă.</p>
<p>Pijamaua sau ce porți la somn. Dacă dormi în tricouri sintetice sau în materiale tip "dry-fit" concepute pentru sport, schimbă la bumbac simplu sau, ideal, lână merinos subțire. Dacă dormi fără nimic pe tine, acest punct nu se aplică, și e probabil un avantaj termic.</p>
<p>Plapuma. Aici intră conceptul de "togs", care e un sistem de clasificare a căldurii plapumilor. Un tog mic (4-7) e pentru vară, un tog mediu (7-10) pentru primăvară și toamnă, un tog mare (10-13) pentru iarnă. Ideea de stratificare: în loc de o plapumă groasă tot anul, ai două subțiri pe care le combini sau le separi în funcție de sezon. Multe sisteme comerciale vând plapume "4 sezoane" care sunt de fapt două plapume cu sistem de prindere.</p>
<p><strong>Faza 3: Rezolvă problema cuplului</strong></p>
<p>Scandinavia a rezolvat asta demult: fiecare persoană are plapuma ei. Sună ciudat cultural, dar funcțional e logic. Partenerul care are tendință de supraîncălzire ia o plapumă de tog mai mic, eventual din materiale diferite. Cel care are frig ia un tog mai mare. Aceeași dimensiune de pat, aceeași apropriere fizică, dar termoregulare individualizată.</p>
<p>Dacă ideea a două plapume nu funcționează estetic sau practic pentru voi, alternativa e o plapumă din lână sau puf natural de tog mediu, combinată cu un strat suplimentar (o pătură subțire) pentru persoana care are frig. Stratul suplimentar se adaugă sau se elimină fără să deranjeze pe celălalt.</p>
<p><strong>Faza 4: Transpirațiile nocturne</strong></p>
<p>Dacă transpirațiile nocturne sunt o problemă recurentă, materialele sunt primul lucru de verificat, dar nu singurul. Transpirațiile nocturne au cauze multiple: hormonale (perimenopauza, testosteron scăzut), metabolice (hipoglicemie nocturnă), infecțioase sau medicamentoase. Dacă schimbarea materialelor nu aduce îmbunătățire în 2-3 săptămâni, merită investigat medical.</p>
<p>Pentru transpirații nocturne, inul și lâna merinos bat bumbacul. Inul pentru efect de răcire, merinos pentru gestionarea umidității. Există și protecții de saltea din materiale naturale cu strat impermeabil respirabil care protejează saltea fără să creeze efect de seră.</p>
<p><strong>Faza 5: Suplimente și ajustări fine</strong></p>
<p>Nu există suplimente care să compenseze un mediu termic prost la somn. Dar dacă optimizezi materialele și tot ai probleme de termoregulare nocturnă, magneziu glicinat (200-400 mg) înainte de culcare poate ajuta prin efectul său de relaxare a vaselor periferice, facilitând disiparea căldurii. Glicina însăși, aminoacidul, a fost studiată pentru capacitatea de a reduce temperatura centrală. Nu e un truc, e un mecanism fiziologic documentat.</p>
<h2>Unde te lasă asta</h2>
<p>Probabil că nu te-ai gândit niciodată la cearșafuri ca la un factor de sănătate. E normal. Nimeni nu vorbește despre asta pentru că nu e spectaculos, nu se vinde ca supliment și nu are niciun guru asociat. Dar corpul tău interacționează cu aceste materiale opt ore pe noapte, 365 de nopți pe an. Asta înseamnă că o îmbunătățire mică aici se multiplică enorm în timp. Nu trebuie să devii obsesiv cu fibrele textile. Trebuie doar să nu lucrezi activ împotriva a ceea ce corpul tău încearcă să facă în somn. Verifică etichetele, schimbă ce poți, observă ce se întâmplă. Răspunsul corpului tău va fi destul de clar.</p>
