<p>Aproximativ 90% din serotonina organismului se produce în intestin, nu în creier, iar serotonina e precursorul direct al melatoninei. Dacă flora intestinală e dezechilibrată, acest lanț biochimic se perturbă, și efectele se simt cel mai clar noaptea, în calitatea somnului.</p>
<ul>
  <li>Aproximativ 90% din serotonina organismului e produsă în intestin, nu în creier, iar serotonina e precursorul direct al melatoninei.</li>
  <li>Bacteriile intestinale nu doar digeră mâncarea. Produc neurotransmițători, acizi grași cu lanț scurt și molecule de semnalizare care ajung la creier prin nervul vag, sânge și sistemul imunitar.</li>
  <li>Disbioza (dezechilibrul florei intestinale) crește inflamația sistemică, iar citokinele inflamatorii perturbă direct somnul profund și arhitectura somnului.</li>
  <li>Fermentația nocturnă excesivă, cauzată de anumite bacterii care prosperă pe zaharuri și carbohidrați procesați, produce gaze și disconfort care fragmentează somnul fără să genereze simptome digestive evidente ziua.</li>
  <li>Antibioticele, zahărul rafinat, stresul cronic și lipsa fibrelor sunt factorii principali care destabilizează microbiomul.</li>
  <li>Butiratul, un acid gras cu lanț scurt produs de bacteriile benefice din fibre, întărește bariera intestinală și reduce inflamația. Lipsa lui permite trecerea în sânge a unor molecule care nu ar trebui să ajungă acolo.</li>
  <li>Alimentele fermentate și fibrele prebiotice au dovezi mai solide decât suplimentele probiotice pentru îmbunătățirea compoziției microbiomului.</li>
  <li>Reconstruirea unui microbiom sănătos cere săptămâni și luni, nu zile. Consistența alimentară contează mai mult decât orice supliment individual.</li>
</ul>
<p>Dacă ți-ar spune cineva că o parte din motivul pentru care dormi prost ar putea fi legată de ce se întâmplă în intestinul tău, reacția naturală ar fi scepticismul. Somnul e o funcție a creierului, digestia e o funcție a abdomenului, și cele două par să aparțină unor lumi diferite. Dar cercetarea ultimului deceniu a arătat că această separare e o iluzie anatomică. Intestinul și creierul comunică constant, bidirecțional, printr-o rețea de semnale chimice, neuronale și imunitare pe care cercetătorii o numesc axa intestin-creier.</p>
<p>Ce e mai puțin intuitiv e cât de mult din această comunicare e mediată de bacteriile care trăiesc în intestin. Microbiomul intestinal, comunitatea de aproximativ 38 de trilioane de microorganisme care populează tractul digestiv, nu e un pasager inert. Produce substanțe neuroactive, influențează inflamația și modifică disponibilitatea precursorilor din care creierul își construiește neurotransmițătorii necesari pentru somn. Când această comunitate e în echilibru, semnalele susțin un somn stabil. Când e perturbată, efectele se simt noaptea.</p>
<h2>Ce se întâmplă de fapt</h2>
<p>Cel mai bun loc de unde să începi e serotonina. În cultura populară, serotonina e asociată cu creierul și cu starea de bine. Dar aproximativ 90% din serotonina organismului e produsă în celulele enterocromafine din mucoasa intestinală, nu în neuroni. Yano și colaboratorii de la Caltech au publicat în 2015 în Cell un studiu care a demonstrat că bacteriile intestinale stimulează direct celulele enterocromafine să producă serotonină. Șoarecii crescuți în mediu steril (fără bacterii intestinale) aveau niveluri de serotonină în colon cu 60% mai mici decât șoarecii normali. Reintroducerea anumitor specii bacteriene (în special din genul Clostridium) a restaurat producția.</p>
<p>De ce contează asta pentru somn? Serotonina e precursorul direct al melatoninei. Enzima AANAT transformă serotonina în N-acetilserotonină, care e apoi convertită în melatonină de enzima HIOMT. Dacă producția de serotonină e compromisă la sursă (în intestin), disponibilitatea precursorilor pentru melatonină scade. Nu e o relație directă și simplă, serotonina intestinală nu traversează bariera hemato-encefalică, dar influențează disponibilitatea triptofanului (aminoacidul precursor) prin competiție metabolică. Când intestinul consumă mai mult triptofan pentru a produce serotonină locală, rămâne mai puțin disponibil pentru creier.</p>
<p>Dar microbiomul influențează somnul și prin alte canale. Nervul vag, cel mai lung nerv cranial, conectează direct intestinul cu trunchiul cerebral. Aproximativ 80% din fibrele nervului vag sunt aferente, adică transportă informații de la intestin către creier, nu invers. Bacteriile intestinale produc metaboliți (acizi grași cu lanț scurt, GABA, triptofan modificat) care activează receptorii de pe terminațiile vagale și trimit semnale directe către centrele cerebrale implicate în reglarea somnului.</p>
<p>Butiratul merită o mențiune separată. E un acid gras cu lanț scurt produs de bacterii precum Faecalibacterium prausnitzii și Roseburia intestinalis prin fermentația fibrelor alimentare. Butiratul are cel puțin trei roluri relevante pentru somn. Întâi, e sursa principală de energie pentru celulele epiteliale ale colonului și menține integritatea barierei intestinale. Când butiratul scade, spațiile dintre celulele intestinale se lărgesc, permițând trecerea în sânge a unor molecule bacteriene (lipopolizaharide, sau LPS) care nu ar trebui să ajungă acolo. Al doilea, butiratul are proprietăți antiinflamatorii directe, reducând producția de citokine proinflamatorii. Al treilea, un studiu din 2019 publicat de Szentirmai și colaboratorii, publicat în Scientific Reports, a arătat că administrarea de butirat la șoareci a crescut durata somnului non-REM cu 50% și a redus temperatura corpului, sugerând un efect direct asupra mecanismelor somnului.</p>
<p>Inflamația e canalul prin care disbioza afectează somnul cel mai agresiv. Când bariera intestinală e compromisă (așa-numitul "intestin permeabil" sau permeabilitate intestinală crescută), fragmentele bacteriene din intestin ajung în circulația sangvină și activează sistemul imunitar. Citokinele proinflamatorii rezultate, în special IL-6 și TNF-alfa, au efecte directe asupra arhitecturii somnului. Mullington și colaboratorii au publicat în 2010 în Best Practice &amp; Research Clinical Endocrinology &amp; Metabolism o analiză care a arătat că nivelurile crescute de IL-6 și TNF-alfa sunt asociate cu somn fragmentat, reducerea somnului profund și somnolență diurnă excesivă. Inflamația nu te împiedică neapărat să dormi, dar schimbă calitatea a ceea ce se întâmplă în timp ce dormi.</p>
<p>Un fenomen pe care puțini îl iau în considerare e fermentația nocturnă excesivă. Anumite bacterii (în special din genul Klebsiella, Citrobacter și unele specii de Streptococcus) fermentează carbohidrații și zaharurile cu producție mare de gaze. Dacă cina a fost bogată în carbohidrați simpli și flora intestinală e dominată de aceste specii fermentative, producția de gaze crește în primele ore ale nopții. Distensia abdominală și disconfortul rezultat pot fragmenta somnul fără să producă simptome digestive pe care să le identifici conștient. Te trezești, nu știi de ce, te întorci pe altă parte și adormi la loc. Dimineața nu ai amintirea unei probleme digestive, dar somnul a fost fragmentat.</p>
<h2>Ce alimentează problema</h2>
<p>Antibioticele sunt perturbatorul cel mai documentat al microbiomului. Un singur curs de antibiotice cu spectru larg poate reduce diversitatea bacteriană cu 30-40%, iar recuperarea completă poate dura 6-12 luni, uneori mai mult. Jernberg și colaboratorii au publicat în 2010 în Microbiology un studiu care a arătat că anumite modificări ale microbiomului persistau și la 2 ani după un singur curs de clindamicină. Antibioticele nu sunt opționale când sunt necesare medical, dar efectele lor pe microbiom sunt reale și subestimate.</p>
<p>Zahărul rafinat și carbohidrații ultraprocesați hrănesc preferențial bacteriile fermentative și reduc populațiile producătoare de butirat. Un studiu publicat de David și colaboratorii în Nature în 2014 a arătat că schimbările în dietă modifică compoziția microbiomului în mai puțin de 24 de ore. O dietă bogată în zahăr și săracă în fibre, menținută săptămâni sau luni, produce o comunitate bacteriană dominată de specii care prosperă pe zaharuri simple și care produc mai puțini acizi grași benefici.</p>
<p>Stresul cronic afectează microbiomul prin mai multe mecanisme. Cortizolul crescut modifică motilitatea intestinală, reduce secreția de mucus protector și alterează pH-ul intestinal. Bailey și colaboratorii au publicat în 2011 în Brain, Behavior, and Immunity un studiu care a arătat că stresul social la șoareci a redus populația de Lactobacillus și a crescut aderența bacteriilor patogene la mucoasa intestinală. La oameni, studii similare au arătat că perioadele de stres intens (examene, doliu, traume) sunt urmate de modificări detectabile în compoziția microbiomului.</p>
<p>Lipsa fibrelor alimentare e probabil cel mai persistent factor. Fibrele sunt substratul din care bacteriile benefice produc butirat, propionat și acetat. Fără fibre, aceste populații se reduc, iar bariera intestinală se slăbește treptat. Dieta modernă occidentală conține în medie 15 grame de fibre pe zi, jumătate din minimul recomandat de 25-30 de grame.</p>
<p>Somnul prost însuși agravează disbioza, creând un cerc vicios. Benedict și colaboratorii au publicat în 2016 în Molecular Metabolism un studiu care a arătat că două nopți de privare parțială de somn au modificat raportul Firmicutes/Bacteroidetes și au crescut abundența bacteriilor asociate cu inflamația. Somnul fragmentat perturbă microbiomul, iar microbiomul perturbat fragmentează și mai mult somnul.</p>
<h2>Ce poți face concret</h2>
<h3>Faza 1 (săptămânile 1-3): fundația alimentară</h3>
<p>Fibrele sunt intervenția cu cele mai multe dovezi și cel mai mare impact pe microbiom. Creșterea treptată a aportului de fibre de la nivelul actual (probabil 12-18 grame) către 30-35 de grame pe zi, pe parcursul a 2-3 săptămâni, e punctul de plecare. Treptată e cuvântul cheie. O creștere bruscă a fibrelor produce balonare și disconfort, exact ce vrei să eviți.</p>
<p>Surse concrete: leguminoasele (linte, năut, fasole) oferă 7-10 grame de fibre per porție. Ovăzul integral conține 4 grame per 40 de grame. Fructele cu coajă (mere, pere) adaugă 3-5 grame. Semințele de in (2 linguri) oferă 4 grame. Legumele crucifere (brocoli, conopidă, varză de Bruxelles) contribuie cu 3-5 grame per porție. Nu trebuie să le adaugi pe toate simultan. O sursă nouă la fiecare 4-5 zile permite intestinului să se adapteze.</p>
<p>Alimentele fermentate introduc bacterii vii și metaboliți benefici. Iaurtul cu culturi vii, kefir, varza murată (cea nepasteurizată, din raft frigider, nu cea din conservă), kimchi, miso. Un studiu randomizat controlat publicat de Wastyk și colaboratorii în Cell în 2021 a comparat o dietă bogată în alimente fermentate cu o dietă bogată în fibre pe parcursul a 10 săptămâni. Grupul cu alimente fermentate a arătat o creștere a diversității microbiene și o reducere a 19 markeri inflamatori. Grupul cu fibre a arătat beneficii diferite (creșterea capacității de degradare a carbohidraților) dar fără aceeași reducere a inflamației pe termen scurt. Concluzia practică: ambele sunt importante, dar alimentele fermentate par să acționeze mai rapid asupra inflamației.</p>
<p>Reducerea zahărului rafinat și a carbohidraților ultraprocesați la cină e o intervenție care servește și microbiomul, și fermentația nocturnă. O cină bazată pe proteine, grăsimi sănătoase, legume și o porție moderată de carbohidrați complecși produce mai puțină fermentație nocturnă decât o farfurie de paste cu sos dulce.</p>
<h3>Faza 2 (săptămânile 4-8): consolidare și observație</h3>
<p>Consistența contează mai mult decât perfecțiunea. Bacteriile benefice nu se instalează după o săptămână de iaurt și linte. Colonizarea stabilă cere un mediu care le susține în mod repetat. Un studiu din 2018 publicat de Zmora și colaboratorii în Cell a arătat că probioticele administrate oral colonizează intestinul diferit la fiecare persoană și că succesul colonizării depinde de compoziția preexistentă a microbiomului. Mediul intestinal trebuie pregătit prin dietă înainte ca bacteriile noi să poată prospera.</p>
<p>Gestionarea stresului nu e o recomandare vagă aici. Cortizolul afectează direct microbiomul, și tehnicile care îl reduc (respirație diafragmatică, plimbări în natură, conexiune socială, somn regulat) au efecte măsurabile pe flora intestinală. Activarea vagală prin respirație lentă (4-6 respirații pe minut) îmbunătățește motilitatea intestinală și crește tonusul vagal, ambele benefice pentru microbiom.</p>
<p>Observă dacă există corelații între anumite alimente și calitatea somnului. Un jurnal alimentar simplu ținut 2-3 săptămâni, corelat cu un jurnal de somn, poate scoate la iveală tipare pe care nu le-ai observa altfel. Anumite persoane descoperă că lactate specifice, leguminoasele în cantitate mare la cină sau anumite fructe uscate le agravează simptomele nocturne.</p>
<h3>Faza 3 (luna a treia și după): intervenții țintite</h3>
<p>Probioticele ca suplimente au date mixte, dar câteva tulpini au dovezi specifice pentru somn. Lactobacillus rhamnosus și Bifidobacterium longum au arătat în studii clinice efecte asupra axei cortizol-stres. Un studiu randomizat controlat publicat de Nishida și colaboratorii în 2019 în Beneficial Microbes a arătat că suplimentarea cu Lactobacillus gasseri CP2305 pe parcursul a 5 săptămâni a îmbunătățit calitatea somnului măsurată prin actigrafie la adulți cu stres moderat. Dar probioticele nu funcționează în absența unei diete care le susține. Sunt un adjuvant, nu o soluție de sine stătătoare.</p>
<p>Prebioticele concentrate (inulină, fructooligozaharide, galactooligozaharide) pot fi adăugate dacă aportul de fibre din alimente e încă insuficient. Doza de start e mică (2-3 grame pe zi) cu creștere treptată. Efectele pe balonare sunt reale la doze mari introduse brusc.</p>
<p>L-glutamina (3-5 grame pe zi) are date privind repararea barierei intestinale, deși studiile sunt în mare parte pe populații cu boli intestinale inflamatorii, nu pe populația generală. Omega-3 din ulei de pește (1-2 grame pe zi) reduce inflamația sistemică și are efecte indirecte pe permeabilitatea intestinală.</p>
<p>Testarea microbiomului prin secvențiere (disponibilă comercial prin diverse companii) poate oferi informații despre compoziția bacteriană, dar interpretarea rezultatelor rămâne limitată. Știm încă prea puțin despre ce înseamnă un microbiom "optim" ca să putem face recomandări foarte precise pe baza unui test.</p>
<h2>Unde te lasă toate astea</h2>
<p>Conexiunea intestin-somn nu e o modă. E susținută de mecanisme concrete: serotonină intestinală, butirat, inflamație, semnalizare vagală. Dar e o conexiune lentă. Microbiomul nu se schimbă într-o săptămână, iar efectele pe somn apar gradual, pe parcursul săptămânilor și lunilor.</p>
<p>Ce merită reținut e că investiția în diversitatea alimentară și în reducerea inflamației intestinale nu produce beneficii doar pentru somn. Aceleași intervenții îmbunătățesc digestia, energia diurnă, imunitatea și starea emoțională. E una dintre puținele situații în care o singură direcție de acțiune influențează pozitiv mai multe sisteme simultan.</p>
<p>Dacă ai somn fragmentat și nu ai găsit o cauză clară până acum, iar alimentația ta e săracă în fibre și bogată în alimente procesate, ai un experiment simplu de făcut. Trei săptămâni de leguminoase zilnice, alimente fermentate și reducerea zahărului rafinat. Costul e zero, riscul e zero, iar dacă somnul se îmbunătățește, ai un indiciu puternic despre unde să continui să sapi.</p>
